### ISSUE TITLE
DATE column is not dehydrated as datetime.date type

### ISSUE THREAD

**Issue by kunxi** [pymssql/pymssql#156]
We have a table with `DATE` column _start_on_, which is not dehydrated as `datetime.date` type in the select query as the following:

``` python
>>> cur.execute_query('select id, start_on from surveys').fetchone()
[(1, u'2011-02-03'), ]

>>> cur.execute_query('SELECT id, CONVERT(datetime, start_on) from surveys').fetchone()
[(1, datetime.datetime(2011, 2, 3, 0, 0),), ]
```

**Comment by epa** [comment]
I believe that recent FreeTDS versions (0.95) onwards do support date, time, and datetime2 (see the NEWS file).  What now needs to be done for them to be supported in pymssql?
