### ISSUE TITLE
binary columns sometimes are processed as varchar

### ISSUE THREAD

**Issue by reox** [pymssql/pymssql#177]
In some rare cases the query for a binary field is generated as string, which causes SQL Server to fail, because implicit conversion from varchar to binary is not supported.

Database:

``` sql
create table test (id int not null, hash binary(16) not null);
```

python code:

``` python
hashes = [] 
# generate hashes
for string in longlistofstrings:
    hashes.append(hashlib.md5(string).digest())
cursor.executemany("insert into test (id, hash) values (123, %s)", hashes)
```

if the hash is like 0x7B7A0A030719343B03346C453449536F, pymssql generates a query like:

``` sql
insert into test (id, hash) values (1135226, '{z\n\x03\x07\x194;\x034lE4ISo')
```

which should be 

``` sql
insert into test (id, hash) values (1135226, 0x7B7A0A030719343B03346C453449536F)
```

you can recreate the digest from an integer by using:

``` python
foo = 0x7B7A0A030719343B03346C453449536F
digest = "".join([chr((foo>>i*8)&0xFF) for i in range(16)][::-1])
```

I'm using Version 2.0.0

**Comment by ryanbentleyxz** [comment]
I'm experiencing this issue with latest pymssql from pip3

        hash_ = hashlib.sha512(password.encode() + hash_.encode()).digest()
        hash_ = binascii.hexlify(hash_)
        return hash_
