### ISSUE TITLE
An issue with UTF-8 and parameters

### ISSUE THREAD

**Issue by vytautas** [pymssql/pymssql#185]
There is an issue with parameter substitution if the query contains UTF-8 strings. Parameter positions are incorrect because RE matching and substitution is made on different encodings of the string.

Test:
```python
from _mssql import substitute_params
print(substitute_params("testing ascii (abc) 1=%d 'one'=%s", (1, 'one')))
print(substitute_params("testing ascii (ąčę) 1=%d 'one'=%s", (1, 'str')))
```
Results (python 3.2.3):
```python
b"testing ascii (abc) 1=1 'one'=N'one'"
b"testing ascii (\xc4\x85\xc4\x8d\xc4\x99)1=%d 'onN'str'=%s"
```

**Comment by The-Compiler** [comment]
I can confirm this on Python 3.4.3. I have `... row_id != %(row_id_1)s` in my query and `... item.row_id !0)s` gets sent, i.e. shifted two characters to the left. I have two `ü`s in my query.
