### ISSUE TITLE
Support bulk load protocol like bcp uses?

### ISSUE THREAD

**Issue by rsyring** [pymssql/pymssql#279]
We have a project coming up to migrate some legacy code that is currently shelling out to bcp.  I've been thinking this might be a good opportunity to enhance pymssql to give it the ability to bulk-load data.  Anyone know anything about how this might work and/or if freetds has support for this?

**Comment by ramiro** [comment]
Sound like a good idea, yes. See e.g.

http://www.freetds.org/reference/a00286.html

**Comment by zeitgeber** [comment]
Is there a plan to incorporate sql bulk copy in the near future? I am running into an issue where the sql insert is very slow and would like to use bulk copy instead.

**Comment by rsyring** [comment]
My company will have need of this feature in the next 3-6 months so it seems likely we will work on incorporating it at some point.  Also James Lowden, a former maintainer of FreeTDS, recently sent an email to me and in it he expressed interest in getting BCP working in pymssql.

**Comment by andreacassioli** [comment]
Hi,
any progress on this issue? That seems a pretty much needed functionality....

**Comment by rsyring** [comment]
@andreacassioli I was hoping we had a project for a customer that was going to need this and therefore we'd get paid time to work on it.  That has since been solved a different way, so my plans have fallen through.  

I haven't heard anything further from James Lowden either.

I think Ramiro is doing all he can to just keep pymssql updated with FreeTDS updates and basic maintenance.  So, unless pymssql get some additional contributors who could tackle a project like this (or someone is able to pay for development of the feature), I don't see it moving along anytime soon.

**Comment by andreacassioli** [comment]
@rsyring Thank you for the update.

It is really a pity, if I could I would really love to help.

Actually I was looking to bulk import as I cannot get decent speed using executemany, I have seen a couple of issue open on that, but I am not sure how do you think to address it.

**Comment by andreacassioli** [comment]
I am sure you know, but I stumble accross this

https://github.com/zillow/ctds

it supports bulk insertion using bcp.
