### ISSUE TITLE
What packages should be built for each release?

### ISSUE THREAD

**Issue by rsyring** [pymssql/pymssql#282]
I have created this wiki page to document the packages we need to build when making a release.

https://github.com/pymssql/pymssql/wiki/Build-Matrix

This was created by looking at what @msabramo released for 2.1.0.  However, I have questions:

* It doesn't look like we are building wheels for Linux.  I know we had problems getting compatability across different linux distributions with our binary builds.  Is this the reason we aren't releasing Linux wheels and eggs?
* How hard is it to build for the older releases of OSX?  I'd like to not commit to officially building for anything earlier than the current version of OSX.
* bitness: are the builds for OSX 32 or 64 bit?  I see that the 10.4 builds specify 64 bit.  Should we build 32 bit or 64 bit (or both) for Windows?

Any other thoughts?  @msabramo if you could give some thoughts on this issue, based on what you've been thinking with prior releases, I'd apprecaite it.

**Comment by rsyring** [comment]
We had talked about supporing MSI files vs EXE files.  I'm to the point where I think wheel's have taken off enough in the Python community that we should only be producing wheels.

Proposed support matrix:

|        | Linux | Windows | OSX 10.? |
|--------|-------|---------|----------|
| source | x     | x       | x        |
| wheel  | 64       |  32/64       |  32/64        |

Python versions 2.6-7,3.3-5

Questions remaining:

* what version(x) of OSx can/should we build for?
* should we still support Python 2.6 and 3.3?
* Do we have the ability to build the Windows binaries w/ SSL support?

**Comment by ramiro** [comment]
We've adopted @rsyring proposal above. For release 2.1.2 we shipped:

* a sdist tarball
* Windows binary wheels for all supported Python versions.

The only missing binaries are  OS X wheels because we don't have access to such a system.

We'll monitor devopments in the PEP 313 front to evaluate if/when to add Linux binary wheels.
