### ISSUE TITLE
RPC Float Type

### ISSUE THREAD

**Issue by woozyking** [pymssql/pymssql#287]
Hi,

We recently ran into an issue when we pass in float type params for a stored procedure. The error is `NotSupportedError: Unable to determine database type from python float type`, and by looking at https://github.com/pymssql/pymssql/blob/dd42d5e962cd42eeb8e6ce24a0a09135e92ef990/pymssql.pyx#L99 we realized that there's no map for float. Is there any particular reason why it's like that? Float type has a more common usage than Decimal in Python

**Comment by ramiro** [comment]
Good catch.

Patches welcome. Bonus points if they incldue testa and docuemnation additions.

**Comment by rsyring** [comment]
@woozyking: can you test @bladams patch on PR #304 and let us know if that fixes your problem please.

**Comment by woozyking** [comment]
@rsyring did a simple RPC and it seems to be working :+1:

**Comment by ramiro** [comment]
Fixed in 660044757890f18374fc474011dc627281c1144b
