### ISSUE TITLE
login password limited to 30 characters

### ISSUE THREAD

**Issue by paulrentschler** [pymssql/pymssql#288]
Connecting to a MSSQL database with a password that is longer than 30 characters results in a generic login failed error message.

Tested with pymssql v2.1.0 and FreeTDS v0.91 on Ubuntu 14.04 with python 2.7.6 against MS SQL Server 10.50.2500 and MS SQL Server 2012 v11.0.5058.0.

```
$ tsql -C
Compile-time settings (established with the "configure" script)
                            Version: freetds v0.91
             freetds.conf directory: /etc/freetds
     MS db-lib source compatibility: no
        Sybase binary compatibility: yes
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 4.2
                              iODBC: no
                           unixodbc: yes
              SSPI "trusted" logins: no
                           Kerberos: yes
```

This does not appear to be a FreeTDS issue as connecting to the server with a password greater than 30 characters works with the tsql commandline tool.

Code to reproduce the error:

```
import _mssql
_mssql.connect(
    server='192.168.0.1',
    user='test',
    password='a really super long password more than 30 characters',
    database='Northwind'
    )
*** MSSQLDatabaseException: (18456, "Login failed for user 'test'.DB-Lib error message 18456, severity 14:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20002, severity 9:\nAdaptive Server connection failed\n")
```

Also errors importing pymssql and using pymssql.connect()

**Comment by labynocle** [comment]
Hi there,

I created a PR to add an entry in the FAQ about this issue: (cf PR #470)
Feel free to accept and complet it :)
