### ISSUE TITLE
Integrate with Appveyor

### ISSUE THREAD

**Issue by rsyring** [pymssql/pymssql#303]
http://www.appveyor.com/

**Comment by ramiro** [comment]
I'm giving this a try. See https://github.com/ramiro/pymssql/tree/appveyor and https://ci.appveyor.com/project/ramiro/pymssql

I'd like to use this for two things we badly need (and have their own tickets):

* Generate Windows release binaries, which we could do directly from AppVeyor without having to maintain a local Windows system/VM with different Python, Visual C, SQL Server etc. versions, x86/x64  and at the same time reducing the friction of tagging a pymssql release of which Windows distributables are the greater pain.
* Documenting the release process

I believe it would be nice to also have similar a Windows FreeTDS CI setup which pushes the resulting binaries to somewhere the pymssql AppVeyor Windows jobs can fetch from. These FreeTDS binaries would have SSL linked in so connections with Azure work (something I missed in the 2.1.1 Windows .exe installers/wheels).

Currently the only job is the one that compiles pymssql for Python 2.7 and uses the (win x86, complied with Visual Studio 2008) FreeTDS 0.91 libs we currently bundle. Jobs for other Pythons and x64 can be activated oce we have corresponding FreeTDS binaries.

**Comment by ramiro** [comment]
Fixed in https://github.com/pymssql/pymssql/commit/c1ae24bf73dcd1f5d42bb9d2635d7940d3c91b8e
