### ISSUE TITLE
Connection Pool?

### ISSUE THREAD

**Issue by woozyking** [pymssql/pymssql#306]
I can't seem to find a sure answer in the documentation. Is this implemented? We tried to apply singleton on connection object but that lead to some issues, so we had to switch to fresh connect/close for every query we fire to the SQL server.

In fact we followed the documented way of using `with` to automatically do that in context.

How can we make the connection reusable so that we don't have to start a new connection every time? At scale it gets really expensive.

**Comment by damoxc** [comment]
You could use pymssql through SQLAlchemy (http://docs.sqlalchemy.org/en/latest/core/pooling.html) which provides connection pooling. Or there are other DB-API 2.0 connection pooling libraries available as well. Connection pooling itself is something that is out of scope for this library.
