### ISSUE TITLE
Does not work with pypy

### ISSUE THREAD

**Issue by dholth** [pymssql/pymssql#308]
It looks like pymssql can't compile under PyPy. Two obvious things prevent it from compiling. It inherits from PyBaseExceptionObject, missing in PyPy, and it calls `isinstance(value, bytearray)`, also missing in PyPy's CPYEXT.

**Comment by rsyring** [comment]
Thanks for the report.  Not sure anyone on the current maintainers team has experience with PyPy and our development time is pretty thin as-is.  I think we'd welcome a PR as long as it didn't affect compatibility or functionality in CPython.

**Comment by rsyring** [comment]
closing due to time
