### ISSUE TITLE
Not working on linux 32bit

### ISSUE THREAD

**Issue by LEALCorentin** [pymssql/pymssql#310]
You need to recreate the libsybdb.a for nix_32 with the default path not someone's.

Link to the commit which resolve the problem on 64 bit : https://github.com/pymssql/pymssql/commit/24cea499ac711bf92100895694c3badaab90f7c0?diff=unified

You need to do the same for 32 bits.

Thanks for your work.

**Comment by ramiro** [comment]
Fixed with the release of 2.1.2.

See http://pymssql.org/en/latest/freetds.html#linux
