### ISSUE TITLE
Drop support for FreeTDS older than 0.91

### ISSUE THREAD

**Issue by ramiro** [pymssql/pymssql#315]
I'd like to propose that for the next pymssql release (2.1.2) we state explicitly in our docs the oldest FreeTDS version suppoorted is 0.91.

Rationale for this:

* 0.82 was released in May 2008
* 0.91 was released in August 2011
* We actually bundle FreeTDS 0.91 static binaries already
* The next FreeTDS version (to be named 0.95) is nearing completion (Thanks Frediano Ziglio @freddy77 and co.!)
* I'm not sure any of the pymssql dev team members do actually build and test against FreeTDS 0.82 (could be wrong here). I don't. Our CI setup uses 0.91 

Regarding the risk of leaving users of older stacks unsupported:
* Ubuntu already ships FreeTDS 0.91 with all their currently supported (12.04, 14.04) releases (see http://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=freetds-dev&searchon=names). 10.04 which ships 0.82 reaches EOL on April 30 2015.
* Debian ships FreeTDS 0.91 with its current stable release 7.x Wheezy (see https://packages.debian.org/search?keywords=freetds-dev).
* I cant find if RHEL and Suse do actually ship official FreeTDS RPM packages to confirm their versions 
* AFAICS FreeBSD ports already build FreeTDS 0.9x only.
  
If RHEL and Suse do actually include and support FreeTDS older than 0.91, then for users of stacks based on them choices are:
* Fetch 0.91 from third party (vendor-blessed or not) repositories like EPEL, etc. 
* Stay with pymssql <= 2.1.1
* Build FreeTDS manually

Same thing would apply to Debian users on current 'oldstable' (6.x Squeeze) and for Windows users.

**Comment by rsyring** [comment]
+1.  But we should bump our version to to 2.2.0 instead of 2.1.2.
