### ISSUE TITLE
Problem with transactions on pymssql module

### ISSUE THREAD

**Issue by noapex** [pymssql/pymssql#324]
Hi, using pymssql module I can't make any queries. I get this error message:
"The operation could not be performed because the OLE DB provider 'SQLOLEDB' was unable to begin a distributed transaction.DB-Lib error message 7391, severity 16: General SQL Server error: Check messages from the SQL Server"
If I switch to _mssql module I have no problems. The only difference I see in logs is that pymssql starts a transaction before executing the query.
Is there a way to switch off auto transactions on pymssql?

Cheers

**Comment by rsyring** [comment]
Please use the mailing list for questions like this.  https://groups.google.com/forum/#!forum/pymssql

Not sure if it's documented, but you can turn off the autocommit logic:

https://github.com/pymssql/pymssql/blob/master/pymssql.pyx#L245
https://github.com/pymssql/pymssql/blob/master/pymssql.pyx#L260

Seems to me that the flag might work in the inverse way of what might be intuitive.  Regardless, you can set it one way, then the other, and test as necessary.
