### ISSUE TITLE
SQL Azure connectivity issue on Windows

### ISSUE THREAD

**Issue by meet-bhagdev** [pymssql/pymssql#327]
I successfully used pymssql to conenct to Azure SQL DB on my ubuntu machine, however if I copy the code over to my windows machine I get the following error message : adaptive server connection failed

I have FreeTDS installed. Is this an issue or did I not install FreeTDS correctly. I made sure i configured it with openssl and followed all your instructions.

Here is my code : 
mport pymssql
conn = pymssql.connect(server='myserver.database.windows.net', user='myusername@myserver', password='mypassword', database='mydatabase')
cursor = conn.cursor()
cursor.execute("INSERT SalesLT.Product (Name, ProductNumber, StandardCost, ListPrice, SellStartDate) OUTPUT INSERTED.ProductID VALUES ('SQL Server Express', 'SQLEXPRESS', 0, 0, CURRENT_TIMESTAMP)")
row = cursor.fetchone()
while row:
    print "Inserted Product ID : " +str(row[0])
    row = cursor.fetchone()

Thanks,
Meet

**Comment by ramiro** [comment]
Make sure you build FreeTDS yourself with SSL enabled and that you actrually link in OpenSSL or GNUTLS.

The 2.1.1 Windows binaries we shipped include FreeTDS linked in statically but they DON'T have the SSL feature enabled so I suspect that's the reason it can't be used to connect to Azure.

Any help in getting FreeTDS Windows builds to link in any of the external libraries which provide SSL support is gratly welcome. Hopefully with that ehlo wi'll be able to ship Windows pymssql binaries with such capability.

**Comment by meet-bhagdev** [comment]
Thanks for the quick response ramiro.
Do you have recommended instructions to build FreeTDS with the specific requirements for SQL Azure? Also will I have to manually tell pymmsql where(file path) my FreeTDS is installed?

**Comment by ramiro** [comment]
> Do you have recommended instructions to build FreeTDS with the specific requirements for SQL Azure?

No. That's why we ask for help.
>Also will I have to manually tell pymmsql where(file path) my FreeTDS is installed?

Once you get your FreeTDS static libs built, put them under the `freetds/` subdir in the pymssql source tree possibly overwriting the contents of the `vs2008_32/` subdir (depending on your Visual Studio and CPU architecture) and then proceed to build pymssql as is usual with Python modules: `python setup.py bdist_wininst` or any other relevant target (i.e. to build wheels, or a .msi file)

**Comment by meet-bhagdev** [comment]
I see, so using pip on windows to get pymssql is not an option?

**Comment by ramiro** [comment]
No if you want to use SSL, because `pip install pymssql` will fetch our binaries from PyPI.

**Comment by meet-bhagdev** [comment]
Got it! Thank you, let me try to make this work.

**Comment by cgohlke** [comment]
@meet-bhagdev can you try the binaries at http://www.lfd.uci.edu/~gohlke/pythonlibs/#pymssql ?

**Comment by meet-bhagdev** [comment]
Sure i will give it a shot right away. Do they come with FreeTDS(configured with OpenSSL) ?
Would this be the correct binary for a 64bit machine ? : pymssql‑2.1.1‑cp34‑none‑win_amd64.whl

**Comment by cgohlke** [comment]
Yes, it's statically linked to freetds-0.91.112 configured with SSL. `cp34‑none‑win_amd64` is for Python 3.4, 64 bit.

**Comment by meet-bhagdev** [comment]
Worked like a charm! Thank you so much. Really appreciate it!

**Comment by ramiro** [comment]
This is great!

Thanks Christoph for your help here and for the woenderful service you do
publishing all these Windows Python packages.

One question: Do you use OpenSSL or GNU TLS? I'd like to fix this for a
future pymssql release.

**Comment by cgohlke** [comment]
I used OpenSSL. These are my notes:

Build OpenSSL and iconv with Visual Studio 2008|2010 using Multi-threaded DLL (/MD) runtime library.
Add the OpenSSL and iconv include directories to the FreeTDS solution projects.
Change the FreeTDS projects to use Multi-threaded DLL (/MD).
Define HAVE_OPENSSL and HAVE_ICONV in config.h.
Add win_mutex.c and sspi.c to the TDS project source files.
Rebuild FreeTDS.
In pymssql setup.py, change libraries to
    ['db-lib', 'tds',
     'ws2_32', 'wsock32', 'kernel32', 'shell32',
     'user32', 'advapi32', 'gdi32', 'crypt32',
     'iconv', 'zlib', 'ssleay32', 'libeay32']
Add the paths to the libraries to INCLUDE and LIB environment variables.
Run python setup.py build ...

**Comment by ramiro** [comment]
> I used OpenSSL. These are my notes:

Thanks Christoph for your help. Got it working on Appveyor, using statically linked OpenSSL for now but the idea is to link against their .DLL's:

https://ci.appveyor.com/project/ramiro/freetds/build/158/job/74mks6jaj2j67swa#L597

Hopefully we'll be able to include FreeTDs binaries built this way with a pymssql release soon.

**Comment by meet-bhagdev** [comment]
Thanks for the update ramiro. And yep that would be super cool if we can include the pre built FreeTDS binaries.
