### ISSUE TITLE
Can not connect to Azure SQL DB using pymmsql on Mac OS

### ISSUE THREAD

**Issue by csucla2015** [pymssql/pymssql#328]
I installed FreeTDS with ssl and am able to connect to my database on SQL Azure using tsql from command line. However if I install pymmsql and try it through pymmsql it keeps giving me the following error :  File "pymssql.pyx", line 381, in pymssql.Cursor.execute (pymssql.c:4684)
pymssql.ProgrammingError: (102, "Incorrect syntax near ......
I validated the same code on pymmsql on linux and windows and it works.
Can someone help me setup pymmsql with FreeTDS on mac os for SQL Azure support?
Really appreciate it

**Comment by rsyring** [comment]
Please use the google group for support requests:

https://groups.google.com/forum/#!forum/pymssql

Thanks.  :)
