### ISSUE TITLE
Problem with float parameter in callproc

### ISSUE THREAD

**Issue by tonymcdaniel** [pymssql/pymssql#329]
I was having trouble calling a stored procedure using callproc() when the procedure expects a SQL float and the value is a Python float. I tracked the problem to the py2db_type function:

    if py_type == 'float':
        if value != 0 and not (-3.40E38 <= value <= -1.18E-38 or 1.18E-38 <= value <= 3.40E38):
            return _mssql.SQLFLT8
        else:
            return _mssql.SQLFLT4

which was added [here](https://github.com/pymssql/pymssql/pull/304). The value I was passing in was 32186.88 which used the SQLFLT4 type which seems to correspond to the SQL real type. 

Unless there's a reason to differentiate between the two floating point types, I would suggest removing the above conditional and adding

    'float': _mssql.SQLFLT8 

to the DBTYPES dict. Downloading the source code and compiling it with this change resolved the issue for me. I was going to submit a pull request, but wasn't sure if there was a reason for the current implementation.

**Comment by bladams** [comment]
I think you are right. It is probably better to consistently use float8 in that case. I can't think of what I was trying to accomplish with that conditional. If you have a patch ready, I'd say go ahead and submit a PR or I could if you prefer.

Thanks,
Bill
