### ISSUE TITLE
Cannot open server "1433D" requested by the login

### ISSUE THREAD

**Issue by jlvcm** [pymssql/pymssql#330]
i'm using `freetds-0.91-12.git0a42888` and MSSQL server from Azure and pymssql=2.1.1

and on `freetds.conf` i've configured my server:
```
[mymssql-beta]
        host = mymssql.database.windows.net
        port = 1433
        tds version = 8.0
        client charset = UTF-8
 ```
and if i try to connect using the `tsql`:
` tsql -S mymssql-beta -U myusername -P mypassword_ -D mydb`
it works just fine, but when i try to connect using pymssql
```python
import pymssql
conn = pymssql.connect("mymssql-beta","myusername","mypassword","mydb")
```
i'm get this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pymssql.pyx", line 637, in pymssql.connect (pymssql.c:9508)
pymssql.OperationalError: (40532, 'Cannot open server "1433D" requested by the login.The login failed.
DB-Lib error message 20018, severity 20:
    General SQL Server error: Check messages from the SQL Server
DB-Lib error message 20002, severity 9:
    Adaptive Server connection failed')
```

**Comment by ezwiefel** [comment]
The username requires the server name as well - so instead of `"myusername"` you need `"myusername@mymssql-beta"`

I was running into the same issue, but found the solution on https://azure.microsoft.com/en-us/documentation/articles/sql-database-develop-python-simple-ubuntu-linux/

**Comment by proftom** [comment]
had the same problem. ezwiefel's answer fixed it.

**Comment by acrain** [comment]
Same here. Thanks @ezwiefel. Should be better documented somewhere...

**Comment by velle** [comment]
I get the same error, however the solution mentioned here (adding "@server") does not work for me. 

Could you please explain me why it says "D". Why "1433D"? Is that short notation for something? And why does it say "Can not open server 1433D". Does it think that 1433/1433D is a hostname?

**Comment by divyashravanthi** [comment]
Using an mssql adapter, you might have to set an explicit option "azure: true" to the connection specifications.

**Comment by rootchina** [comment]
ezwiefel's answer could resolve my similar issue as well. Here's the example code:

`import pymssql`
`conn = pymssql.connect(server='yourserver.database.chinacloudapi.cn', user='yourusername@yourserver', password='yourpassword', database='AdventureWorks')`

**Comment by igotmail9** [comment]
Thank you Mr. ezwiefel, this worked for me

**Comment by shoaib-s** [comment]
Thank you ezwiefel 

The username requires the server name as well worked for me.

**Comment by Ex3v** [comment]
@ezwiefel you rock! 🚀 Thanks

**Comment by xsqian** [comment]
I am getting this error: ```File "pymssql.pyx", line 641, in pymssql.connect (pymssql.c:10824)
pymssql.OperationalError: (40532, b'Cannot open server "1433D" requested by the login.  The login failed.DB-Lib error message 20018, severity 20:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20002, severity 9:\nAdaptive Server connection faile...```

**Comment by xsqian** [comment]
Hi @Ex3v actually @ezwiefel 's solution regarding the username worked. The username has to be in the format of "user@server". Thanks!

**Comment by permanar** [comment]
> The username requires the server name as well - so instead of `"myusername"` you need `"myusername@mymssql-beta"`
> 
> I was running into the same issue, but found the solution on https://azure.microsoft.com/en-us/documentation/articles/sql-database-develop-python-simple-ubuntu-linux/

Omg I feel so pathetic lol. Thanks for saving me with this. Even tho I was actually searching for tiny_tds solution😁

**Comment by omartin2010** [comment]
thanks @ezwiefel ! :) 
So with pymssql==2.1.1, it works in this format : 
```python
conn = pymssql.connect(server='<my-instance>.database.windows.net',
                       port=1433,
                       user='myuser@<myinstance>',   # note  here it's not the FQDN...
                       password='oliLOssbob1234@@..',
                       database='olibob')
```
But it doesn't work on pymssql==2.1.4. I get this error
```text
pymssql.OperationalError: (20002, b'DB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (olibob.database.windows.net:1433)\n')
```
Any clue what might be wrong? Any options I should be specifying? 2.1.4 seems to not require other things (`freetds-dev` and `freetds-bin` packages to be apt installed) so would be nicer.

**Comment by samitshah78** [comment]
I wanted to build the parameters with string and then pass it to connect 
e.g. 
str1 = 'server = ' + servername + ', port = ' + port + ' , user = ' + user + ', password = ' + password + ', database = ' + database 

pymsssql.connect(str1)

but it considers str1 as single parameter and throws error as unknown host name. Any idea, what am I missing over here

**Comment by omartin2010** [comment]
you're missing the fact that there are multiple params you should use for these things independently and not stuff everything in a string. Use the example above `pymsssql.connect(server=servername, port=port, etc.`. That should get you there.
