### ISSUE TITLE
Cursor.executemany is unnecessarily slow

### ISSUE THREAD

**Issue by klothe** [pymssql/pymssql#332]
The Cursor.executemany method is implemented by repeatedly calling Cursor.execute, rather than combining all the parameter lists into one statement (relevant code is here: https://github.com/pymssql/pymssql/blob/master/pymssql.pyx#L480).

For example, instead of

```
INSERT INTO table (x, y) VALUES (1, 2), (3, 4), (5, 6);
```

it produces:

```
INSERT INTO table (x, y) VALUES (1, 2);
INSERT INTO table (x, y) VALUES (3, 4);
INSERT INTO table (x, y) VALUES (5, 6);
```

where each INSERT statement requires a separate round trip between the client and the database server.

This is [allowed by the DBAPI specification](https://www.python.org/dev/peps/pep-0249/#executemany), but it defeats the point of executemany, because its performance no better than having the consumer call execute repeatedly.

This makes pymssql unusable when trying to insert many rows, especially over a slow network connection. Some other DBAPI implementations, such psycopg2, implement executemany by generating a single insert statement, which is fast; pymssql should do the same thing.

**Comment by rsyring** [comment]
Thanks for pointing this out.  If you submit a PR with no tests breakages that makes this change, it would likely be accepted.

There is the possibility that you would hit the SQL server statement length limit doing this:

http://stackoverflow.com/questions/9201354/how-many-characters-long-may-an-sql-server-sql-statement-be

But, IMO, that probably should be handled by the app developers.  If there data is big enough to run into that limitation, then they need to figure out the best way to chunk it.

**Comment by klothe** [comment]
OK, I’ll see what I can do.

The most intuitive way to implement this is to extract the “VALUES” clause from the SQL string, call `self.conn.format_sql_command` with each parameter list, re-assemble the results into another SQL string, and then pass that to execute. Is there any alternative that doesn't involve parsing the SQL?

**Comment by rsyring** [comment]
> The most intuitive way to implement this is to extract the “VALUES” clause from the SQL string,

Parsing usually has odd corner cases.  Maybe see how psycopg did it?  If they parsed, maybe we can use that as a starting point.

**Comment by klothe** [comment]
It's hard to tell exactly what psycopg2's implementation does. I also looked at MySQLdb, which parses the INSERT statement with a regular expression, so maybe that's not so bad: https://github.com/farcepest/MySQLdb1/blob/master/MySQLdb/cursors.py

**Comment by vadoverde** [comment]
Hey all, just wanted to share a solution I developed using XML, hope it helps.
https://gist.github.com/vadoverde/84f4d4a4c31416d2dfee

**Comment by indera** [comment]
this would be  really nice fix!

**Comment by Jan-Ko** [comment]
I'm also struggling with slow executemany performance. Just wanted to share this link https://gadymargalit.wordpress.com/2014/07/19/python-and-mssql-performance/
providing a solution (for pyodbc) turning the input dictionaries to batches of lists of tuples.
I'm not yet sure if it's really different than the solution idea provided above

**Comment by vadoverde** [comment]
@Jan-Ko thanks for sharing this solution by gadymargalit. This solution is encapsulating the table into a text variable and writing it to SQL and text variables have limitations in MSSQL. For instance you notice that the solution has a limit of 1000 records on the table which means if you have a table of 1001+ records the WritetoDB() will result in loss of data. Removing the limit or increasing it will exponentially increase the time this solution will take to become even slower than executemany() depending on the processing power of your machine. 
The solution I provided above uses XML formats in both Python and MSSQL which have no limitation on data format or size. Also the size of the table will not affect performance. You may test writing tables with different number of records (1000 vs 70000 rows) and compare the results in both solution and see what I mean.

**Comment by Jan-Ko** [comment]
@vadoverde 
Maybe I am wrong, but the enlist() function takes the number of records you want to insert and splits them into batches of size at most 1000.
WritetoDB() loops over parameter lists of size at most 1000. So the solutions will work for a table with 1001 records. One batch of size 1000 and one batch of size 1, right? 

My SQL Server admin once told me, that batch size in prepared statements should not be too large and he suggestes batch sizes of around 500 - 10000 (probably depending on your hardware).

**Comment by vadoverde** [comment]
@Jan-Ko you're right I missed the "for data in enlist(r)" loop.
Concerning batch size, I've done a lot of testing on it in the past few years and I couldn't say there is one number that works for best for all situations. Inserting 10,000,000 rows into a fact table of a highly normalized SQL Server database on a 32 core 128 GB memory server with a batch size of 100,000 gave me the best performance while 1,000 took forever. Though if you're working with small data sets then 1,000 might be optimal. Besides server performance, database settings and architecture are equally important such as transaction logging level or whether tables are optimized for inserts or querying. Inserting into a heap will be way more efficient than a clustered index.

Coming to a conclusion, my experience with sending SQL data from Python to the SQL engine as text has not been very positive (performance and precision - accounting for quotes and other special characters) compared to using the python's ET library (XML format). Though I designed my solution is not generalized as I designed it for my specific application and it need to be optimized for your own specific application. The ultimate solution would be modify the pymssql driver to not write the data one row at a time.

**Comment by Jan-Ko** [comment]
I was just checking the pandas Dataframe.to_sql() function and there also a chunksize can be selected. Going through the source code (https://github.com/pydata/pandas/blob/master/pandas/io/sql.py), it looks like the data are simply zipped together to "simulate" array inserts for a fixed chunk size. Check the SQLTable class starting at row 644

Isn't it possible to use a similar procedure in the execute_many function here?
One might add a chunk size option, or simply transform the data into an array and "execute" the array. Then, defining the right chunk_size is the left to the user.

**Comment by MaximilianR** [comment]
>I was just checking the pandas Dataframe.to_sql() function and there also a chunksize can be selected. Going through the source code (https://github.com/pydata/pandas/blob/master/pandas/io/sql.py), it looks like the data are simply zipped together to "simulate" array inserts for a fixed chunk size. Check the SQLTable class starting at row 644

I think pandas passes this to SQLAlchemy, which passes it to the driver with `execute_many` - in this case pymssql...

**Comment by Jan-Ko** [comment]
Yes, it does ...

I think I've just realized a mistake in my thinking. I thought, one could pass "arrays" to the execute function. But if this where the case, this thread would not exist, would it? :) 

The TSQL documentation (https://msdn.microsoft.com/en-us/library/cc296201(v=sql.105).aspx) suggests to perform a prepared statement. Why not do this?

It looks like it is restricted to the ? placeholder, though, if parsing of the sql query shall be avoided.

**Comment by ramiro** [comment]
I was slightly in favor of merging this even when I agree with @rsyring on being wary of solutions involving parsing of SQL.

And then we have issues like e.g. #424

Now I'm not so sure.

**Comment by andreacassioli** [comment]
Hi all,
what is the status of this issue? I am experiencing slow performance with executemany. From the DB trace I see a single insert for each row, as executemany is only looping over the input data.

**Comment by ramiro** [comment]
See this thread on the psycopg mailing list for similar issues and feasability/factors influencing design of a solution: https://www.postgresql.org/message-id/060e2dde-fef6-1c31-bb09-097a13121375%40zzzcomputing.com

**Comment by gary-cowell** [comment]
I'm bumping into this issue writing a program which inserts many rows to SQL Server. I have my rows in a collection and run insertmany,  my measurments show it inserts around 1000 rows a second, which is pretty slow. Looking at network traffic it is indeed doing a round trip per row.

So the question is either, how can I code my python to mitigate this? If it was another language I'd bind in array variables so as to insert many rows in a single network trip,  but I'm unclear if I can do this with pymssql. Or, after a year and a half, is there any sign of progress?

**Comment by saherahwal** [comment]
Is this issue still open? I'm seeing extremely slow performance of executemany and though it batches the inserts. If it's simply looping over execute(), then it defeats the purpose.

**Comment by dherrebout** [comment]
Executemany indeed just creates multiple execute statements. Especially for inserting rows this becomes painfully slow. Pyodbc has a solution called fast_executemany, where it basically creates one INSERT statement and loops over an iterable, such as a list with tuples, and converts those into multiple rows of values in that one insert statement. 

This would be way faster; any plans to implement this into pymssql? I don't really want to switch to pyodbc since it relies on ODBC (obviously), which is yet another layer between the code and database.

**Comment by hhsissi** [comment]
Hi!

Did someone get to address this issue ? I see it exists for 4 years... if you have a custom implementation i'd gladly take it!
