### ISSUE TITLE
Error 20006: Write to Server Failed

### ISSUE THREAD

**Issue by kotowick** [pymssql/pymssql#336]
Anyone else get this error once in a while?

http://pastebin.com/Z5G1JzcU

**Comment by rsyring** [comment]
Yes.  It usually means that the server dropped the connection (was rebooted maybe).  Regardless, it's not an issue with pymssql, the connection to the server just went away for some reason.

**Comment by kotowick** [comment]
Thanks for the response.

I have never experienced this issue in production -- only development. Sometimes, rails server will give that message, but running the same action in rails console will still work. Restarting PG  & rails on OSX sometimes doesn't even help...in that case, I have to reboot. Happens maybe twice a day.
