### ISSUE TITLE
When used in a package compiled with cx_freeze, fails to get all needed packages.

### ISSUE THREAD

**Issue by morganthrapp** [pymssql/pymssql#343]
I've been trying to run `cx_freeze` on a package that includes a `pymssql` import. This fails unless I manually import `_mssql`, `socket`, `decimal`, and `uuid`.

Without those manual imports, as soon as I try to run the compiled .exe created by `cx_freeze`, it fails with an `ImportError` stating that one of the above modules are missing.

**Comment by ramiro** [comment]
pymssql is a python extension written in Cython so the heuristics cx_freeze (and other similar solutions)  uses to detect dependencies might fail. AFAICT this isn't a problem exclusively of pymssql but common to extensions not written in pure Python.

Please report the issue to cx_freeze to see if they can implement such detection in some other way. Not sure it's posssible though.
