### ISSUE TITLE
connect to sql server using domain account from linux box and not using a username password

### ISSUE THREAD

**Issue by rajesh-erasani** [pymssql/pymssql#344]
Is there a way to connect to SQL Server using the domain account from Linux box? Like windows authentication or trusted connection or integrated security when we connect from a windows box is there a similar way to be able to connect from Linux box using pymssql? I don't want to provide a username and password for my connection and want to use the domain account of the user trying to connect to SQL server.

**Comment by rsyring** [comment]
Please use the mailing list for questions: https://groups.google.com/forum/#!forum/pymssql

Short answer: you are looking for Kerberos auth.  Google "FreeTDS Kerberos" and "pymssql Kerberos."  FreeTDS is the C library that pymssql depends on.
