### ISSUE TITLE
Wheels for Python 3.5

### ISSUE THREAD

**Issue by The-Compiler** [pymssql/pymssql#345]
https://pypi.python.org/pypi/pymssql/2.1.1 doesn't seem to have wheels (or binary installers) for Python 3.5 - having those would be very useful!

**Comment by fudomunro** [comment]
I'm using the ones here: http://www.lfd.uci.edu/~gohlke/pythonlibs/#pymssql

(But I agree it would be nice to get them in PyPI)

**Comment by ramiro** [comment]
Related:

https://github.com/pymssql/pymssql/commit/c1ae24bf73dcd1f5d42bb9d2635d7940d3c91b8e (already merged)

See https://ci.appveyor.com/project/ramiro/pymssql (that URL should be https://ci.appveyor.com/project/pymssql/pymssql at some point once we get to the pymssql GitHub organization to have its own AppVeyor account)

Binaries (wheels and .exe installers) for all current Python versions and win32/win64 are created with every commit to our Git repository and are available as artifacts of these builds, e.g. https://ci.appveyor.com/project/ramiro/pymssql/build/job/qy9pahbvyh67k2no/artifacts

Testing of such binaries is welcome. Here's a guide:

Note these binaries link in matching FreeTDS in DLL form, the ones used are from https://github.com/ramiro/freetds/releases

These FreeTDS binaries in its own turn link in OpenSSL in DLL form, the ones used are from http://www.npcglib.org/~stathis/blog/precompiled-openssl/

Download the DLL's that match your Python version and architecture and put them in the same directory as the pymssql extension files or in a directory listed inthe PATH env var.

**Comment by The-Compiler** [comment]
@ramiro Thanks, that's a beautiful AppVeyor setup! :+1:

I rarely use Windows and filed this on behalf of someone in the `#python` IRC channel - so I'm afraid I can't test them easily.

**Comment by ramiro** [comment]
I assume this issue was about binary wheels for the WIndows platform as that's the only one where they are possible.

This means this has been fixed with the release of v2.1.2
