### ISSUE TITLE
Chinese unreadable code

### ISSUE THREAD

**Issue by JayForest** [pymssql/pymssql#355]
Hi， I just  start to learn the pymssql ,use it to connect SQL server2014.And I use the Anaconda3.4 ,which includes the  ipython 3.4, pymssql2.1.1,  but the  Chinese are all unreadable code, my python code is 

# -*- coding: utf-8 -*-
"""
Created on Tue Nov 17 16:05:37 2015

@author: Jay
"""

import pymssql   
     
conn = pymssql.connect(server="192.168.201.6",user="sa",password="pwd",database="weibodb",charset = 'utf8')
#sql = "SELECT TOP 100 ID,价格,评价内容 FROM weibo"
sql = "SELECT TOP 100 ID,价格,评价内容 FROM weibo".encode("utf8")
cur = conn.cursor()
cur.execute(sql)
resList = cur.fetchall()
conn.commit()
conn.close()

print(resList)

but my results is unreadable code ,such as 
  " [('Ð¡Ã×£¨MI£©', '£¤549.00'), ('Ð¡Ã×£¨MI£©', '£¤549.00'), ('ÈýÐÇ£¨SAMSUNG£©', '£¤5888.00'), ('÷È×å£¨MEIZU£©', '£¤899.00'), ('»ªÎª£¨HUAWEI£©', '£¤799.00'), ('÷È×å£¨MEIZU£©', '£¤799.00'), ('»ªÎª£¨HUAWEI£©', '£¤1099.00'), ('Ð¡Ã×£¨MI£©', '£¤699.00'), ('÷È×å£¨MEIZU£©', '£¤768.00'), ('Ð¡Ã×£¨MI£©', '£¤699.00'), ('ÈýÐÇ£¨SAMSUNG£©', '£¤1349.00'), ('Ð¡Ã×£¨MI£©', '£¤1799.00'), ('Ð¡Ã×£¨MI£©', '£¤699.00'), ('»ªÎª£¨HUAWEI£©', '£¤1588.00'), ('ÖÐÐË£¨ZTE£©', '£¤238.00'), ('»ªÎª£¨HUAWEI£©', '£¤799.00'), ('ÖÐÐË£¨ZTE£©', '£¤238.00'), ('»ªÎª£¨HUAWEI£©', '£¤999.00'), ('Ð¡Ã×£¨MI£©', '£¤699.00'), ('»ªÎª£¨HUAWEI£©', '£¤3388.00'), ('ÈýÐÇ£¨SAMSUNG£©', '£¤1398.00'), ('ÈýÐÇ£¨SAMSUNG£©', '£¤1398.00'), ('ÖÐÐË£¨ZTE£©', '£¤238.00'), ('Ð¡Ã×£¨MI£©', '£¤1299.00'), ('ÁªÏë', '£¤598.00'), ('»ªÎª£¨HUAWEI£©', '£¤999.00'), ('»ªÎª£¨HUAWEI£©', '£¤1899.00'), ('»ªÎª£¨HUAWEI£©', '£¤1999.00'), ('ÈýÐÇ£¨SAMSUNG£©', '£¤1199.00'), ('»ªÎª£¨HUAWEI£©', '£¤1899.00'), ('»ªÎª£¨HUAWEI£©', '£¤699.00'), ('»ªÎª£¨HUAWEI£©', '£¤2299.00'), ('»ªÎª£¨HUAWEI£©', '£¤1899.00'), ('»ªÎª£¨HUAWEI£©', '£¤2499.00'), ('»ªÎª£¨HUAWEI£©', '£¤599.00'), ('Ð¡Ã×£¨MI£©', '£¤599.00'), ('ÖÐÐË£¨ZTE£©', '£¤238.00'), ('÷È×å£¨MEIZU£©', '£¤799.00'), ('vivo', '£¤1798.00'), ('÷È×å£¨MEIZU£©', '£¤599.00'), ('÷È×å£¨MEIZU£©', '£¤1599.00'), ('Ð¡Ã×£¨MI£©', '£¤699.00'), ('ÖÐÐË£¨ZTE£©', '£¤238.00'), ('vivo', '£¤1798.00'), ('ÈýÐÇ£¨SAMSUNG£©', '£¤1228.00'), ('»ªÎª£¨HUAWEI£©', '£¤799.00'), ('»ªÎª£¨HUAWEI£©', '£¤799.00'), ('ÈýÐÇ£¨SAMSUNG£©', '£¤2899.00'), ('¿áÅÉ£¨Coolpad£©', '£¤778.00'), ('ÖÐÐË£¨ZTE£©', '£¤238.00'), ('Å¬±ÈÑÇ£¨nubia£©', '£¤1299.00'), ('»ªÎª£¨HUAWEI£©', '£¤799.00'), ('Ð¡Ã×£¨MI£©', '£¤1799.00'), ('ÁªÏë', '£¤599.00'), ('»ªÎª£¨HUAWEI£©', '£¤1499.00'), ('ÁªÏë', '£¤499.00'), ('÷È×å£¨MEIZU£©', '£¤1599.00'), ('»ªÎª£¨HUAWEI£©', '£¤1899.00'), ('Ð¡Ã×£¨MI£©', '£¤799.00'), ('÷È×å£¨MEIZU£©', '£¤599.00'), ('»ªÎª£¨HUAWEI£©', '£¤2499.00'), ('ÈýÐÇ£¨SAMSUNG£©', '£¤5888.00'), ('Ð¡Ã×£¨MI£©', '£¤549.00'), ('»ªÎª£¨HUAWEI£©', '£¤1999.00'), ('Ð¡Ã×£¨MI£©', '£¤699.00'), ('»ªÎª£¨HUAWEI£©', '£¤1499.00'), ('ÈýÐÇ£¨SAMSUNG£©', '£¤1398.00'), ('»ªÎª£¨HUAWEI£©', '£¤1799.00'), ('»ªÎª£¨HUAWEI£©', '£¤1799.00'), ('Ð¡Ã×£¨MI£©', '£¤1799.00'), ('»ªÎª£¨HUAWEI£©', '£¤1588.00'), ('»ªÎª£¨HUAWEI£©', '£¤1799.00'), ('Ð¡Ã×£¨MI£©', '£¤1799.00'), ('ÖÐÐË£¨ZTE£©', '£¤238.00'), ('÷È×å£¨MEIZU£©', '£¤899.00'), ('ÖÐÐË£¨ZTE£©', '£¤238.00'), ('ÈýÐÇ£¨SAMSUNG£©', '£¤2899.00'), ('Å¬±ÈÑÇ£¨nubia£©', '£¤1388.00'), ('»ªÎª£¨HUAWEI£©', '£¤1499.00'), ('»ªÎª£¨HUAWEI£©', '£¤1899.00'), ('Ð¡Ã×£¨MI£©', '£¤699.00'), ('ÈýÐÇ£¨SAMSUNG£©', '£¤2569.00'), ('ÖÐÐË£¨ZTE£©', '£¤238.00'), ('÷È×å£¨MEIZU£©', '£¤768.00'), ('÷È×å£¨MEIZU£©', '£¤799.00'), ('Ð¡Ã×£¨MI£©', '£¤549.00'), ('Ð¡Ã×£¨MI£©', '£¤799.00'), ('÷È×å£¨MEIZU£©', '£¤1799.00'), ('»ªÎª£¨HUAWEI£©', '£¤599.00'), ('vivo', '£¤2598.00'), ('LG', '£¤2999.00'), ('÷È×å£¨MEIZU£©', '£¤799.00'), ('ÁªÏë', '£¤349.00'), ('Ð¡Ã×£¨MI£©', '£¤849.00'), ('»ªÎª£¨HUAWEI£©', '£¤2499.00'), ('ÁªÏë', '£¤1999.00'), ('÷È×å£¨MEIZU£©', '£¤1999.00'), ('÷È×å£¨MEIZU£©', '£¤668.00'), ('÷È×å£¨MEIZU£©', '£¤1099.00'), ('÷È×å£¨MEIZU£©', '£¤999.00')]"

**Comment by Russell-Jones** [comment]
Cribbing from https://timscyclingblog.wordpress.com/2012/01/12/sql-server-convert-a-string-into-a-hex-string-and-back-sql-sqlserver/ ... Could you run
SELECT TOP 10 'ID',
MASTER.dbo.fn_varbintohexstr(CAST('价格' AS VARBINARY)),
MASTER.dbo.fn_varbintohexstr(CAST('评价内容' AS VARBINARY))
FROM weibo
And send the output? It should give three fields per record (it seems odd that the above has only two) and return the contents as hex. That would help with working out how the text is being mangled.

**Comment by JayForest** [comment]
sorry,I check my sql code ,and it should sql = "SELECT TOP 100 品牌，价格  FROM weibo".encode("utf8")，the unreadable code is not hex, I guess the pymssql cannot support the Chinese

**Comment by Russell-Jones** [comment]
@JayForest The statement will convert the binary representation of the strings (which we get by casting to VARBINARY) in the database to hex (using the MS SQL built in function MASTER.dbo.fn_varbintohexstr), so we can see exactly what binary data is in the database, before any charset conversion is done.
```
"SELECT TOP 10 "
"MASTER.dbo.fn_varbintohexstr(CAST(价格 AS VARBINARY)), "
"MASTER.dbo.fn_varbintohexstr(CAST(评价内容 AS VARBINARY)) "
"FROM weibo"
```

**Comment by JayForest** [comment]
@Russell-Jones  ，hi , I go back the SQL Server , run the code:
"SELECT TOP 2 MASTER.dbo.fn_varbintohexstr(CAST(品牌 AS VARBINARY)) AS Brand , MASTER.dbo.fn_varbintohexstr(CAST(价格 AS VARBINARY)) as Price FROM weibo" , then get the hex charset, 
  Brand	                                       Price
0xd0a1c3d7a3a84d49a3a9	0xa3a43534392e3030
0xd0a1c3d7a3a84d49a3a9	0xa3a43534392e3030
,so  Are you let me put the hex charset  to convert other charset which pymssql can identify?
#*****************************************************************************************************************
In fact, I think the unreadable  charset are mainly caused by the charset coded with varchar  in  my SQL Server ,the pymssql can support the unicode ,but the varchar is not unicode .
If the data is small, i can convert the varchar to nvarchar,but the data is too large to change it, 
Do you have any good suggestions?

**Comment by Russell-Jones** [comment]
'Ð¡Ã×£¨MI£©'.encode("cp1252") (basically the byte values) gives the hex values, so that looks like the actual byte sequence, at least for the two record you give. I can't work out what encoding it should be from that alone. Supposing it's the case for the other records (is it?) chardet doesn't make it any clearer:

```
#!/usr/bin/env python3
from chardet import detect
def hex2bytes(_str):
   a = iter(_str)
   return bytes([int(x+next(a),16) for x in a])

print(detect(hex2bytes("d0a1c3d7a3a84d49a3a9")))
print(detect(hex2bytes("a3a43534392e3030")))
```
ะกรืฃจMIฃฉ (TIS-620) looks kind of convincing, but doesn't work on much of the data.
苤譙ㄗMIㄘ (BIG5) also looks plausible, but doesn't work past the third record. If either of these are correct, it could be that the data is using multiple encodings. (This is putting the array above in the variable "a" and using the code below)

```
for x, y in a:
    c=x.encode("cp1252")
    print(c.decode("BIG5"))
```

**Comment by JayForest** [comment]
hi,thank you very much your patience,  I code  in python3 

# -*- coding: utf-8 -*-
"""
Created on Tue Dec  1 09:11:34 2015

@author: Jay
"""

import pymssql

conn = pymssql.connect(server="192.168.201.6",user="sa",password="pwd",database="weibodb",charset = 'utf8')
sql = "SELECT TOP 2 MASTER.dbo.fn_varbintohexstr(CAST(品牌 AS VARBINARY)), MASTER.dbo.fn_varbintohexstr(CAST(价格 AS VARBINARY)) FROM weibo"
cur = conn.cursor()
cur.execute(sql)
resList = cur.fetchall()
conn.commit()
conn.close()

print(resList)

the results return the list :
    "[('0xd0a1c3d7a3a84d49a3a9', '0xa3a43534392e3030'), ('0xd0a1c3d7a3a84d49a3a9', '0xa3a43534392e3030')]"

The results are same as the result coded in the MSSQL,So, the method maybe cannot achieve my goal

**Comment by Russell-Jones** [comment]
Ah yes, you mentioned you use 3 in the OP. You'll need to know the text encoding used in the database records whatever approach you use if you want to display the data.

**Comment by ramiro** [comment]
It's not clear this is an issue in pymssql but rather a GIGO one with OP's DB data.

The right plce for this kind of support questions is the mailing list not an issue here.
