### ISSUE TITLE
AttributeError: 'module' object has no attribute 'connect'

### ISSUE THREAD

**Issue by Diyago** [pymssql/pymssql#356]
I know that such error might appear if I named the file same as importing lib, but there are must be  is something different, because the error persist even if try run that code below through console:

``` python
# -*- coding: cp1251
import _mssql

connSQLserver = _mssql.connect(
                        server="localhost",
                        port=1433,
                        user="admin",
                        password="****",
                        database="master")
```

I'm trying to connect to locally installed sql server 2014,  using pymssql-2.1.1-cp27-none-win_amd64 
.

What may cause the error?

**Comment by rsyring** [comment]
I'm sure this isn't a bug or pymssql problem, please try the mailing list: https://groups.google.com/forum/#!forum/pymssql

You should make sure the file is not named _mssql.py AND that there isn't a _mssql.pyc file either.

You could also `print _mssql` or `print _mssql.__file__` to see what module you are actually dealing with.
