### ISSUE TITLE
Unable to install on Windows with Python 3.5.1

### ISSUE THREAD

**Issue by johnpaul2** [pymssql/pymssql#364]
When I try to installl pymssql on windows I get the following error:
"Python Version 3.5 required, which was not found in the registry"

I use the installer from the latest build for python 3.5 found here: 
https://ci.appveyor.com/project/ramiro/pymssql/build/job/u096jx1yp0y77sns/artifacts

My environment:
* Win8 64 bit
* Python 3.5.1 32bit
* Visual Studion 2015

**Comment by rsyring** [comment]
Do other Python 3.5 exe's install ok for you?  i.e. is this a pymssql problem or a problem with your system?

You could try installing python for windows with their 3.5 exe: http://sourceforge.net/projects/pywin32/files/pywin32/Build%20219/

**Comment by johnpaul2** [comment]
I had the same error when installing another exe. I found a workaround here:
http://sourceforge.net/p/pywin32/bugs/702/#c6f1

After copying the registry keys as described the installation if pymssql worked. 
As I can not decide if this is a bug in the python 3.5 or the pymssql installer, I leave it up to you to close this issue.

**Comment by rsyring** [comment]
Not a pymssql issue then.  Closing.  :)

**Comment by johnpaul2** [comment]
Sorry, me again. When I try to import pymssql I get the following error:
"ImportError was unhandled by user code
Message: DLL load failed: Das angegebene Modul wurde nicht gefunden."

**Comment by ramiro** [comment]
@johnpaul2 

Make sre you have the FreeTDS and OpenSSL DLLs available. See https://groups.google.com/d/msg/pymssql/bfe0yxWl7Fc/UF9WjG4TAwAJ

**Comment by rsyring** [comment]
Also, please take future questions that aren't really bugs or features to the mailing list: https://groups.google.com/forum/#!forum/pymssql

Thanks.  :)
