### ISSUE TITLE
Despite using freetds 0.95 I still get DB-Lib error message 20002

### ISSUE THREAD

**Issue by ttucker137** [pymssql/pymssql#371]
Hello, I have read previous posts in reference to this issue and understand that the username length is often the issue. However, because `@server.database.windows.net` is included in the username, not going over 30 chars is difficult. I have compiled and built FreeTDS v 0.95 which one post said anything post 0.91 should fix [and allow up to 128], but I still face the same issue. Please see code snippet and config below:

----------------FreeTDS Config---------------------------
[root@qa-server prod-approvals]# tsql -C
Compile-time settings (established with the "configure" script)
                            Version: freetds v0.95.79
             freetds.conf directory: /usr/local/etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: no
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 5.0
                              iODBC: no
                           unixodbc: no
              SSPI "trusted" logins: no
                           Kerberos: no
                            OpenSSL: no
                             GnuTLS: no
---------------Code---------------------------------
import pymssql
    def get_connection(self):
        db_pass = os.environ['db_pass']
        db_server = 'server.database.windows.net'
        db_user = 'username@' + db_server
        db_name = 'powerstone'
        connection = pymssql.connect(db_server, db_user, db_pass, db_name)
        return connection

connection = get_connection()
print str(connection)

**Comment by ramiro** [comment]
IIRC you need to use TLS/SSL to connect to Azure.

**Comment by ttucker137** [comment]
I have opened a ticket with MSFT as well to troubleshoot this, their link does not make any mention of TLS/SSL. https://azure.microsoft.com/en-us/documentation/articles/sql-database-develop-python-simple-ubuntu-linux/

**Comment by ramiro** [comment]
That article isn't  supposed to mention it at all.

The FreTDS binaries used (in the case of the Microsoft article the Debian/Ubuntu/etc. Linux distribution .deb packages) shipped with are the ones that should have been built with the SSL/TLS feature activated:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

$ sudo apt-get install freetds-dev freetds-bin

$ dpkg -l | grep freetds
ii  freetds-bin                                           0.91-5                                              amd64        FreeTDS command-line utilities
ii  freetds-common                                        0.91-5                                              all          configuration files for FreeTDS SQL client libraries
ii  freetds-dev                                           0.91-5                                              amd64        MS SQL and Sybase client library (static libs and headers)

$ ldd /usr/lib/x86_64-linux-gnu/libsybdb.so.5.0.0 
	linux-vdso.so.1 =>  (0x00007ffd01ed0000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007efc8f087000)
	libgcrypt.so.11 => /lib/x86_64-linux-gnu/libgcrypt.so.11 (0x00007efc8ee07000)
	libgnutls.so.26 => /usr/lib/x86_64-linux-gnu/libgnutls.so.26 (0x00007efc8eb48000) <------
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007efc8e92a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007efc8e565000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007efc8e299000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007efc8e06a000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007efc8de66000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007efc8dc5a000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007efc8da55000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007efc8d83c000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007efc8d627000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007efc8d3e5000)
	/lib64/ld-linux-x86-64.so.2 (0x000055a1c54d8000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007efc8d1e1000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007efc8cfc5000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007efc8cdc1000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007efc8cbb8000)
```

In your case, if you are building your own FreeTDS you need to take care of that yourself by following the FreeTDS docs

I'm closing this issue. Please post this kind of user support question to our mailing list.
