### ISSUE TITLE
failed to build: Cannot open include file: 'sqlfront.h': No such file or directory

### ISSUE THREAD

**Issue by YoungjaeKim** [pymssql/pymssql#372]
```pip install pymssql``` in Windows 10 64bit with Python 3.5 64bit has error.
Any workaround to address this issue?

The error log is as beow.

--

Collecting pymssql
  Using cached pymssql-2.1.1.tar.gz
Installing collected packages: pymssql
  Running setup.py install for pymssql
    Complete output from command C:\Python35\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\Youngjae\\AppData\\Local\\Temp\\pycharm-packaging0.tmp\\pymssql\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\Youngjae\AppData\Local\Temp\pip-uhyoaql7-record\install-record.txt --single-version-externally-managed --compile:
    setup.py: platform.system() => 'Windows'
    setup.py: platform.architecture() => ('64bit', 'WindowsPE')
    running install
    running build
    running build_ext
    building '_mssql' extension
    creating build
    creating build\temp.win-amd64-3.5
    creating build\temp.win-amd64-3.5\Release
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Youngjae\AppData\Local\Temp\pycharm-packaging0.tmp\pymssql\freetds\vs2010_64\include -IC:\Python35\include -IC:\Python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\winrt" /Tc_mssql.c /Fobuild\temp.win-amd64-3.5\Release\_mssql.obj -DMSDBLIB
    _mssql.c
    _mssql.c(314): fatal error C1083: Cannot open include file: 'sqlfront.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\cl.exe' failed with exit status 2
    
    ----------------------------------------

Command "C:\Python35\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\Youngjae\\AppData\\Local\\Temp\\pycharm-packaging0.tmp\\pymssql\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\Youngjae\AppData\Local\Temp\pip-uhyoaql7-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Youngjae\AppData\Local\Temp\pycharm-packaging0.tmp\pymssql

**Comment by ramiro** [comment]
Pleae pist your question to the mailing list instead of opening an issue here, ebcause this isn't a user pupport channel.

PS: Please read the documentation http://pymssql.org/en/stable/building_and_developing.html#windows

**Comment by etripathy** [comment]
Even I encountered the same 
_mssql.c(314): fatal error C1083: Cannot open include file: 'sqlfront.h': No such file or directory
error: command 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe' failed with exit status 2 
While trying to install pymssql for win7 64 bit system. Any help here is really appreciated . 
YoungjaeKim Does that issue got resolved for you

**Comment by nyxcalamity** [comment]
Consider reopening this issue, since it happens on 'pip install pymssql'. Does seem like a user support issue.

**Comment by efficks** [comment]
@ramiro Same problem installing through pip with Windows 7 x64

**Comment by dkalaria** [comment]
On Mac

brew install freetds@0.91
brew link --force freetds@0.91
pip install pymssql

**Comment by Ooooooog** [comment]
_mssql.c:314:22: fatal error: sqlfront.h: No such file or directory
Also happens when i do 'pip install pymssql' 

CentOS 7.2.1511, python 2.7.5

**Comment by pepeld** [comment]
didn't work for me...
I downloaded the python wheels for python version 3.6 from this site: https://www.lfd.uci.edu/~gohlke/pythonlibs/
that worked!

**Comment by man40** [comment]
> ## Solution for Windows and Python 3.6
> ### Python 3.6 32-bit
> Download package **[freetds-v0.95.95-win-x86-vs2015.zip](https://github.com/ramiro/freetds/releases/download/v0.95.95/freetds-v0.95.95-win-x86-vs2015.zip)** from **https://github.com/ramiro/freetds/releases**
> 
> Unpack **freetds-v0.95.95-win-x86-vs2015.zip** to **c:\usr**.
> Now you got **c:\usr\freetds-v0.95.95-win-x86-vs2015** folder.
> 
> Next run **cmd.exe** and do the following:
> 
> ```
> set INCLUDE=c:\usr\freetds-v0.95.95-win-x86-vs2015\include;%INCLUDE%
> set LIB=c:\usr\freetds-v0.95.95-win-x86-vs2015\lib-nossl;c:\usr\freetds-v0.95.95-win-x86-vs2015\lib-nossl\static;%LIB%
> 
> pip install pymssql
> ```
> 
> This works for me on Windows 10 x64, Python 3.6 32-bit and Visual Studio 2017
> 
> ### Python 3.6 64-bit (Not tested)
> Download package **[freetds-v0.95.95-win-x86_64-vs2015.zip](https://github.com/ramiro/freetds/releases/download/v0.95.95/freetds-v0.95.95-win-x86_64-vs2015.zip)** from **https://github.com/ramiro/freetds/releases**
> 
> Unpack **freetds-v0.95.95-win-x86_64-vs2015.zip** to **c:\usr**.
> Now you got **c:\usr\freetds-v0.95.95-win-x86_64-vs2015** folder.
> 
> Next run **cmd.exe** and do the following:
> 
> ```
> set INCLUDE=c:\usr\freetds-v0.95.95-win-x86_64-vs2015\include;%INCLUDE%
> set LIB=c:\usr\freetds-v0.95.95-win-x86_64-vs2015\lib-nossl;c:\usr\freetds-v0.95.95-win-x86_64-vs2015\lib-nossl\static;%LIB%
> 
> pip install pymssql
> ```

the 64 bit worked as well. I used it to install ctds

**Comment by llazzaro** [comment]
For ubuntu install `freetds-dev`

```
apt install freetds-dev
```

**Comment by grokkerzz** [comment]
> For ubuntu install `freetds-dev`
> 
> ```
> apt install freetds-dev
> ```

Thank you very much, it works for my case.

**Comment by benlloyd50** [comment]
> ### Python 3.6 64-bit (Not tested)
> 
> Download package **[freetds-v0.95.95-win-x86_64-vs2015.zip](https://github.com/ramiro/freetds/releases/download/v0.95.95/freetds-v0.95.95-win-x86_64-vs2015.zip)** from **https://github.com/ramiro/freetds/releases**
> 
> Unpack **freetds-v0.95.95-win-x86_64-vs2015.zip** to **c:\usr**. Now you got **c:\usr\freetds-v0.95.95-win-x86_64-vs2015** folder.
> 
> Next run **cmd.exe** and do the following:
> 
> ```
> set INCLUDE=c:\usr\freetds-v0.95.95-win-x86_64-vs2015\include;%INCLUDE%
> set LIB=c:\usr\freetds-v0.95.95-win-x86_64-vs2015\lib-nossl;c:\usr\freetds-v0.95.95-win-x86_64-vs2015\lib-nossl\static;%LIB%
> 
> pip install pymssql
> ```

Trying this out again in 2023 on Windows 10, Python 3.10 and still getting the same missing sqlfront.h file
