### ISSUE TITLE
Fails to load DLL when importing pymssql on Win7

### ISSUE THREAD

**Issue by jontyq** [pymssql/pymssql#390]
`import pymssql`
fails in version 2.1.2 with:
`    import pymssql
ImportError: DLL load failed: The specified module could not be found.`

This was working fine in 2.1.1

**System OS**:  Win7 64bit
**Python**: Python 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)] on win32

**Pip Freeze**:
backports.ssl-match-hostname==3.4.0.2
certifi==2015.4.28
Flask==0.10.1
functools32==3.2.3.post1
ipython==3.2.0
itsdangerous==0.24
Jinja2==2.7.3
jsonschema==2.5.1
MarkupSafe==0.23
matplotlib==1.4.3
mistune==0.6
numpy==1.9.2
pandas==0.17.0
ptyprocess==0.5
py==1.4.30
pycmd==1.2
Pygments==2.0.2
PyInstaller==3.0
pymssql==2.1.2
pyparsing==2.0.3
pypiwin32==219
pyserial==2.7
python-dateutil==2.4.2
pytz==2015.4
pyusb==1.0.0b2
pywinusb==0.3.6
pyzmq==14.7.0
requests==2.8.1
six==1.9.0
terminado==0.5
tornado==4.2
virtualenv==13.1.0
Werkzeug==0.10.4
wheel==0.24

**Comment by ramiro** [comment]
Read The Fine Documentation: http://pymssql.org/en/latest/freetds.html#windows

**Comment by jontyq** [comment]
Ramiro: Please, make the change more obvious!

1. I went from a working system to a non-working system by upgrading; how is that *patch* version increment?  No-one should expect their system to break by moving from 2.1.1 to 2.1.2.
2. When it broke, I did read your change log; No mention of the above breaking change!

I'm tipping this will frustrate a lot of other windows users.

**Comment by jontyq** [comment]
Thanks for your hard work on making such an awesome library.

Sorry for sounding like a whiny got it for free and still not happy user.

**Comment by ramiro** [comment]
Thank you for posting your feedback because it is very valuable.


In restrospect I see now we should have included a changelog entry about
this change in the official Windows binaries. This is my fault.

On Wed, Feb 10, 2016 at 11:51 PM, jontyq <notifications@github.com> wrote:

> Thanks for your hard work on making such an awesome library.
>
> Sorry for sounding like a whiny got it for free and still not happy user.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pymssql/pymssql/issues/390#issuecomment-182678807>.
>



-- 
Ramiro Morales
@ramiromorales

**Comment by jontyq** [comment]
The main changelog should feature the change:

http://pymssql.org/en/latest/changelog.html

**Comment by ramiro** [comment]
ref #392
