### ISSUE TITLE
pymssql ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by InbarRose** [pymssql/pymssql#396]
What am I doing wrong? I used pip to install the package, and importing the package results in an error. What am I missing?

```
C:\Users\Administrator>pip show pymssql
---
Metadata-Version: 2.0
Name: pymssql
Version: 2.1.2
Summary: DB-API interface to Microsoft SQL Server for Python. (new Cython-based version)
Home-page: http://pymssql.org
Author: pymssql development team
Author-email: pymssql@googlegroups.com
License: LGPL
Location: c:\python27\lib\site-packages
Requires:
```
```
C:\Users\Administrator>python
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymssql
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified module could not be found.
```

Note: The same thing happens on a computer that already had a version of pymssql installed that worked:

```
C:\Users\inbar>pip show pymssql
---
Metadata-Version: 2.0
Name: pymssql
Version: 2.1.1
Summary: DB-API interface to Microsoft SQL Server for Python. (new Cython-based version)
Home-page: http://pymssql.org
Author: pymssql Google Group
Author-email: pymssql@googlegroups.com
License: LGPL
Location: c:\python27\lib\site-packages
Requires:
```

```
C:\Users\inbar>python
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymssql
>>> exit()
```
Notice how the import was successful with no errors.

Then I upgrade the package to the newest version.
```
C:\Users\inbar>pip install --upgrade pymssql
Collecting pymssql
  Downloading pymssql-2.1.2-cp27-cp27m-win32.whl (134kB)
    100% |################################| 135kB 1.5MB/s
Installing collected packages: pymssql
  Found existing installation: pymssql 2.1.1
    Uninstalling pymssql-2.1.1:
      Successfully uninstalled pymssql-2.1.1
Successfully installed pymssql-2.1.2
```

And now it won't work anymore.
```
C:\Users\inbar>python
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymssql
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by InbarRose** [comment]
So, I found that as of the new version there is documentation that says I need some dlls. That is fine, but why isn't there a message about it instead of this error? Why isn't there a notification when I update the package? 

Also, The documentation is not clear, After downloading the freetds and opensll packages for my Python version, do I include their their parent dir path or just the path to the dlls? Could there perhaps be an example somewhere? Maybe a script that can be run that will fetch and update/maintain these packages as part of the installation/update process? (shouldn't be that hard)

**Comment by ramiro** [comment]
> So, I found that as of the new version there is documentation that says I need some dlls. That is fine,

Yes, that's a change I've performed in how Windows binaries for the 2.1.2 release are built/shipped. As you've probably already discovered rationale is explained in http://pymssql.org/en/v2.1.2/freetds.html#windows

> but why isn't there a message about it instead of this error? Why isn't there a notification when I update the package?

I dont think pip and the rest of the Python management tools provide a standard way to show a warning text during the installation process. Users are still required to read the documentation beforehand.

Note: The `Changelog*` files shipped initially with the 2.1.2 sdist tarball didn't include a prominent warning. After a similar report to this one (#390) I added it to:

* The package entry at PyPI (https://pypi.python.org/pypi/pymssql/2.1.2): https://pypi.python.org/pypi/pymssql/2.1.2#recent-changes
* To the Changelog page (http://pymssql.org/en/latest/changelog.html) for the default docset published at http://pymssql.org/

> 
> Also, The documentation is not clear, After downloading the freetds and opensll packages for my Python version, do I include their their parent dir path or just the path to the dlls?

This is standard PATH enviroment variable behavior/manioulation (which even is the same for Unix/Linux/platforms): It needs to point to the dir(s) where the files (in this case DLLs) are located. Nut documentation can always be enhanced, see below.

> Could there perhaps be an example somewhere? Maybe a script that can be run that will fetch and update/maintain these packages as part of the installation/update process? (shouldn't be that hard)

Patches/PRs are always welcome.

**Comment by cgohlke** [comment]
Consider using the statically linked [unofficial binaries](http://www.lfd.uci.edu/~gohlke/pythonlibs/#pymssql).

**Comment by rsyring** [comment]
See #399 and #400 for further discussion.  Going to close this issue for now.
