### ISSUE TITLE
pymssql 2.1.3 needed w/ static FreeTDS library

### ISSUE THREAD

**Issue by rsyring** [pymssql/pymssql#400]
Releasing 2.1.2 without static FreeTDS on Windows presents a big BC break and violates semver principles.  I'd like us to ship 2.1.3 as soon as possible with FreeTDS built on Windows as a static library.

I've opened #399 to discuss how we move forward in the long run, but I think a quick fix is needed in this case.

**Comment by ramiro** [comment]
Please see https://github.com/pymssql/pymssql/issues/399#issuecomment-186219556

**Comment by pupssman** [comment]
As a long-term pymssql user on Windows I do support this idea!
DLLs are a bit of pain.

**Comment by morganthrapp** [comment]
I'm definitely in support of this! I just ran into this issue with a new machine.

**Comment by ramiro** [comment]
Implemented this suggestion. See https://pypi.python.org/pypi/pymssql/2.1.3
