### ISSUE TITLE
Please handle the default username more cleanly..

### ISSUE THREAD

**Issue by jvrobert** [pymssql/pymssql#402]
I had to wrestle a bit to figure out that I had to use (..,user="") to trigger Kerberos authentication. If I leave the user=parameter off it defaults to 'sa' which I don't think is a useful thing to do.

IMO semantics that make sense would be the default of None, and if it's None pass in null to freetds or whatever triggers integrated auth.  Or just change default to "" and leave as-is.

**Comment by ramiro** [comment]
Thanks for the report.
 
Now (pre-2.2) is a good time to introduce this kind of backard-incompatible changes that fixes dubiuos default values. See e.g. 2eb3ba9b2518616f899f13a01b14b4c56d20cf0c and PR #404.

I'm accepting the issue and plan to work on it.

Related to this: Would you be interested in helping us to document how to set up thinkg to implement Kerberos authentication? It's a scenario I've alyways wanted to have documented (e.g. in which platform are you workig, which addition dependencies are needed if any, isf is there any special  FreeTDS compile flags neede, etc.)

**Comment by mattkatz** [comment]
I'm willing to help - had to help a dev figure out that SA was being passed if user="" wasn't put in there.

**Comment by ramiro** [comment]
> I'm willing to help - had to help a dev figure out that SA was being passed if user="" wasn't put in there.

If you can, please test our master branch because we've merged in changes on this front.

**Comment by ramiro** [comment]
See also #446.
