### ISSUE TITLE
What's going on with this error?

### ISSUE THREAD

**Issue by crazy-canux** [pymssql/pymssql#411]
xecute sql error: (20003, 'DB-Lib error message 20003, severity 6:
Adaptive Server connection timed out
')

**Comment by rsyring** [comment]
@crazy-canux this is not a pymssql bug.  Please hit our mailing list if you still need help: https://groups.google.com/forum/#!forum/pymssql

**Comment by crazy-canux** [comment]
This is because the query excute time out.
