### ISSUE TITLE
pymssql cannot connect to database when password has a unicode characters

### ISSUE THREAD

**Issue by Draqun** [pymssql/pymssql#413]
Hi.

I have some problem. When I try using password with unicode characters SQL i got this error

Error: (20017, 'DB-Lib error message 20017, severity 9:\\nUnexpected EOF from the server\\nDB-Lib error message 20002, severity 9:\\nAdaptive Server connection failed\\n')

In SQL logs exists message

Logon,Unknown,Login failed for user 'data_sync_agent'. Reason: Password did not match that for the login provided.

Someone can help me with that?

In my case password was created with chars "§".

Any help will be appreciated.

Best regards

**Comment by rsyring** [comment]
Please take this request for help to the mailing list: https://groups.google.com/forum/#!forum/pymssql

If, after further troubleshooting, this turns out to be a bug in pymssql, then you are welcome to open an issue.  

Thanks.
