### ISSUE TITLE
How to fix this in the SQL query or SP?

### ISSUE THREAD

**Issue by crazy-canux** [pymssql/pymssql#414]
(7391, 'The operation could not be performed because OLE DB provider "SQLNCLI10" for linked server "euedcapp0049.edc.eu.corp" was unable to begin a distributed transaction.DB-Lib error message 7391, severity 16:
General SQL Server error: Check messages from the SQL Server')

**Comment by rsyring** [comment]
@crazy-canux this is not a pymssql bug. Please hit our mailing list if you still need help: https://groups.google.com/forum/#!forum/pymssql
