### ISSUE TITLE
How to fix this issue?

### ISSUE THREAD

**Issue by crazy-canux** [pymssql/pymssql#415]
(7202, "Could not find server 'euedcapp0049.edc.eu.corp' in sys.servers. Verify that the correct server name was specified. If necessary, execute the stored procedure sp_addlinkedserver to add the server to sys.servers.DB-Lib error message 7202, severity 11:General SQL Server error: Check messages from the SQL Server")

**Comment by rsyring** [comment]
@crazy-canux this is not a pymssql bug. Please hit our mailing list if you still need help: https://groups.google.com/forum/#!forum/pymssql
