### ISSUE TITLE
getting "ImportError: DLL load failed" using pymssql

### ISSUE THREAD

**Issue by drofaern** [pymssql/pymssql#416]
hi all,

I just tried to play python and I need to use pymssql to connect the db. However, after this module is installed, I kept getting this error:
ImportError: DLL load failed using pymssql: specific module cannot be found.

My env is Win 10, VS 2015 and SQL server 2014, python version is 3.5.1, pymssql is 2.1.2

hope I don't need to downgrade my env. 

Really appreciate if I can get some help here. thx.

**Comment by rsyring** [comment]
This is a dup.  Please see #399 and #400.

**Comment by drofaern** [comment]
WOW! I didn't expect such a quick response! Thank you very much!
