### ISSUE TITLE
Question about the executemany function

### ISSUE THREAD

**Issue by zhanghan987** [pymssql/pymssql#418]
Hi：
    I have tested the executemany fucntion, it is a so slow.
    Then I checked the source code and found it is implemented by 'for' and 'execute'. 
    My question is does pymssql has faster function to execute batch values ?

**Comment by rsyring** [comment]
Please don't use the github issues for questions.  Ask on the mailing list: https://groups.google.com/forum/#!forum/pymssql

Furthermore, there is already an issue addressing this: https://github.com/pymssql/pymssql/issues/332
