### ISSUE TITLE
Attempt to initiate a new Adaptive Server operation with results pending

### ISSUE THREAD

**Issue by poblabs** [pymssql/pymssql#419]
I have a Python script that has a socket open. 10 servers connect to the socket and dump data to the script. The servers do not disconnect and the data is constantly coming in. Sometimes rapidly, sometimes not. The script on-the-fly converts the data dump to columns and submits to SQL Server. I have autocommit enabled.

Every so often I'll get this error. About 5-10 times a day.  

```
20019
DB-Lib error message 20019, severity 7:
Attempt to initiate a new Adaptive Server operation with results pending
```

My script is very straight forward. After doing substring matching to get the columns, it does:

```
try:
    query = "INSERT INTO %s VALUES %s" % (mssql_table, mssql_output)
    cursor.execute( query )
    #dbConn.commit() # Not needed, autocommit is enabled
except pymssql.OperationalError as e:
    logmsg("pymssql.OperationalError exception caught: %s" % str(e).replace("\n", " ") )
except:
    pass
```

Our DBAs aren't familiar with the error, and they say the SQL server is not busy. 

What does this error mean?

**Comment by poblabs** [comment]
I may have figured this out. In my script I'm using threading. There was 1 SQL connector for all the threads. I've moved that so that each thread has its own connector. So far so good. I'll close this for now and re-open again if I get stuck

**Comment by rsyring** [comment]
Yes, neither connection nor cursors should be shared across threads.
