### ISSUE TITLE
results truncated to roughly 4k

### ISSUE THREAD

**Issue by atlas0fd00m** [pymssql/pymssql#421]
attempting to pull a large set of data (the stored procedures which store the SP in one field) seems to truncate to ~4k.  same limitation is applied to all records.  each SP record field (not the whole row) appears to be limited to 4186 bytes.  

i am using the following config:

[global]
    port = 1433
    tds version = 8.0
    text size = 4294967295

and before submitting my query, i'm setting TEXTSIZE:

        cursor.execute('''SET TEXTSIZE 2147483647; SELECT * FROM thedatabase.information_schema.routines where routine_type = 'PROCEDURE' ''')

am i doing something wrong?  is this a bug?  or a pebkac error?

**Comment by atlas0fd00m** [comment]
this is using pymssql 2.1.1 and freetds 0.91 on windows, installed using the .egg from https://pypi.python.org/pypi/pymssql/2.1.1#downloads

**Comment by rsyring** [comment]
Until you are sure this is a pymssql bug, please use the forums for support requests:

https://groups.google.com/forum/#!forum/pymssql

Thanks.
