### ISSUE TITLE
pymssql installation for Windows is confusing.

### ISSUE THREAD

**Issue by PabitraPati** [pymssql/pymssql#422]
For using pymssdql with Windows, as per the documentation, following are the two pre-requisites :-
- openssl
- FreeTDS

So, the documentation for pymssql installation should cover the detailed installation instruction for the above two per-requisites as well. But in current documentation contains following line only :- 

> Download and uncompress it taking note of the path to the directory which contains the DLL files.

which gives no idea to a new user on installing those pre-requisites and proceed for using pymssql.

As a new user, I can't find out a way for installing the above pre-requisites. There is no source in web available for the same also.

**Comment by rob-bb** [comment]
I agree.  Plus I get an error 

_mssql.c(242): fatal error C1083: Cannot open include file: 'sqlfront.h': No such file or directory 

which suggests it cant find something or that I have unpacked freedts in the wrong place.  

Where should I unpack freetds to?

**Comment by ramiro** [comment]
Fixed with 2.1.3.See https://pypi.python.org/pypi/pymssql/2.1.3

**Comment by etripathy** [comment]
@rob-bb Does the issue _mssql.c(242): fatal error C1083: Cannot open include file: 'sqlfront.h': No such file or directory got resolved for you. I am currently facing the issue when trying to install pymssql in win7 64 bit system

**Comment by ktritz** [comment]
same problem here using either pip or easy_install for pymssql 2.1.3

**Comment by akotulu** [comment]
Same problem with pip.

**Comment by neluhornsby** [comment]
Same problem with pymssql 2.1.3.

**Comment by mateuspontesmoraes** [comment]
Same problem with pip

**Comment by rsyring** [comment]
Come everyone, this is a closed bug, if you need help, take it to the mailing list: https://groups.google.com/forum/#!forum/pymssql

You can also find pre-compiled wheels for pymssql here: http://www.lfd.uci.edu/~gohlke/pythonlibs/#pymssql
