### ISSUE TITLE
Doesn't work with SQL Server Express by instance name

### ISSUE THREAD

**Issue by QuAzI** [pymssql/pymssql#423]
SQL Server Express installed and MS SQL Management Studio connects fine.
Connection string looks like
`Server=myServerName\myInstanceName;Database=myDataBase;User Id=myUsername; Password=myPassword;`

```
import pymssql

dbConnection = pymssql.connect(server='myServerName\myInstanceName', user='myUsername', password='myPassword', database='myDataBase')
```
failed with
>    File "pymssql.pyx", line 641, in pymssql.connect (pymssql.c:10788)
> pymssql.OperationalError: (20009, b'DB-Lib error message 20009, severity 9:\nUna
> ble to connect: Adaptive Server is unavailable or does not exist (myServerName\\myInstanceName)\n')

**Comment by ramiro** [comment]
Please don't open tickets here with user support questiion. Post them to our mailing list instead.

**Comment by pourdelir** [comment]
Replace [server='myServerName\myInstanceName'] 
with : `server=r'myServerName\myInstanceName'`
That "r" makes the \ sign real, so it should work. for external server you wouldn't need that.
