### ISSUE TITLE
Begin Transaction, do stuff, Commit Transaction (re-open of #427)

### ISSUE THREAD

**Issue by rob-bb** [pymssql/pymssql#428]
Reposting because this issue was closed but it shouldn't be.  

Please look at https://github.com/pymssql/pymssql/issues/427

Pymssql will not commit data if autocommit is set to False even when I explicitly call commit() on the connection.  It will only commit data if autocommit is set tot True but then I can't do transaction that consist of more than a single sql statement.

**Comment by rsyring** [comment]
Please provide a working example demonstrating the bug.

**Comment by rob-bb** [comment]
import sys
import pymssql
import logging
import logging.handlers

logger = logging.getLogger("DataBase")
logger.setLevel(logging.INFO)
file_log = logging.handlers.RotatingFileHandler('./example.log', maxBytes=10485760, backupCount=5)
file_log.setLevel(logging.DEBUG)

console_log = logging.StreamHandler()
console_log.setLevel(logging.DEBUG)

formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
file_log.setFormatter(formatter)
console_log.setFormatter(formatter)

logger.addHandler(file_log)
logger.addHandler(console_log)

class DataBase:

	def __init__(self, server, db, usr, pwd):

		self.logger = logging.getLogger("DataBase")
		try:
			self.con = pymssql.connect(host=server, user=usr, password=pwd, database=db)
			self.set_autocommit_mode(False)  # todo: setting to false does not work?
			self.cursor = self.con.cursor()
			self.cursor.execute("SELECT @@SERVERNAME")
			self.logger.info("Server: %s" % self.cursor.fetchone()[0])
			self.cursor.execute("SELECT DB_NAME()")
			self.db_name = self.cursor.fetchone()[0]
			self.logger.info("Database: %s" % self.db_name)
			self.logger.info("Autocommit: %s " % self.get_autocommit_mode())
			self.cursor.execute("SELECT @@VERSION")
			self.logger.info(self.cursor.fetchone()[0])
		except pymssql.Error as dbe:
			try:
				self.logger.error(" Error [%d]: %s" % (dbe.args[0], dbe.args[1]))
			except IndexError:
				self.logger.error(" Error: %s" % str(dbe))
			sys.exit(1)

	def get_autocommit_mode(self):
		return self.con.autocommit_state

	def set_autocommit_mode(self, mode):
		self.con.autocommit(mode)

	def start_transaction(self):
		self.logger.info(" Starting Transaction")
		self.execute("BEGIN TRANSACTION")

	def commit_transaction(self):
		self.logger.info(" Committing Transaction")
		self.execute("COMMIT TRANSACTION")


	def execute(self, sql):
		"""Runs an sql query.  Returns None on error."""
		try:
			self.logger.info(" Executing SQL - %s" % sql)
			self.cursor.execute(sql)
		except pymssql.Error as dbe:
			try:
				self.logger.error(" Error [%d]: %s" % (dbe.args[0], dbe.args[1]))
			except IndexError:
				self.logger.error(" Error: %s" % str(dbe))
				raise
			return None
		self.logger.info(' Rows affected - %d' % (self.cursor.rowcount))
		return self.cursor.rowcount

	def close(self):
		self.logger.info(" Closing database connections")
		try:
			if self.cursor:
				self.cursor.close()
			if self.con:
				self.con.close()
		except pymssql.Error as dbe:
			try:
				self.logger.error("Error [%d]: %s" % (dbe.args[0], dbe.args[1]))
			except IndexError:
				self.logger.error("Error: %s" % str(dbe))

if __name__ == "__main__":
	# Test Database Class

	db = DataBase(r"localhost", r"dbname", r"user", r"password")

	db.start_transaction()
	db.execute("INSERT INTO managed_tables (db_name, table_name, pk_column) VALUES ('db', 'table', 'id')")

	db.commit_transaction()
	db.close()
	sys.exit()

**Comment by rsyring** [comment]
You have provided a script, but it doesn't help identify any bug in pymssql.  I don't know what you are expecting to happen, what happens instead, and/or how the script demonstrates either.  Once again, I'd like to encourage you to take this problem to the mailing list: https://groups.google.com/forum/#!forum/pymssql

Please do not open another issue.  If, after getting help on the mailing list, you can demonstrate on the mailing list a minimal code example written in accordance with the DBAPI spec that pymssql implements (https://www.python.org/dev/peps/pep-0249/) that shows pymssql is not working as intended, then I will open a bug issue here.

As it stands, I suspect you are confused about how pymssql is supposed to work and need to do more research.

> Pymssql will not commit data if autocommit is set to False even when I explicitly call commit() on the connection.

I highly doubt this is true.  We have a test to cover this:

https://github.com/pymssql/pymssql/blob/f814fd9dedc7cd87fabbe92dfb1b6d19a5ed31a3/tests/test_pymssql.py#L43

and all tests are currently passing:

https://ci.appveyor.com/project/pymssql/pymssql

Furthermore, pymssql is used in production in a number of places.  If it was as badly broke as you say, we would have had a lot more error reports already.

**Comment by rob-bb** [comment]
Well, I expect to be able to start a transaction with the "BEGIN TRANSACTION" sql statement, insert data with the INSERT sql statement, and have sql server commit the data when I use "COMMIT TRANSACTION" sql statement.

Are you saying pymssql is designed not to commit a transaction when a user sends the "COMMIT TRANSACTION" statement?

When I used self.con.commit() instead of sending "COMMIT TRANSACTION" sql statement still the row is not inserted.

**Comment by rsyring** [comment]
> Are you saying...

The primary thing I'm saying is that this is not the appropriate forum for your questions.  Please take your questions to the google group where there are more users to help you.  :)

https://groups.google.com/forum/#!forum/pymssql

Thanks.
