### ISSUE TITLE
 How to get full precision data using pymssql? 

### ISSUE THREAD

**Issue by AhnSeongHyun** [pymssql/pymssql#429]
I want to get a data from db using ```callProc()```. 

I run the stored procedure in SQL Server Management Studio. And then see  ```0.342342``` but below code ```0.34```.

How to get full precision data using pymssql? 

<pre>
<code>
def data_search(self, order, reg_date):
    try: 
        self.open() 
        self.cursor.callproc("admin.dbo.search_test", (order, reg_date))
        result = list()
        for row in self.cursor:
            row = list(row)
            for i, v in enumerate(row):
                row[i] = v
            result.append(row) 
        self.close()
        return result
    except Exception as e:
        self.close() 
        raise e
</code>
</pre>

**Comment by rsyring** [comment]
Please don't use github issues for support questions.  Please use the forum for these questions:

https://groups.google.com/forum/#!forum/pymssql

Thanks.  :)

**Comment by AhnSeongHyun** [comment]
Thanks :)
