### ISSUE TITLE
Pymssql fails to install on Windows 10 with Python 3.5

### ISSUE THREAD

**Issue by morganthrapp** [pymssql/pymssql#439]
As in the title, `pip install pymssql` fails with the following error:

    Collecting pymssql
      Using cached pymssql-2.1.3.tar.gz
    Installing collected packages: pymssql
      Running setup.py install for pymssql
        Complete output from command "C:\Users\mpthrapp\Find Unbatched Payments\Scripts\python.exe" -c "import setuptools, tokenize;__file__='C:\\Users\\mpthrapp\\AppData\\Local\\Temp\\pip-build-jcy9lstk\\pymssql\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\mpthrapp\AppData\Local\Temp\pip-_7jz9j1o-record\install-record.txt --single-version-externally-managed --compile --install-headers "C:\Users\mpthrapp\Find Unbatched Payments\include\site\python3.5\pymssql":
        setup.py: platform.system() => 'Windows'
        setup.py: platform.architecture() => ('64bit', 'WindowsPE')
        running install
        running build
        running build_ext
        building '_mssql' extension
        creating build
        creating build\temp.win-amd64-3.5
        creating build\temp.win-amd64-3.5\Release
        C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\mpthrapp\AppData\Local\Temp\pip-build-jcy9lstk\pymssql\freetds\vs2015_64\include "-IC:\Users\mpthrapp\Find Unbatched Payments\include" -IC:\Users\mpthrapp\AppData\Local\Programs\Python\Python35\include -IC:\Users\mpthrapp\AppData\Local\Programs\Python\Python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" /Tc_mssql.c /Fobuild\temp.win-amd64-3.5\Release\_mssql.obj -DMSDBLIB
        _mssql.c
        _mssql.c(266): fatal error C1083: Cannot open include file: 'sqlfront.h': No such file or directory
        error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\cl.exe' failed with exit status 2

        ----------------------------------------
    Command ""C:\Users\mpthrapp\Find Unbatched Payments\Scripts\python.exe" -c "import setuptools, tokenize;__file__='C:\\Users\\mpthrapp\\AppData\\Local\\Temp\\pip-build-jcy9lstk\\pymssql\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\mpthrapp\AppData\Local\Temp\pip-_7jz9j1o-record\install-record.txt --single-version-externally-managed --compile --install-headers "C:\Users\mpthrapp\Find Unbatched Payments\include\site\python3.5\pymssql"" failed with error code 1 in C:\Users\mpthrapp\AppData\Local\Temp\pip-build-jcy9lstk\pymssql

It works via `wheel install` with gholke's wheel, but not via pip. Is this something that is supposed to work? If not, should the link to the wheel be added to the readme?

**Comment by ramiro** [comment]
Yopu have an ancient version of pip, one so old that it doesn't know about per-platform binary wheels. Upgrade it and you will be able to install without stumble that problem.

This is no-pymssql-specific Python tooling usage. Closing this issue for now, reopen it if you actually find a problem with pymssql.

**Comment by trejas** [comment]
Having the same issue with the most current version of pip. Same errors:

`Collecting pymssql
  Using cached pymssql-2.1.3.tar.gz
Skipping bdist_wheel for pymssql, due to binaries being disabled for it.
Installing collected packages: pymssql
  Running setup.py install for pymssql ... error
    Complete output from command "c:\program files\anaconda3\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\
cal\\Temp\\pip-build-uqzfd7mm\\pymssql\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n'
mpile(code, __file__, 'exec'))" install --record C:\Users\traey\AppData\Local\Temp\pip-5xd0_ttt-record\install-record.txt --sing
ly-managed --compile:
    setup.py: platform.system() => 'Windows'
    setup.py: platform.architecture() => ('64bit', 'WindowsPE')
    running install
    running build
    running build_ext
    building '_mssql' extension
    creating build
    creating build\temp.win-amd64-3.5
    creating build\temp.win-amd64-3.5\Release
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\t
Temp\pip-build-uqzfd7mm\pymssql\freetds\vs2015_64\include "-Ic:\program files\anaconda3\include" "-Ic:\program files\anaconda3\i
am Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt" "-I
86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared" "-IC:\Program
s Kits\10\include\10.0.14393.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt" /Tc_mssql.c /Fobuild\te
lease\_mssql.obj -DMSDBLIB
    _mssql.c
    _mssql.c(266): fatal error C1083: Cannot open include file: 'sqlfront.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2`

**Comment by neluhornsby** [comment]
Same issue (pymssql-2.1.3 and pip 9.0.1)

**Comment by jrussev** [comment]
I have the same issue :
_mssql.c(266): fatal error C1083: Cannot open include file: 'sqlfront.h': No such file or directory

**Comment by cmpalmer66** [comment]
I have the same issue as well. Python 3.6, pip 9.0.1.

**Comment by nmvollmer** [comment]
As a crappy workaround, I was able to install with pip 8.1.1.

**Comment by dfernan** [comment]
I have the exact same problem with python 3.6 and pip 9.0.1.  Has anyone found any acceptable solution and not some ad-hoc hacks?  Thanks in advance!

**Comment by rsyring** [comment]
We don't currently have wheels built for 3.6 (https://pypi.python.org/pypi/pymssql/2.1.3), so pip is trying to build pymssql but you don't have FreeTDS installed.  That is why you are getting the error message.

Unfortunately, we also don't have any comprehensive docs for how to build pymssql on Windows.  See here: https://groups.google.com/forum/#!topic/pymssql/2TRTsiRh1mY

Your options are to:

- Drop back to Python 3.5
- Use the Python 3.6 wheels available here: http://www.lfd.uci.edu/~gohlke/pythonlibs/
- Try to build pymssql using the advice given in the forum link above.
