### ISSUE TITLE
pymssql.output(int) returns rubbish when stored procedure returned null

### ISSUE THREAD

**Issue by konradperzyna** [pymssql/pymssql#441]
When pymssql.output(int) is passed to callproc and stored procedure returns null for that param, we get random integer instead of None. You can't tell if procedure returned valid integer or null.
For now the only way around I could think of is passing pymssql.output(str) instead: I get empty string then.

System params: Python 3.5, MS SQL Server 2008 R2, pymssql 2.1.3, Windows 7

**Comment by ramiro** [comment]
@konradperzyna How are you calling [bind](http://www.pymssql.org/en/latest/ref/_mssql.html#_mssql.MSSQLStoredProcedure.bind) for that nullable int outpur SP parameter? Are you pasing it `null=True`?

**Comment by dalao-B** [comment]
Has this problem been solved?   I had the same problem。
When both result set and output exist, output returns none

**Comment by maicotamanho** [comment]
I have the same problem. Does anyone have any other solution other than using str or changing the procedure to return a value in the int field? The problem occurs even changing the null=True parameter.

**Comment by termim** [comment]
Please provide a complete example.

**Comment by maicotamanho** [comment]
Example:
SQL Procedure:

_CREATE PROCEDURE [dbo].[test]
   @io_cd_erro   int          output   
as begin
	set @io_cd_erro = null
end_

Python Code:

_from pymssql import _mssql
conn = _mssql.connect(server="XX.XX.XX.XX", user="xx", password="xxxxxxx", database="xxxxx", port=1433, appname='TEST')
proc = conn.init_procedure("dbo.test")
proc.bind(0, _mssql.SQLINTN, "@io_cd_erro", output=True, null=True)
proc.execute()_

**Comment by maicotamanho** [comment]
This issue is causing serious crashes in our systems. I can try to help, I just need help setting up the pymssql library development environment.

**Comment by maicotamanho** [comment]
> @konradperzyna How are you calling [bind](http://www.pymssql.org/en/latest/ref/_mssql.html#_mssql.MSSQLStoredProcedure.bind) for that nullable int outpur SP parameter? Are you pasing it `null=True`?

Yes, the problem occurs even when passing null=True. This problem is serious and does not yet have a solution.

**Comment by maicotamanho** [comment]
> @konradperzyna How are you calling [bind](http://www.pymssql.org/en/latest/ref/_mssql.html#_mssql.MSSQLStoredProcedure.bind) for that nullable int outpur SP parameter? Are you pasing it `null=True`?



> @konradperzyna How are you calling [bind](http://www.pymssql.org/en/latest/ref/_mssql.html#_mssql.MSSQLStoredProcedure.bind) for that nullable int outpur SP parameter? Are you pasing it `null=True`?

<sub>Yes, the problem occurs even when passing null=True. This problem is serious and does not yet have a solution.</sub>

**Comment by maicotamanho** [comment]
> @konradperzyna How are you calling [bind](http://www.pymssql.org/en/latest/ref/_mssql.html#_mssql.MSSQLStoredProcedure.bind) for that nullable int outpur SP parameter? Are you pasing it `null=True`?

Yes, the problem occurs even when passing null=True. This problem is serious and does not yet have a solution.
