### ISSUE TITLE
Queries returning None result, work fine from other client applications

### ISSUE THREAD

**Issue by Izbitzer** [pymssql/pymssql#444]
I'm running a simple select query against a SQL Server 2014 DB (version 12.1.4100.1):

This is the code I'm running:

```
>>> import pymssql
>>> conn = pymssql.connect('localhost', '***', '***', 'ItemsCmsLgTest', as_dict=True)
>>> c = conn.cursor()
>>> res = c.execute("SELECT * FROM ucpItemDescriptors WHERE ItemId = '86292440-8000-48AF-92E6-B3EE15EFF6D2'")
>>> res.fetchone()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'fetchone'
```

The same query works fine when running from another client application, and oddly, queries to some tables work fine.

It also seems from the FreeTDS logs (attached) that it does get results back, but for some reason I still get `None` back. The query execution in the FreeTDS logs are in the last 100-150 rows or so.

There are no error messages anywhere as far as I can tell.

I have only seen this happen where the column I'm selecting on (ItemId in this case) is of type UNIQUEIDENTIFIER, but that might be a red herring.

**pymssql version:** 2.1.3
**FreeTDS version:** 0.91-6.1build1

[freetds.txt](https://github.com/pymssql/pymssql/files/369239/freetds.txt)

**Comment by rsyring** [comment]
`cursor.execute()` does not return a value.  Proper usage is like:

```python
cursor.execute('SELECT * FROM persons WHERE salesrep=%s', 'John Doe')
row = cursor.fetchone()
```

In the future, please use the mailing list for such questions :)  
https://groups.google.com/forum/#!forum/pymssql

**Comment by Izbitzer** [comment]
Wow, that's embarrassing, sorry about wasting your time! I will use the mailing list next time :)
