### ISSUE TITLE
Resulting in python to stop working, the process automatically exit

### ISSUE THREAD

**Issue by szcountryboy** [pymssql/pymssql#447]
environment:
pymssql-2.1.3, python-2.7

Use the following pseudo-code
while True:
   if conn == None:
      connect database method
   try:
      query (sql)
    except Exception, e:
      conn.close ()
      conn == None

   time.sleep (2)

Connect to the database sucessful
Unplug the network cable,
Wait a few seconds, then plug the Internet cable
Connect again, this will be reported error (20004, '\ x06 \ x08DB-Lib error message 20004, severity 9: \ nRead from the server failed \ nNet-Lib error during Unknown error (10054) \ n')
And will lead to python.exe process exit
what reason?
Thank you

**Comment by rsyring** [comment]
I doubt this is a bug in pymssql.  Please use the mailing list for help: 

https://groups.google.com/forum/#!forum/pymssql
