### ISSUE TITLE
Bug in conversion of datetime objects to string

### ISSUE THREAD

**Issue by tombech** [pymssql/pymssql#454]
The following code from _mssql.pyx:

`value = value.strftime('%Y-%m-%d %H:%M:%S.') + "%03d" % (value.microsecond // 1000)`

doesn't handle dates with year less than 1000, for example `datetime.datetime(906, 7, 28, 0, 0)`. 
The resulting string is "906-07-28 00:00:00.000" which SQL Server will refuse to cast to DATETIME2
in updates or inserts ("0906-07-28 00:00:00.000" works fine). The reason is that python's `strftime()` function doesn't zero-pad the year field.

**Comment by johnnymo87** [comment]
@tombech Did you find a workaround?
