### ISSUE TITLE
freetds success, pymssql fails - Adaptive Server Connection failed

### ISSUE THREAD

**Issue by drcrook1** [pymssql/pymssql#458]
http://stackoverflow.com/questions/10121212/cannot-connect-to-sql-server-database-using-pymssql-but-can-connect-using-underl 

import os
os.environ['TDSDUMP'] = 'stdout'
import pymssql  
conn = pymssql.connect(server='SRVER.database.windows.net', 
                   user='USR@SRVER', 
                   password='PW', 
                   database='DBNAME',
                   tds_version='8.0',
                   port = '1433') 
I can call

sudo TDSVER=8.0 tsql -H SRVR.database.windows.net -p 1433 -U USR@SRVR -P PSSWRD -D DATABASE
The only thing I can think of is the password has some symbols in it, but nothing too fancy.

Machine Configuration:
Ubuntu 16.04
Python (normal) 3.5

**Comment by ramiro** [comment]
Please post support requests like this to the mailing list.

Make sure to specify what version of pymssql you are using and how you installed it.
