### ISSUE TITLE
Why isn't the manylinux wheel built with ssl support?

### ISSUE THREAD

**Issue by waynew** [pymssql/pymssql#461]
I recently [ran into an issue](http://stackoverflow.com/q/39129928/344286) where I couldn't connect to azure databases because the Linux wheel doesn't have SSL support.

Is there a reason that the Linux wheel doesn't have SSL support?

**Comment by ramiro** [comment]
[PEP 513](https://www.python.org/dev/peps/pep-0513/) Python binary wheels specify a way to create and distribute non pure binary Python modules by using/assuming a lowest common denominator set of dynamic libs dependencies for the Linux platform.

As you might already know, pymssql actually is a wrapper around FreeTDS.

And SSL support in FreeTDS means linking against libraries like OpenSSL or GNU TLS.

Our manylinux1 wheels, which we have started shipping with version 2.1.3 do link a static copy of FreeTDS so our users aren't forced to build it.

We've chosen to not link OpenSSL,, be it either

* Statically, as that would force us to release a new version of pymssql with every OpenSSL security revision (technical reason). Also, I suspect there would be licensing issues if we included a statically linked version of OpenSSL (legal reason)
* Dynamically, as it isn't included in the reduced set of libs a module can assume to be present in every supported Linux platform: https://www.python.org/dev/peps/pep-0513/#the-manylinux1-policy

See also (it's important to read all of them to have a full picture of the situation):

* Parts of this discussion could be relevant https://github.com/pymssql/pymssql/issues/399
* This other comment on another issue: https://github.com/pymssql/pymssql/issues/459#issuecomment-242993912
* The PEP 513 document linked above, particularly this section:  https://www.python.org/dev/peps/pep-0513/#security-implications


PS: Please, don't post questions like this as issues here but rather on our mailing list.
