### ISSUE TITLE
executemany parameter substitution

### ISSUE THREAD

**Issue by andreacassioli** [pymssql/pymssql#462]
Hi,

I would like to use `executemany` to perform a sequence of `SELECT` queries. I have a list of tables

```
tables  = ['PythonAccess','PythonAccessRoutingLegs','PythonAccessEmptyRoutings', 'PythonAccessDemandRoutings', 'PythonAccessRoutingLegCost']
```

and I organize the code as 

```
qs = "SELECT * FROM [tmp].[guest].[%s] WHERE RunId = '1111'"

tt = [ ( t.encode('utf-8') ) for t in tables]
print(tt)
cursor.executemany(qs, tt)

```

I get the following

```
_mssql.MSSQLDatabaseException: (208, b"Invalid object name 'tmp.guest.'PythonAccess''.DB-Lib error message 20018, severi
ty 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")
```

I am very much confused about the table name `'tmp.guest.'PythonAccess`. Why are there such quotes?

Note that I can successfully query one table at the time.

I have tried to change encoding in many different ways but I always get some strange output.

**Comment by klesun** [comment]
You probably don't care anymore after those 7 years, but I'd like to drop my 5 cents as I had the same question.

As far I know, you can't use placeholders for table names, you can only use them for expressions. 
The `executemany()` in pymssql performance and functionality wise is not much different from just an alias for:
```py
for t in tt:
    cursor.execute(qs, t)
```

For selecting rows from multiple same structure tables in one query I can recommend to use the `UNION ALL` approach instead:
```py
cursor.execute(" UNION ALL ".join([
    "SELECT * FROM [" + t + "]"
    for t in tt
]))
```
Make sure to properly escape the table name to avoid injections. Sadly that seems to be the only way to query tables by dynamic name.
