### ISSUE TITLE
Error when connecting (Python 2.7 - Windows 10 Home 64-bit)

### ISSUE THREAD

**Issue by nobody37** [pymssql/pymssql#465]
Traceback (most recent call last):
  File "testmssql.py", line 9, in <module>
    conn = pymssql.connect(serverName, userName, passwordVar, 'master')
  File "pymssql.pyx", line 635, in pymssql.connect (pymssql.c:10734)
  File "_mssql.pyx", line 1902, in _mssql.connect (_mssql.c:21821)
  File "_mssql.pyx", line 553, in _mssql.MSSQLConnection.__init__ (_mssql.c:5917)
ValueError: too many values to unpack (expected 2)

Happens when I try with _mssql.connect as well.

Installed via pip install pymssql.

Also tried installing from here and running ./setup.py build I get an error (can't find sqlfront.h, there's an sqlfront.pxd in the src directory).

**Comment by rsyring** [comment]
Please provide a simple and self-contained test case that we could run locally (without any dependencies) that demonstrates the problem.  Thanks.

**Comment by nobody37** [comment]
import pymssql

server = 'MyServer'
user = 'MyUser'
password = 'MyPassword'

conn = pymssql.connect(server, user, password, "master")
conn.close()

**Comment by rsyring** [comment]
@nobody37 I'm not sure what is going on with your install, but something is messed up.  

I've tried the latest pymssql in both Python 2.7 and 3.5 on Ubuntu Linux.  The following script works just fine for me:


```python
import pymssql

server = '172.16.1.2'
user = 'test'
password = 'test'

conn = pymssql.connect(server, user, password, 'test')
conn.close()
```

It sounds to me like you may have an old or badly patched version of pymssql.

If you need additional assistance, please try the mailing list: https://groups.google.com/forum/#!forum/pymssql

**Comment by nobody37** [comment]
This is a fresh install of Win 10 (64-bit). The only other software on this box besides Python is MSSQL 2016 Express and VS2015 Community.
Fresh install of Python 2.7.
Fresh install of Pymssql via pip. (Literally the first Python module I've installed on that box.)
Installing via Git as of yesterday does not seem to work trying to run setup.py build, complains about sqlfront.h not found (there's an sqlfront.pxd there though).

I found a workaround to the issue since I only needed Detach/Attach DB functionality to just call SqlCmd from the cmdline and run that from Python. Would be nice to have this working for future projects.

Since it was installed by Pip, I don't have FreeTDS already installed (or MingW). Could that be the issue?

**Comment by rsyring** [comment]
I just ran the test script on a Windows 7 box, Python 2.7.8 32-bit, `pip install -U` for the latest version of pymssql, and had no issues.

Are you using 32 bit or 64 bit Python?

Building pymssql is complex on Windows, but the wheels we make available on pypi have FreeTDS built in, so you don't need FreeTDS or MingW unless you want to build it yourself.

**Comment by rsyring** [comment]
I also upgraded to 2.7.12 on 32 bit and installed 64 bit and tested on both.  Still no errors.

I don't see how a change to Windows 10 would give you an error message like you are getting above.

FWIW, have you tried using dictionary style arguments to pymssql.connect()?

**Comment by nobody37** [comment]
The version of Python 64-bit I installed yesterday was from an MSI (python-2.7.12.amd64.msi) from the Python page.

I tried dictionary style arguments (pymssql.connect(server='SERVERNAME',user='UserName',password='Password')) and got the same result. 

I also tried omitting user/pass to see if would try a trusted connection but still got that same error above (File "_mssql.pyx", line 553, in _mssql.MSSQLConnection.__init (_mssql.c:5917)
 ValueError: too many values to unpack (expected 2))

Interestingly if I specify no parameters at all to connect it just hangs forever.

**Comment by nobody37** [comment]
This is still not working. I've installed MingW so I can try and build pymssql. I want to get this up and running quickly so I can use pymssql to access a SQL Server backend from a Django web app.

Why is this not picking up "sqlfront.h"?

PS C:\Users\rnern\Downloads\pymssql-master\pymssql-master> python setup.py build -c mingw32
setup.py: platform.system() => 'Windows'
setup.py: platform.architecture() => ('64bit', 'WindowsPE')
C:\Python27\lib\site-packages\setuptools\dist.py:285: UserWarning: Normalizing '2.2.0.dev' to '2.2.0.dev0'
  normalized_version,
running build
running build_ext
skipping 'src\_mssql.c' Cython extension (up-to-date)
building '_mssql' extension
creating build
creating build\temp.win-amd64-2.7
creating build\temp.win-amd64-2.7\Release
creating build\temp.win-amd64-2.7\Release\src
C:\MingW\bin\gcc.exe -mdll -O -Wall -IC:\Users\rnern\Downloads\pymssql-master\pymssql-master\freetds\ming_64\include -IC
:\Python27\include -IC:\Python27\PC -c src\_mssql.c -o build\temp.win-amd64-2.7\Release\src\_mssql.o -DMSDBLIB -Wl,-allo
w-multiple-definition -Wl,-subsystem,windows-mthreads -mwindows -Wl,--strip-all -Wl,-allow-multiple-definition -Wl,-subs
ystem,windows-mthreads -mwindows -Wl,--strip-all
src\_mssql.c:274:22: fatal error: sqlfront.h: No such file or directory
compilation terminated.
error: command 'C:\\MingW\\bin\\gcc.exe' failed with exit status 1

**Comment by nobody37** [comment]
I tried also deleting the existing _mssql.c and rebuilding and got the same result:

PS C:\Users\rnern\Downloads\pymssql-master\pymssql-master> cd src
PS C:\Users\rnern\Downloads\pymssql-master\pymssql-master\src> del .\_mssql.c
PS C:\Users\rnern\Downloads\pymssql-master\pymssql-master\src> cd ..
PS C:\Users\rnern\Downloads\pymssql-master\pymssql-master> python setup.py build -c mingw32
setup.py: platform.system() => 'Windows'
setup.py: platform.architecture() => ('64bit', 'WindowsPE')
C:\Python27\lib\site-packages\setuptools\dist.py:285: UserWarning: Normalizing '2.2.0.dev' to '2.2.0.dev0'
  normalized_version,
running build
running build_ext
cythoning src\_mssql.pyx to src\_mssql.c
building '_mssql' extension
C:\MingW\bin\gcc.exe -mdll -O -Wall -IC:\Users\rnern\Downloads\pymssql-master\pymssql-master\freetds\ming_64\include -IC
:\Python27\include -IC:\Python27\PC -c src\_mssql.c -o build\temp.win-amd64-2.7\Release\src\_mssql.o -DMSDBLIB -Wl,-allo
w-multiple-definition -Wl,-subsystem,windows-mthreads -mwindows -Wl,--strip-all -Wl,-allow-multiple-definition -Wl,-subs
ystem,windows-mthreads -mwindows -Wl,--strip-all
src\_mssql.c:274:22: fatal error: sqlfront.h: No such file or directory
compilation terminated.
error: command 'C:\\MingW\\bin\\gcc.exe' failed with exit status 1
PS C:\Users\rnern\Downloads\pymssql-master\pymssql-master>

**Comment by rsyring** [comment]
The only thing left that seems different between my tests and yours is that I'm using Windows 7 and you are using Windows 10.  I just can't see that the error you are getting could result from that difference.  Since I can't reproduce the error, I'm going to close this issue.

I think at this point it is best for you to take this troubleshooting to our forum: 

https://groups.google.com/forum/#!forum/pymssql

Thanks.

**Comment by nobody37** [comment]
Not a problem. I found pyodbc to just simply work the first time when I did a pip install. I've got it connecting fine over ODBC to the MSSQL database.

In order to debug your software's issue on my system I'd need to be able to build from Git manually and diagnose. I went through a number of steps getting MingW/MSYS installed, only to find multiple errors when trying to run FreeTDS's autogen.sh from a Git clone in order to make the configure scripts. 

So I decided to try PyODBC and it ran fine the first time, I'm not 100% satisfied with ODBC since I have to specify [dbo].[Blah] when selecting from a table instead of dbo.Blah, and other nuances of working with ODBC vs native SQL Server drivers, but it works and I can get moving along with what I need to do. So I'll accept it as a solution for now for working with databases over Python.

I would highly recommend testing the pymssql build and execution on a Windows 10 64-bit box or virtual machine (especially since Windows 7 is past end of life as far as MS Support is concerned). Also test with SQL Server 2016 Express and see if that produces any errors. The one I tried was the wheels install, maybe it could be something going on in FreeTDS.

**Comment by rsyring** [comment]
@ramiro do you know if we could run the AppVeyor tests against specific versions of Windows and SQL Server?

**Comment by ramiro** [comment]
Re: OS version: We don't have too many choices for our Windows CI runs:  https://www.appveyor.com/docs/installed-software/#operating-system

Re: SQL Server version: We are already running our test suite against SQL2008R2SP2 and SQL2012SP1 . See https://github.com/pymssql/pymssql/blob/master/appveyor.yml

Also: https://www.appveyor.com/docs/installed-software/#services-and-databases We cartainly could add a few newer SQL Server versions to the CI matrix.

Anyway I don't think SQL Server version has anything to to with this issue as the error happens way before the client contacts the server.

FWIW I've tested installing pymssql via pip (which downloads and installs the wheel so no compilation is involved) on Windows 8.1 x86_64 and running a simple connection test and it works flawlessy as expected.

I'd like to see the output of:

```
print(type(server))
print(type(user))
print(type(password))
```

Are you sure you don't have a start trailing comma in sme line which is somehow converting one of the variables to tuple instead of a string?

**Comment by ramiro** [comment]
Looking at the original traceback it seems this is happeming at this line:  https://github.com/pymssql/pymssql/blob/9de15f5773725e4acafb86e1b97eb2bfe58554c4/_mssql.pyx#L553

So it seems you are passing in a server name with more than one `\` character.

We could have a more defensive approach, yes. But first it would be nice to fully know the scenario at hand.

**Comment by nobody37** [comment]
Let me try that, it may be that I need to remove the initial \\

**Comment by nobody37** [comment]
Yep that did the trick, it was the preceding \\\\ using the UNC name instead of just SERVER\\INSTANCE, case closed. (/slaps self in face) 

It might be good for the code to do some checking early on to see if it's trying to hit a UNC path and either warn the user or remove the preceding slashes (it's easy to confuse on a box like this one where I'm using the full UNC path all over the place for shares and the like).

Luckily now I can do some native MSSQL from python. Sweet! :)

I'd still like to get it building though, and I'm having trouble tracking down a community or forum for FreeTDS, best thing I know to do is post to their mailing list. What build environment are you guys using on Windows for FreeTDS? I'm installing Cygwin right now, but have a minimal install of MSYS/MingW on the system. When I've tried to run autogen.sh for FreeTDS from Git (configure isn't already made at that point it looks like), I get tons of errors usually about permissions for trying to delete files in /tmp even though I'm running MSYS as Admin. (I'm aware this is an out of scope question, but any help to steer me in the right direction would be very greatly appreciated. I figure since it's a heavy dependency of pymssql you guys might know what to do.)

**Comment by rsyring** [comment]
The best bet for understanding how to compile is to look at how our CI system does it:

https://github.com/pymssql/pymssql/blob/master/appveyor.yml

This might also help:

https://github.com/FreeTDS/freetds/blob/master/README.Windows
