### ISSUE TITLE
get image or varbirary[max] type from sql server 2014 ,return 'System.Byte[]' str type 

### ISSUE THREAD

**Issue by firehang** [pymssql/pymssql#469]
'>>> cursor=conn.cursor()
'>>> cursor.execute("select * from [dbo].[TMoShiTuPian]")
'>>> r=cursor.fetchall()
'>>> r
[(u'0CA91A28-9C37-4607-878B-9048D7185D18', datetime.datetime(2016, 11, 3, 11, 15, 41, 533000), u'201611031115485795_dingdanfahuo.JPG', 'System.Byte[]'), (u'0E31BFD1-F79B-4B2F-BFA1-5999F7C000E1', datetime.datetime(2016, 11, 3, 11, 15, 39, 517000), u'201611031115467981_dingdanwangong.JPG', 'System.Byte[]')]

**Comment by rsyring** [comment]
Please include a full example including create statements for a temporary table and what you are trying to do with the data once it comes back from the database.

**Comment by firehang** [comment]
I'm sorry, it's our problem.it ok.
