### ISSUE TITLE
Adaptive server connection failed (DB-Lib error message 20002, severity 9)

### ISSUE THREAD

**Issue by syedaliammar** [pymssql/pymssql#472]
Hi,
I'm sure this issue has been raised an uncountable number of times before but perhaps, someone could still help me. 
I am using pymssql v2.1.3 with Python 2.7.12 and the code that I used several times until yesterday to write data to my Azure SQL DB has somehow decided not to work anymore - for no apparent reason. The firewall is set, my IP is in the whitelist, I can connect to the database using SQL Server Management Studio and query the data but I still keep getting this error when attempting to connect using pymssql.

The app is a Flask web-app and following is how I connect to the DB:
`conn = pymssql.connect(server='mydatabase.database.windows.net', user='myusername@mydatabase', password='mypassword', database='mydatabase')`

**Comment by ramiro** [comment]
pymssql IS a wrapper for FreeTDS: It can't use other drivers/stacks/libraries.

If you are using an official pymsql 2.1.3 wheel downloaded from pypi then you copy of pymssql includes a statically linked cpy of FreeTDS. But Such copy doesn't include the feature to use TLS-protected connection which are a mandatory requirement to connect to Azure.

To be able to do so you will need to build/use a copy of FreeTDS linked against OpenSSL or similar. and then build pymssql against that version of FreeTDS.

This means your setup should heve never worked.

Pleae post support quetions like this to our mailing list, not here. I'm closing this issue.

**Comment by syedaliammar** [comment]
@ramiro It indeed worked with this exact setup and on the same machine, otherwise this question would be pointless. Thanks for the posting guidelines.
