### ISSUE TITLE
I keep getting an error when trying to download and install the package "sqlfront.h" file notfound

### ISSUE THREAD

**Issue by bryarcole** [pymssql/pymssql#475]
[pysqlfail.txt](https://github.com/pymssql/pymssql/files/704954/pysqlfail.txt)

I've made sure to install freetds; I even unlinked it and reinstalled it. I really want to get this to work, any ideas?

**Comment by bryarcole** [comment]
Figured it out from a another thread on here, thanks,

**Comment by ktritz** [comment]
how did you figure it out? I'm getting the same problem, windows 10, python 3.6
