### ISSUE TITLE
Does not work IN (%s)  for list and tuple 

### ISSUE THREAD

**Issue by itpooh** [pymssql/pymssql#476]
cursor.execute('SELECT 1 WHERE 2 IN (%s)',  (tuple(range(4)),))
or
list_more_one_size = [3,4]
cursor.execute('SELECT 1 WHERE 2 IN (%s)', (tuple(list_more_one_size),))

pymssql.ProgrammingError: (102, b"Incorrect syntax near ','.DB-Lib error message 102, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n")

**Comment by rsyring** [comment]
This is a programming error.  You are relying on the string representation of lists and tuples to be valid SQL.  Please use the forums for technical support: https://groups.google.com/forum/#!forum/pymssql
