### ISSUE TITLE
Acquire the bound query as a string

### ISSUE THREAD

**Issue by CMCDragonkai** [pymssql/pymssql#478]
Is there a way to get the actual bound query as a string after binding it?

That is after running:

```
cursor.execute(query, data)
```

How can I find what the query looks like after the data is bound to it?

**Comment by rsyring** [comment]
Please post questions like this to the mailing list: https://groups.google.com/forum/#!forum/pymssql

Github issues are for bugs and feature requests.  Thanks.  :)
