### ISSUE TITLE
PYMSSQL - How to connect to a SQL Server instance?

### ISSUE THREAD

**Issue by MaximoTrinidad** [pymssql/pymssql#479]
I'm able to connect to a single instance of SQL Server.  Unfortunately, I've tried to a different SQL instance on the same system.  

What's the correct string format?  I've tried:
server = 'computername\instance1' - failed
server = 'computername\\\instance1' - failed
server = 'computername' - Good

Error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pymssql.pyx", line 641, in pymssql.connect (pymssql.c:10824)
pymssql.OperationalError: (20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (MTRINIDADLT2\\MSSQL2K16A)\n')

I appreciate the help.

Thanks,
Maximo Trinidad

![pymssql_sqlinstance1_2017-02-01_10-59-37](https://cloud.githubusercontent.com/assets/19892435/22514780/69007ca8-e86e-11e6-9834-222df5d694f6.jpg)

![pymssql_sqlinstance_2017-02-01_10-59-37](https://cloud.githubusercontent.com/assets/19892435/22514838/96fcbdb0-e86e-11e6-877a-09e8f1375b7f.jpg)

**Comment by rsyring** [comment]
Please use the forums for support questions: https://groups.google.com/forum/#!forum/pymssql

The GitHub issue tracker is for bugs and feature requests.

You may also want to review: http://pymssql.org/en/stable/faq.html#cannot-connect-to-sql-server
