### ISSUE TITLE
Error on install pymssql use pip under proxy

### ISSUE THREAD

**Issue by Hrom-in-space** [pymssql/pymssql#481]
If installed pymssql using pip with proxy (pip3 --proxy <proxy> install pymssql) depending on the specified in setup.py setup_requires will not be installed because EasyInstal used for downloading. It might be worth rename setup_requires -> install_requires to pip immediately downloaded all dependencies?

**Comment by rsyring** [comment]
setup_requires and install_requires are for two different things.  I don't believe this is likely a bug in pymssql.
