### ISSUE TITLE
pypi linux python 3.6 wheel not availble

### ISSUE THREAD

**Issue by mas-dse-juremigi** [pymssql/pymssql#482]
is support for python 3.6 planned? The latest version of Anaconda is on 3.6, as is SQL Alchemy.  I had to switch to pyodbc because the source will not build successfully in python 3.6.

**Comment by efficks** [comment]
I also need support for Python 3.6 on Windows 7 64 bit.
Documentation to build the project is not very clear for Windows. And no automated build seems to exists.

**Comment by rsyring** [comment]
> is support for python 3.6 planned?
Yes, but none of the current maintainers have much time give to pymssql.  Want to help out?

> I also need support for Python 3.6 on Windows 7 64 bit.

You can find Windows builds here:

http://www.lfd.uci.edu/~gohlke/pythonlibs/#pymssql

> Documentation to build the project is not very clear for Windows. And no automated build seems to exists.

An automated build does exist and is linked to from the badge on the readme:

https://ci.appveyor.com/project/level12/pymssql/branch/master

Everything you need to know about building on Windows can probably be gleaned from how we setup Appveyor to build it.  Starting point:

https://github.com/pymssql/pymssql/blob/master/appveyor.yml

Yes, none of this is ideal.  You are welcome to create PRs to update the docs to help us out.  :)

**Comment by rsyring** [comment]
I'm sorry, I missed the "linux" part!  The above comment is not so helpful for Linux.

We do have a Linux build, linked to from the Readme

https://travis-ci.org/pymssql/pymssql

The travis config should have the info in it needed to build on Linux:

https://github.com/pymssql/pymssql/blob/master/.travis.yml

to fill in the gaps where the docs aren't enough.

**Comment by ramiro** [comment]
Please see #473.

**Comment by KptainBiwouak** [comment]
Hello,
After having used your links, I am still facing same issues to setup pymssql module on Windows.
sqlfront.h NOT found.
I do not understand what to do to complete my setup?
Do I have to wait for pymssql 2.1.4?
Do I have forget some dependencies?
