### ISSUE TITLE
UnicodeEncodeError when database name has non-ASCII characters

### ISSUE THREAD

**Issue by DKanarsky** [pymssql/pymssql#484]
When I'm trying to connect to a database with non-ascii symbols in it's name the UnicodeEncodeError occurs with text: "'ascii' codec can't encode character '\u0410' in position... "
Is there any solution or I have to rename database?

**Comment by driftluo** [comment]
Hi, everyone, I encountered the same problem, the database name is Chinese, can't connect with text："'ascii' codec can't encode character '\xd07' in position..." 

So, is there any solution?

The database name can not rename, because the database is connected to other software, I just crawl the data, I can't rename it.

**Comment by hh-in-zhuzhou** [comment]
I met this problem today 2017/12/16,  I installed pymssql thru pip, and pip list shows the pymssql version is 2.1.3
@driftluo @Pentusha @damoxc 
pymssql.connect( server, username, passwd, 'non ascii 数据库名') 
then exception throws:
UnicodeEncodeError: 'ascii' codec can't encode characters in position

**Comment by driftluo** [comment]
@hh-in-zhuzhou This problem seems a long time, I have solved this problem with pyodbc

**Comment by hh-in-zhuzhou** [comment]
@driftluo 哥们，你看了这位Pentusha给你的回复没？他提交的pr，就改动了一行，原来这个"'ascii' codec can't encode character '\xd07' in position..."错误是因为一行代码：db.encode('ascii')引起的。。。。我当时看完很无语。。。感谢你给我的回复，我是怎么解决的呢，我在connect中没有指定数据库，然后在查询时先写一行 use [数据库名字]， 这样也可以解决。

**Comment by driftluo** [comment]
@hh-in-zhuzhou
I have not paid attention to this problem for a long time, but this library should not be updated for a very long time. Although the solutions have been given, no one has ever merged（这个问题我很久没有关注过了，这个库应该是很久没更新过了，即使已经存在了 pr，也没有人做合并工作）

**Comment by rsyring** [comment]
>  but this library should not be updated for a very long time. Although the solutions have been given, no one has ever merged

Yes, the project is looking for maintainers who have time to support: https://github.com/pymssql/pymssql/issues/516

**Comment by Solar-Matrix-Core** [comment]
> @driftluo 哥们，你看了这位Pentusha给你的回复没？他提交的pr，就改动了一行，原来这个"'ascii' codec can't encode character '\xd07' in position..."错误是因为一行代码：db.encode('ascii')引起的。。。。我当时看完很无语。。。感谢你给我的回复，我是怎么解决的呢，我在connect中没有指定数据库，然后在查询时先写一行 use [数据库名字]， 这样也可以解决。

谢谢大佬 4年过去了 这个bug居然还存在 我弄了一下午 卡在这个'ascii' codec can't encode character这里 我还看它的项目介绍里写着unicode friendly 我人傻了

**Comment by termim** [comment]
Should be fixed in 351bd30f22d87306cf41024f8e2d01693df644f4.
