### ISSUE TITLE
FreeTDS 1.X incompatibility on Mac

### ISSUE THREAD

**Issue by jpotts18** [pymssql/pymssql#485]
Trying to install this lib with 1.x version of FreeTDS caused errors. I had to roll back my version of FreeTDS 0.95.69 in order for this library to work. This worked for me as a fix. 

`brew install homebrew/versions/freetds091`
`brew switch freetds 0.95.69`
`pip install pymssql`

I wonder if the .travis.yml file needs to be updated to add the new versions of FreeTDS to the build matrix.

**Comment by ramiro** [comment]
Plase see see #432
