### ISSUE TITLE
Connection not closing

### ISSUE THREAD

**Issue by gaw89** [pymssql/pymssql#494]
I just got a message from a DBA that my query is causing blocks.  The query is run through a Python script using pymssql.  The script completed over an hour ago.

Does the pymssql connection close when the script it's in finishes, or do I have to close the connection manually?

Thanks.

**Comment by rsyring** [comment]
GitHub issues should not be used for questions like this.  Please visit the mailing list instead: https://groups.google.com/forum/#!forum/pymssql

**Comment by gaw89** [comment]
Understood.  Sorry.  Thanks for a great library, by the way!
