### ISSUE TITLE
Installing 32-bit version in a python 3.6.1 virtualenv does not work - "basetsd.h" missing

### ISSUE THREAD

**Issue by dkessel** [pymssql/pymssql#495]
I am trying to install using "pip install pymssql" in a python 3.6.1 virtualenv.

Which exact components of Visual Studio do I have to install? I have some components, but something seems to be missing here...

I get the following error output:
Collecting pymssql
  Using cached pymssql-2.1.3.tar.gz
Installing collected packages: pymssql
  Running setup.py install for pymssql: started
    Running setup.py install for pymssql: finished with status 'error'
    Complete output from command C:\Users\kessel.VISUS-TT\virtualenv\pypimps\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\KESSEL~1.VIS\\AppData\\Local\\Temp\\pip-build-yk8hztht\\pymssql\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\KESSEL~1.VIS\AppData\Local\Temp\pip-8_lz6c86-record\install-record.txt --single-version-externally-managed --compile --install-headers C:\Users\kessel.VISUS-TT\virtualenv\pypimps\include\site\python3.6\pymssql:
    setup.py: platform.system() => 'Windows'
    setup.py: platform.architecture() => ('32bit', 'WindowsPE')
    running install
    running build
    running build_ext
    building '_mssql' extension
    creating build
    creating build\temp.win32-3.6
    creating build\temp.win32-3.6\Release
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\KESSEL~1.VIS\AppData\Local\Temp\pip-build-yk8hztht\pymssql\freetds\vs2015_32\include -IC:\Users\kessel.VISUS-TT\virtualenv\pypimps\include -IC:\kessel\dev\python36\include -IC:\kessel\dev\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /Tc_mssql.c /Fobuild\temp.win32-3.6\Release\_mssql.obj -DMSDBLIB
    _mssql.c
    c:\kessel\dev\python36\include\pyconfig.h(222): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

**Comment by rsyring** [comment]
If it helps, there are wheels for 3.6 on a link on this issue: https://github.com/pymssql/pymssql/issues/473

**Comment by dkessel** [comment]
Exactly what I needed! Thanks.
