### ISSUE TITLE
[INFO requested] Question about db_cancel() in execute()

### ISSUE THREAD

**Issue by jkchin** [pymssql/pymssql#499]
Can someone explain why there needs to be a db_cancel() call / aka TDS ATTENTION packet per execute

```
    def execute(self):
        cdef RETCODE rtc
        cdef int output_count, i, type, length
        cdef char *param_name_bytes
        cdef BYTE *data
        log("_mssql.MSSQLStoredProcedure.execute()")

        # Cancel any pending results as this throws a server error
        # otherwise.
        db_cancel(self.conn)
```
https://github.com/pymssql/pymssql/blob/3bc299936fe2d35196dd4c9ebc8a22777f0c97e6/src/_mssql.pyx#L1591

**Comment by jkchin** [comment]
According to the comment block, it's to cancel any pending results. How often would this situation arise, and what kind of server error do we see?

The motivation for my question is asking whether this is a necessary action

**Comment by jkchin** [comment]
I see on reading https://github.com/pymssql/pymssql/blob/3bc299936fe2d35196dd4c9ebc8a22777f0c97e6/src/_mssql.pyx#L415 it'll only do the cancel if conn.dbproc is not null. What's it's normal state? I'm using a connection pool on sqlalchemy, so i'm not sure what the normal state
```
cdef RETCODE db_cancel(MSSQLConnection conn):
    cdef RETCODE rtc

    if conn == None:
        return SUCCEED

    if conn.dbproc == NULL:
        return SUCCEED

    with nogil:
        rtc = dbcancel(conn.dbproc);

    conn.clear_metadata()
    return rtc
```

**Comment by rsyring** [comment]
We would prefer that discussion questions like this go to the forum and not be created as issues.  Thank you.

https://groups.google.com/forum/#!forum/pymssql
