### ISSUE TITLE
SQL Server 2017 support

### ISSUE THREAD

**Issue by zzzeek** [pymssql/pymssql#502]
Microsoft now has easy to install SQL Server builds for linux, including for docker:

https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker

The above instructions work.    However, TDS-style clients can't connect.   pymssql just hangs,and trying to use FreeTDS "tsql" also hangs until we get the output:

```
locale is "en_US.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"
129Error 20004 (severity 9):
	Read from the server failed
	OS error 115, "Operation now in progress"
Error 20002 (severity 9):
	Adaptive Server connection failed
There was a problem connecting to the server

```

if pymssql can connect to this thing I can finally have SQL Server coverage for SQLAlchemy in my Jenkins environment.   Any insight into what magic beans is needed here to make TDS work?

**Comment by guruofgentoo** [comment]
My first questions/thoughts would be:
- how are you running the mssql container?
- have you confirmed that when tests begin running (or you run tsql), the mssql docker container is fully started and ready for connections (can take 10-15 seconds in my experience, on good hardware)?
- have you confirmed that the port is mapped where you need it (the container exposes 1433 by default, but unless you map it to the host network, it will only be available on the docker container's IP)?

**Comment by zzzeek** [comment]
> how are you running the mssql container?

exactly as in the steps at https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker

> have you confirmed that when tests begin running (or you run tsql), the mssql docker container is fully started and ready for connections (can take 10-15 seconds in my experience, on good hardware)?


I can telnet to the connection and also I can log into the database itself using "sqlcmd" from *inside* the container, if you are suggesting that's not enough then I can figure out how to install "sqlcmd" on the host itself and try again.  Netstat -ant shows the mapped port (1401 in this case) as listening on * as well.

If you look at the error message I am getting, it is distinctly different from the error you get when you try to connect to a non-listening port / host, and it also takes much longer for this particular error to come back.   Googling for "OS error 115, "Operation now in progress"" errors w/ TDS has suggested TDS version issues for older versions of SQL Server.

> have you confirmed that the port is mapped where you need it (the container exposes 1433 by default, but unless you map it to the host network, it will only be available on the docker container's IP)?

if you look at the tutorial, they have you mapping port 1401 host to 1433 container and this is working (I have run lots of databases and services in containers in a variety of network topologies so I'm pretty familiar with the basics).

**Comment by zzzeek** [comment]
note that the tds testing I did can be seen at https://github.com/FreeTDS/freetds/issues/146 I thought I was responding to that issue.

**Comment by zzzeek** [comment]
I upgraded to fedora 26 and it is now working.
