### ISSUE TITLE
Connect to LocalDB

### ISSUE THREAD

**Issue by thorstenkampe** [pymssql/pymssql#503]
Is it possible to connect to a LocalDB Instance on a Windows host? LocalDB supports Named Pipe connection and Windows authentication only. This is the connection string (via SQLAlchemy)
```
'mssql+pymssql://(LocalDB)\\MSSQLLocalDB/master'
```
The error is:
```
(pymssql.InterfaceError) Connection to the database failed for an unknown reason
````
The connection works fine with PyODBC:
```
Microsoft SQL Server 2017 (RC2) - 14.0.900.75 (X64)
        Jul 27 2017 08:53:49
        Copyright (C) 2017 Microsoft Corporation
        Express Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 15063:
```

**Comment by gordthompson** [comment]
According to

http://www.freetds.org/userguide/domains.htm

>  FreeTDS does not currently implement support for Named Pipe-based SQL connections

**Comment by thorstenkampe** [comment]
Thanks for the explanation - closing ticket...

**Comment by marceloavf** [comment]
Found any solution for this @thorstenkampe ?
