### ISSUE TITLE
Azure with SSL timing out

### ISSUE THREAD

**Issue by allanice001** [pymssql/pymssql#505]
Hi all,

Anyone having issues with azure and their ssl protocol timing out after about 25 - 30 minutes?
This causes the database connection to drop.

I'm trying to find a mechanism (at this time im thinking something as simple as a port ping from within the driver) to prevent the connection from dropping.

Any ideas on how something like this would be implemented in pymssql?

**Comment by rsyring** [comment]
Unless you think this is a bug in pymssql, please use the mailing list for such questions:

https://groups.google.com/forum/#!forum/pymssql

You are also likely to get a faster response there.  :)

FWIW, SQLAlchemy (and other ORM libraries) often use a connection pool type interface.  SQLAlchemy also resently added the ability to detect when connections have dropped before turning the connection from the pool: http://docs.sqlalchemy.org/en/latest/core/pooling.html#pool-disconnects-pessimistic
