### ISSUE TITLE
1 of 10 Request - Python 2.7 With VirtualEnv

### ISSUE THREAD

**Issue by iamnaveenkumar** [pymssql/pymssql#506]
Hi Team.

We are using PYMSSQL for one of our project but it is not working properly in the VirtualEnv of python 2.7. we are facing problem where 1 of 10 request are going through. Other we are getting the below error. 
**(18456, 'DB-Lib error message 20018, severity 14:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (<<ServerName>>:1433)\n')**

can you please guide us on this?

**Comment by rsyring** [comment]
It sounds to me like you having network stability problems between your python code and the DB.  More info: 

http://pymssql.org/en/stable/faq.html#cannot-connect-to-sql-server

Please use the forum for questions like this that don't demonstrate a bug or feature request with pymssql.  Thanks.  https://groups.google.com/forum/#!forum/pymssql
