### ISSUE TITLE
issue connecting azure mssql using pymyssql

### ISSUE THREAD

**Issue by Set4now** [pymssql/pymssql#507]
[I am using sqlalchemy which again use pymssql to connect to DB.
This string works  with Mssql servers with aws(rds),vms 
but not with azure sql servers.

dburl="mssql+pymssql://criuser:Password0@testservercri.database.windows.net/testdbcri"
ERROR:- 
pymssql.OperationalError: (20002, 'DB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (40.68.37.158:1433)\n')

ubuntu :- 16.04
SQLAlchemy==1.1.14
pymssql==2.1.1 ( tried with 2.2 as well)
freetds-0.95
cat /etc/freetds/freetds.conf
[global]
        # TDS protocol version
        tds version = 7.1
        port = 1433
I checked with tsql as well for manual connection
It works as expected after freetds setup. But pymssql doesnt work .
After enabling the debug mode of tds, this is what am getting..
iconv.c:328:tds_iconv_open(0x26d7e10, UTF-8)
iconv.c:346:setting up conversions for client charset "UTF-8"
iconv.c:348:preparing iconv for "UTF-8" <-> "UCS-2LE" conversion
iconv.c:395:preparing iconv for "ISO-8859-1" <-> "UCS-2LE" conversion
iconv.c:400:tds_iconv_open: done
net.c:202:Connecting to 40.68.37.158 port 1433 (TDS version 7.1)
net.c:275:tds_open_socket: connect(2) returned "Operation now in progress"
net.c:314:tds_open_socket() succeeded
packet.c:740:Sending packet
0000 12 01 00 34 00 00 00 00-00 00 15 00 06 01 00 1b |...4.... ........|
0010 00 01 02 00 1c 00 0c 03-00 28 00 04 ff 08 00 01 |........ .(......|
0020 55 00 00 02 4d 53 53 51-4c 53 65 72 76 65 72 00 |U...MSSQ LServer.|
0030 39 b0 00 00            -                        |9...|

packet.c:639:Received packet
0000 04 01 00 25 00 00 01 00-00 00 15 00 06 01 00 1b |...%.... ........|
0010 00 01 02 00 1c 00 01 03-00 1d 00 00 ff 0c 00 01 |........ ........|
0020 f4 00 00 03 00         -                        |.....|

login.c:1106:detected flag 3
login.c:472:login packet rejected
query.c:3772:tds_disconnect()
util.c:165:Changed query state from IDLE to DEAD
util.c:322:tdserror(0x27df540, 0x26d7e10, 20002, 0)
dblib.c:7925:dbperror(0x27f83c0, 20002, 0)
dblib.c:7993:dbperror: Calling dblib_err_handler with msgno = 20002; msg->msgtext = "Adaptive Server connection failed (40.68.37.158:1433)"
dblib.c:8015:dbperror: dblib_err_handler for msgno = 20002; msg->msgtext = "Adaptive Server connection failed (40.68.37.158:1433)" -- returns 2 (INT_CANCEL)
util.c:352:tdserror: client library returned TDS_INT_CANCEL(2)
util.c:375:tdserror: returning TDS_INT_CANCEL(2)
dblib.c:1241:tdsdbopen: tds_connect_and_login failed for "40.68.37.158:1433"!
dblib.c:1463:dbclose(0x27f83c0)
dblib.c:243:dblib_del_connection(0x7f3a2affca00, 0x26d7e10)
mem.c:648:tds_free_all_results()
dblib.c:290:dblib_release_tds_ctx(1)
dblib.c:5873:dbfreebuf(0x27f83c0)
dblib.c:743:dbloginfree(0x277c170)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pymssql.pyx", line 641, in pymssql.connect (pymssql.c:10824)
pymssql.OperationalError: (20002, 'DB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (40.68.37.158:1433)\n')

Not sure what am i doing wrong.

**Comment by Set4now** [comment]
export TDSDUMP=stdout
pymssql.connect(server="name",port=1433,user="criuser@testservercri",password="Password0",database="testdbcri"
Then the above error.

**Comment by cyberatz** [comment]
I'm having issues on a newly patched SQL 2016 version too. Either receiving the above error or a timeout error. 
SQL Version: Microsoft SQL Server 2016 (SP1) (KB3182545) - 13.0.4001.0 (X64)   Oct 28 2016 18:17:30   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Datacenter 6.3 <X64> (Build 14393: ) 

Additional error message:
OperationalError: 20004, 'DB-Lib error message 20004, severity 9:\nRead from the server failed\nNet-Lib error during Operation timed out (60)\n'

Program exited after 27.36 seconds. So it's not reaching any timeouts yet. 

When looking at a network packet dump, it seems the python script send a reset packet to disconnect the session as the results are ready.

**Comment by rsyring** [comment]
These are usually configuration issues either with pymssql or the network or SQL server.  Please use the forums for technical support: https://groups.google.com/forum/#!forum/pymssql
