### ISSUE TITLE
Maintainers Needed - Apply Within

### ISSUE THREAD

**Issue by rsyring** [pymssql/pymssql#516]
@damoxc @ramiro: Obviously it would help pymssql if we had maintainers who had more time for the project.  I propose leaving this issue open as a signal to others that we have need and are willing to give others commit privileges.  I also believe we could contact a few of the people who submitted PRs recently to see if they are interested in helping more.  Any objections?

To others: if you have interest and time to help pymssql progress, please leave a message here.

**Comment by yuvalbar** [comment]
@rsyring I myself don't have a lot of free time to maintain a public repository but am willing to try and help close / merge some of the open issues. What are your expectations of maintainers?

**Comment by rsyring** [comment]
@yuvalbar Understood, I think we are all in that same boat.  At this point, I have no expectations really.  Outside of occasional issue updates and posts to the mailing list, I've not been a meaningful contributor to the project for years.  I simply know it needs help, and I want to let interested parties know that.  Outside of making sure obviously malicious code is not being merged and the test suite is maintained and is passing before we cut releases, I'm not sure I'm in a position to insist on anything really.

From a priorities perspective, It would be nice to get some of the major PRs reviewed/accepted, and cut a new release with wheels for Python 3.6.  I'm sure a review of the most commented on issues in the last year would also help review where the most need is.

**Comment by yuvalbar** [comment]
@rsyring I'm willing to give it a try and see if we can make it work.

**Comment by rsyring** [comment]
@yuvalbar thanks for making the effort.  I've given you commit access.

**Comment by twiggy** [comment]
thanks @yuvalbar we really appreciate the effort of this project where i work. I'm going to see if I can find a little time to put a commit together to bundle up a decent version of freetds and get around the DB VER 80 issues. Compiling freetds and cython issues make the build a little unstable and complicated. I don't think i deserve nor want commit privileges though.

**Comment by jpgimenez** [comment]
@rsyring I just created a PR #522 to update windows wheel to use the latest stable FreeTDS, at least I can continue contributing with maintaining the wheels, I'm working on a project that doesn't allow the installation of source packages, so keeping binaries up to date is important.

**Comment by rsyring** [comment]
@jpgimenez Sorry for the delay.  I just gave you commit access.  Feel free to make reasonable changes to master.  Please ping me on something if it seems iffy for any reason.

Thanks for your willingness to help.

**Comment by jpgimenez** [comment]
thank you @rsyring!

**Comment by zzzeek** [comment]
hey @rsying -

starting to hit problems here like #520 that are holding up my CI process, I think for the moment I am going to need to drop pymssql from SQLAlchemy CI as pymssql releases seem to be stalled for six months.

**Comment by rsyring** [comment]
@zzzeek Ok, thanks for the heads up.  If that is the case, I might be able to get some of these things moving along.  I'll email you privately for some more info and potential discussion.

**Comment by rsyring** [comment]
@zzzeek over the next two weeks, @guruofgentoo will put 10-20 hours into evaluating the state of pymssql and will put a milestone together to at least cleanup the build issues and get a release out that works with the newest FreeTDS and Python versions.  We'll then need to get a budget approved for the work needed to actually accomplish those tasks.  But, I hope to be able to finish them all by the end of August.

**Comment by rsyring** [comment]
@AlexHagerman so glad you've been able to jump in and help us move pymssql down the road.  I'm seeing the issues and PR comments coming through.  Keep up the good work!

**Comment by echen805** [comment]
I'd like to help get PRs pushed through. 

I don't think I deserve commit privileges yet so I'll work on some PRs and fix up any tests that are failing until I get a better understanding of the code base. 

Are there any documentation on formatting for PRs? I did not see any on the site.

**Comment by AlexHagerman** [comment]
@echen805 I don't think there is any specific formatting required for PRs at this time as long as they provide enough detail to understand the purpose of the PR. That said one thing I will point out is the `2.1.x` branch and `master` diverged, and I'm not quite sure why. Maybe the intent was to create a `3.x` release or there was another reason, but when reviewing PRs you will need to keep that context in mind and make sure things go against the right branch. Realistically I think getting that figured out would be a big boon to knowing what issues should stay open, which version people are opening issues against, PR review etc.

**Comment by rsyring** [comment]
I'm happy to see that get fixed and we have an issue open for it: https://github.com/pymssql/pymssql/issues/569

**Comment by echen805** [comment]
Great, thanks for the responses @AlexHagerman  and @rsyring! 

I see that master is the branch to use for active development now. I can setup my environment tonight and start working on the PRs to be updated against master.

**Comment by rsyring** [comment]
This project is being discontinued.  See #668 for details.
