### ISSUE TITLE
pymssql-2.1.3 ‘DBVERSION_80’ undeclared (first use in this function); did you mean ‘DBVERSION_70’?

### ISSUE THREAD

**Issue by benjaminweb** [pymssql/pymssql#520]
`pip3 install pymssql
`
```
Building wheels for collected packages: pymssql
  Running setup.py bdist_wheel for pymssql ... error
  Complete output from command /sites/angebot.clasen-co.com/.venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-knuguc6l/pymssql/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpoyh0piogpip-wheel- --python-tag cp36:
  setup.py: platform.system() => 'Linux'
  setup.py: platform.architecture() => ('64bit', '')
  setup.py: platform.linux_distribution() => ('arch', '', '')
  setup.py: platform.libc_ver() => ('glibc', '2.3.4')
  setup.py: Not using bundled FreeTDS
  setup.py: include_dirs = ['/usr/local/include']
  setup.py: library_dirs = ['/usr/local/lib']
  running bdist_wheel
  running build
  running build_ext
  building '_mssql' extension
  creating build
  creating build/temp.linux-x86_64-3.6
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fPIC -I/usr/local/include -I/usr/include/python3.6m -c _mssql.c -o build/temp.linux-x86_64-3.6/_mssql.o -DMSDBLIB
  _mssql.c: In function ‘__pyx_f_6_mssql__tds_ver_str_to_constant’:
  _mssql.c:18814:15: error: ‘DBVERSION_80’ undeclared (first use in this function); did you mean ‘DBVERSION_70’?
       __pyx_r = DBVERSION_80;
                 ^~~~~~~~~~~~
                 DBVERSION_70
  _mssql.c:18814:15: note: each undeclared identifier is reported only once for each function it appears in
  error: command 'gcc' failed with exit status 1
```

**Comment by papachoco** [comment]
Same issue on MacOS (freetds installed in macports)

**Comment by asafo** [comment]
Same issue on Alpine Linux

**Comment by KptainBiwouak** [comment]
In order to solve this issue by using pymssql 2.1.3, I have
modified header of /usr/include/sybdb.h belonging to the libsybdb-devel
package (Cygwin) by adding line below:
#define DBVERSION_80 DBVERSION_71

It is an other way to solve temporarily this issue without waiting for next
release of pymssql 2.1.4
I have documented this fix from pymssql forum if it can help

Best Regards,

​

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by benjaminweb** [comment]
If I install the git version via pip3 install git+
https://github.com/pymssql/pymssql, I don't run into the issue.
On Tue, Dec 19, 2017, at 21:54, KptainBiwouak wrote:
> In order to solve this issue by using pymssql 2.1.3, I have
>  modified header of /usr/include/sybdb.h belonging to the libsybdb-
>  devel>  package (Cygwin) by adding line below:
>  #define DBVERSION_80 DBVERSION_71
> 
>  It is an other way to solve temporarily this issue without waiting
>  for next>  release of pymssql 2.1.4
>  I have documented this fix from pymssql forum if it can help
> 
>  Best Regards,
> 
> 
> 
>  <https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>>  Garanti
>  sans virus. www.avast.com
>  <https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>>  <#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
> 
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/pymssql/pymssql/issues/520#issuecomment-352883344

**Comment by doruchiulan** [comment]
how can i temporary install this on Mac ? I don't have /usr/include/sysdb.h, is there anything else i can do?

**Comment by benjaminweb** [comment]
Do you mean `pip3 install git+https://github.com/pymssql/pymssql` ?

**Comment by doruchiulan** [comment]
nevermind, I ended up using pyodbc

**Comment by drook** [comment]
Same stuff on FreeBSD with FreeTDS 1.0.x from ports.

Workaround: edit DBVERSION_80 in the mentioned file to DBVERSION_74.

````buildlog
[root@dev:/tmp/pymssql-2.1.3]# /usr/local/python-3.6.3/bin/python3 setup.py install
setup.py: platform.system() => 'FreeBSD'
setup.py: platform.architecture() => ('64bit', 'ELF')
setup.py: platform.libc_ver() => ('libc', '7')
setup.py: Detected FreeBSD.
    For FreeBSD, you can install FreeTDS with FreeBSD Ports or by downloading
    and compiling it yourself.
            
setup.py: Not using bundled FreeTDS
setup.py: include_dirs = ['/usr/local/include']
setup.py: library_dirs = ['/usr/local/lib']
running install
running bdist_egg
running egg_info
creating pymssql.egg-info
writing pymssql.egg-info/PKG-INFO
writing dependency_links to pymssql.egg-info/dependency_links.txt
writing top-level names to pymssql.egg-info/top_level.txt
writing manifest file 'pymssql.egg-info/SOURCES.txt'
reading manifest file 'pymssql.egg-info/SOURCES.txt'
writing manifest file 'pymssql.egg-info/SOURCES.txt'
installing library code to build/bdist.freebsd-11.1-RELEASE-amd64/egg
running install_lib
running build_ext
cythoning _mssql.pyx to _mssql.c
warning: _mssql.pyx:143:4: Exception already a builtin Cython type
building '_mssql' extension
creating build
creating build/temp.freebsd-11.1-RELEASE-amd64-3.6
cc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -I/usr/local/python-3.6.3/include/python3.6m -c _mssql.c -o build/temp.freebsd-11.1-RELEASE-amd64-3.6/_mssql.o -DMSDBLIB
_mssql.c:21223:15: error: use of undeclared identifier 'DBVERSION_80'
    __pyx_r = DBVERSION_80;
              ^
1 error generated.
error: command 'cc' failed with exit status 1
````

**Comment by Warfront1** [comment]
Thanks @drook 
For those on alpine having this issue
`sed  '/DBVERSION_74      8/a #define DBVERSION_80 DBVERSION_71' /usr/include/sybdb.h -i.bkp`

And obviously in your docker file:
`RUN sed  '/DBVERSION_74      8/a #define DBVERSION_80 DBVERSION_71' /usr/include/sybdb.h -i.bkp`

**Comment by cscetbon** [comment]
@Warfront1,  is it a problem in pymssql or fretds ? Cause if it's an issue in freetds, an issue should be created on the project.

**Comment by cscetbon** [comment]
Okay never mind, it's now defined in freetds version embedded in pymssql :
https://github.com/pymssql/pymssql/blob/master/freetds0.95/nix_64/include/sybdb.h#L79 

 I think we can close that issue now @benjaminweb ?

**Comment by benjaminweb** [comment]
I would like to test it first. I can give you a feedback no earlier than next week.

**Comment by benjaminweb** [comment]
I can confirm that it works in production without any hiccup.
