### ISSUE TITLE
pymssql-2.1.3-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by dreamsline** [pymssql/pymssql#523]
python version:3.6.2
Please tell me how to solve the problem?

**Comment by jpgimenez** [comment]
basically means that you are trying to install a wheel for one platform on another one... what OS/arch are you using?

**Comment by rsyring** [comment]
Please use the forum for technical support: https://groups.google.com/forum/#!forum/pymssql
