### ISSUE TITLE
Release 2.1.4

### ISSUE THREAD

**Issue by rsyring** [pymssql/pymssql#528]
@jpgimenez has created a milestone to track the 2.1.4 release: https://github.com/pymssql/pymssql/milestone/9

@jpgimenez regarding your comment on #527, I don't think we need pypy support for this milestone.  I'd much rather get the bug fixes into 2.1.4 and see pypy support left for consideration in 2.2.0 (or higher).  Seems hard to take on commitment to support another platform when we struggle to keep updates going for the currently-supported platforms.

**Comment by jpgimenez** [comment]
just moved pypy support to milestone 2.2.0

**Comment by jpgimenez** [comment]
@rsyring whats common practice about preparing 2.1.4 release? We should merge master to stable-2.1.x or just pick the related commits?

**Comment by rsyring** [comment]
Is master releasable?  If so, just tag it.  If not, creating a release
branch makes sense to me.

Randy Syring (sent from my mobile)
Chief Executive Developer
Direct: 502-276-0459
Office: 812-285-8766

Level 12 - Software that Works

**Comment by kparaju** [comment]
Any updates?

**Comment by kparaju** [comment]
Are we going to get this soon? If not, I can create a MR against the stable-2.1.x branch with https://github.com/pymssql/pymssql/pull/527 and https://github.com/pymssql/pymssql/pull/524 (those are the two changes AFAIK)

Someone will still have to push it to pypi though.

**Comment by rsyring** [comment]
@kparaju feel free.

**Comment by jpgimenez** [comment]
Finally I get the time to merge branches update-windows-wheels and update-linux-wheels on stable-2.1.x now 2.1.4 could be tagged from there.

**Comment by jpgimenez** [comment]
Builds are passing for linux and windows on stable-2.1.x branch,
https://travis-ci.org/pymssql/pymssql/jobs/350904511
https://ci.appveyor.com/project/level12/pymssql/build/257

I think than now should be safe to tag 2.1.4 from that branch.

**Comment by rsyring** [comment]
Can we merge to master first?  Or does master have additional changes on it?

Randy Syring (sent from my mobile)
Chief Executive Developer
Direct: 502-276-0459
Office: 812-285-8766

Level 12 - Software that Works

**Comment by jpgimenez** [comment]
just created a pre-release https://github.com/pymssql/pymssql/releases/tag/v2.1.4.dev1
if everything works as expected I'll merge to master and create the final release

**Comment by rsyring** [comment]
@jpgimenez just wanted to make sure you saw that the AppVeyor builds are failing: 

https://ci.appveyor.com/project/level12/pymssql/build/267

**Comment by jpgimenez** [comment]
yes, its failing when upload packages to test pypi, I'll try to fix that later today...

**Comment by rsyring** [comment]
Just FYI, @guruofgentoo did some testing for us on a large app that uses pymssql and we had some breaking changes between 2.1.3 and 2.1.4.dev5.  We aren't sure yet if those were from pymssql or freetds, but we should not release 2.1.4 until we know more.

**Comment by nehaljwani** [comment]
Ping :sweat_smile: 

Is there an ETA on this? I am waiting for this as it would be the first release to officially support python 3.6

**Comment by rsyring** [comment]
@nehaljwani No ETA, sorry.

**Comment by geofft** [comment]
Hey - I'm working on updating the pymssql Debian package, because and Debian testing has picked up freetds 1.00 and now pymssql 2.1.3 doesn't build. Are the concerns @rsyring and @guruofgentoo had resolved now? I'd prefer to package a 2.1.4 release, but I'm also fine getting the freetds compatibility patches - as long as we're not expecting them to be broken.

**Comment by rsyring** [comment]
@geofft How much time do you have before you have to make your updates?  We hope to be able to pull things together and get a release out the door by the end of July.  But until @guruofgentoo and his team can get that time in, I don't really know what the status of the various branches/releases are.

**Comment by geofft** [comment]
End of July should be more than fine - the next big deadline is the Ubuntu 18.10 import freeze on August 23, since Ubuntu gets its package from Debian. (The next Debian release itself is freezing early 2019 so there's plenty of time there.)

If there are things I can do to help with testing, please let me know! Is there a bug report for whatever you're seeing that's making you not comfortable releasing?

**Comment by rsyring** [comment]
@AlexHagerman Great, thanks.  Could you also:

1. Get the RC release up on pypi.  Make sure it's uploaded so that the `--pre` flag is required when using pip to get the RC release (I'm not exactly sure what the mechanism is for that when doing the release, maybe it's discerned from "rc" being in the version?).
2. Announce the RC release on the mailing list: https://groups.google.com/forum/#!forum/pymssql

**Comment by rsyring** [comment]
@zzzeek I'm sure you are busy.  If you get time and can run this RC through the SQLAlchemy test suite, that would be great.

**Comment by AlexHagerman** [comment]
@rsyring will do. It will probably be Monday or Tuesday when I'm able to complete the PyPI upload.

**Comment by zzzeek** [comment]
hi @rsyring easiest for me if it's what "pip install" will download, I can just re-enable it.

**Comment by AlexHagerman** [comment]
RC1 is now available via `pip` using the  `--pre` flag https://pypi.org/project/pymssql/#history.

**Comment by rsyring** [comment]
@zzzeek is this sufficient for you to re-enable your tests?  I'd like to know we haven't made any regressions in the SA test suite before we release.

**Comment by zzzeek** [comment]
@rsyring I can try running them locally but there's not an easy way for me to get that --pre flag on to my CI environment.

**Comment by rsyring** [comment]
@AlexHagerman have you tried running SA tests using what we already have?  See #49.

**Comment by zzzeek** [comment]
@rsyring  my test suite passes locally with this version.  Although I am not recalling what the original problem was that made me remove this.  was is that the current release won't build or something like that?  the current non-pre release doesn't build for me it claims cython is missing (not listed as a dependency? not sure).

**Comment by AlexHagerman** [comment]
@rsyring I haven't ran the test locally yet. I added the ticket to the current milestone and will work on making it part of CI.

**Comment by AlexHagerman** [comment]
2.1.4 is now live on PyPi.

**Comment by AlexHagerman** [comment]
@zzzeek anything else you need before I close this issue?

**Comment by nehaljwani** [comment]
Thank you guys for all the effort for this release.

This version is also available as a conda package now !

**Comment by AlexHagerman** [comment]
@nehaljwani thanks that's awesome. Do you have a script or process on what you did for that so we can look into adding that to our CI/CD pipeline?

**Comment by nehaljwani** [comment]
The recipe is here:
https://github.com/AnacondaRecipes/pymssql-feedstock

**Comment by zzzeek** [comment]
ive re-enabled pymssql up on my CI and all tests passed.   I dont recall what the original issue was but nothing is broke now so thanks!

**Comment by rlshuhart** [comment]
Great job @AlexHagerman! As a user, I would like to thank you very much for taking this project on and creating this release. Thanks to everyone else that contributed as well. Hard to believe it had been two years since the last release!

**Comment by ramiro** [comment]
Thanks and congratulations for the release!

It would be great to have an idea of the time @AlexHagerman invested to prepare a release like this. I'm sure it's a massive effort.

@rlshuhart If we can have a figure of the time (in other words money) Alex an Randy had to invest to get 2.1.4 out the door, then perhaps you could have an answerto to why there hasn't been a release in two years.  Then perhaps you could either:

* Offer funding for future releases
* Volunteer yourself to become a contributor (see #516)  and drive the next release cycle?

**Comment by rlshuhart** [comment]
@ramiro 
My apologies, I did not fully consider how mentioning about it being two years could be interpreted. Lesson learned. 

This past year my eyes were opened to how much burn-out there is in open-source projects from Brett Cannon's keynote at the last PyCon. Because I'm not always able to able to contribute to a project that I use, whether that be I lack time or the skills, the least I can do is thank those that do, which was what I was trying to accomplish. The last thing that I wanted to accomplish was to be discouraging in any way.
