### ISSUE TITLE
Error while calling connect(): ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by jenner** [pymssql/pymssql#529]
Hi there,

we're getting an error (sporadically) when calling pymssql.connect():

```
File "pymssql.pyx", line 635, in pymssql.connect (pymssql.c:10734)
File "_mssql.pyx", line 1902, in _mssql.connect (_mssql.c:21821)
File "_mssql.pyx", line 636, in _mssql.MSSQLConnection.__init__ (_mssql.c:6558)
ValueError: list.remove(x): x not in list
```
It seems to be triggered by a failed connection attempt to the DB. Any suggestions about how we could mitigate the problem?

OS: Windows 2012R2 Server
python: 3.4.4
pymssql: 2.13
sql server: 2014

Regards
Igor

**Comment by zhanghed** [comment]
I AM ALSO exactly the same problem excuse me to solve??

**Comment by termim** [comment]
Do you still have this problem?
