### ISSUE TITLE
Inconsistent connect function in Docs

### ISSUE THREAD

**Issue by andrewrau** [pymssql/pymssql#537]
The docs is inconsistent for the pymssql.connect function.

On this page, it doesn't list all the parameters available to pass in (e.g. port, autocommit)
http://pymssql.org/en/stable/ref/pymssql.html#connection-class

But it is listed on this page
http://pymssql.org/en/stable/ref/pymssql.html#functions

**Comment by AlexHagerman** [comment]
@andrewrau this has been updated in the 2.1.x stable docs. We are working on an RC and this will make it into RTD with the next full release.
