### ISSUE TITLE
When pymssql.connect() with charset="cp949" on Windows, crash occurred.

### ISSUE THREAD

**Issue by pymssql-issue-migrator** [pymssql/pymssql#54]
_From [marun...@gmail.com](https://code.google.com/u/106034399125629555530/) on April 26, 2011 22:50:45_

What steps will reproduce the problem? 1. To refer issue 48 , build pymssql for windows.
2. try to connect mssql server as below script.
import pymssql
conn = pymssql.connect(server="192.168.123.xxx",
                user="id", password="pw", database="db", charset="cp949")
cur = conn.cursor()
cur.execute("select \* from mytable")
for row in cur:
    print row What is the expected output? What do you see instead? It is expected that contents of table is printed.
But, Python crash occurred. What version of the product are you using? On what operating system? revision ab786211a2cc , Cython 0.14.1, Python 2.6.6, Windows 7 Please provide any additional information below. Above code work well with pymssql 1.0.2.
I try to trace the crash point and find that crash occurred at 491 line in _mssql.pyx.

```
    # Set the login timeout
    dbsetlogintime(login_timeout)

    # Connect to the server
    self.dbproc = dbopen(login, server)  ### << crash here.

    # Frees the login record, can be called immediately after dbopen.
    dbloginfree(login)
```

Below error message is displayed with charset="utf-8".

+++ _mssql.MSSQLConnection.__cinit__()
+++ _mssql.MSSQLConnection.__init__()

**\* err_handler(dbproc = 025D30D8, severity = 9,  dberr = 20017, oserr = 0, dberrstr = 'Unexpected EOF from the server',  oserrstr = 'No error'); DBDEAD(dbproc) = 0
**\* previous max severity = 0

**\* err_handler(dbproc = 025D30D8, severity = 9,  dberr = 20002, oserr = 0, dberrstr = 'Adaptive Server connection failed',  oserrstr = 'No error'); DBDEAD(dbproc) = 1
**\* previous max severity = 9

+++ _mssql.MSSQLConnection.__init__() -> dbopen() returned NULL
+++ _mssql.MSSQLConnection.__dealloc__()
+++ _mssql.MSSQLConnection.close()
Traceback (most recent call last):
  File "testpymssql.py", line 3, in <module>
    user="id", password="pw", database="db", charset="utf-8")
  File "pymssql.pyx", line 516, in pymssql.connect (pymssql.c:6644)
    raise OperationalError(e[0])
pymssql.OperationalError: (20017, '\xc4DB-Lib error message 20017, severity 9:\nUnexpected EOF from the server\nDB-Lib error message 20002, severity 9:\nAdaptive Server connection failed\n')

_Original issue: http://code.google.com/p/pymssql/issues/detail?id=50_

**Comment by M0rtalW0mbat** [comment]
Somebody report this issue to the FreeTDS project?
