### ISSUE TITLE
UnicodeDecodeError with utf8 characters

### ISSUE THREAD

**Issue by saeedesmaili** [pymssql/pymssql#542]
I'm using pymssql to get some data from the SQL server and store the results in a pandas dataframe. When I try to select a column that contains utf-8 (Farsi) characters, I get this error:

    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 0: invalid continuation byte

But everything is fine with other columns in the database.

This is my code snippet and I'm running the code with python3.6:

```
import pymssql
import pandas as pd

conn = pymssql.connect(server, username, password, database)
cursor = conn.cursor(as_dict=True)

cursor.execute("""
 SELECT id, title
 FROM products
""")


df = pd.DataFrame(columns=['id', 'title'])

for row in cursor:
    df = df.append(row, ignore_index=True)


conn.close()
```

**Comment by AlexHagerman** [comment]
Which version of SQL Server are you running? Can you try the below:

```
SELECT c.name,  c.collation_name
FROM SYS.COLUMNS c
JOIN SYS.TABLES t ON t.object_id = c.object_id
WHERE t.name = '<your_table_name>'
```

And post the result for your table?

**Comment by AlexHagerman** [comment]
Closing with no response for 14+ days.
