### ISSUE TITLE
clean up and document Windows builds

### ISSUE THREAD

**Issue by guruofgentoo** [pymssql/pymssql#544]
Appveyor is building Windows wheels, but the documented build process for doing this manually is not working. iconv is needed, as well as some TDS utils.

Existing docs mention mingw as an alternative compiler on this. I'm not sure if the build is cleaner there, but AppVeyor is using MSVC to compile for the Windows wheels, so that should likely be our primary target.

#539, #536 are related.

**Comment by AlexHagerman** [comment]
Documentation updated.
