### ISSUE TITLE
Add Python 3.7 to build pipelines

### ISSUE THREAD

**Issue by AlexHagerman** [pymssql/pymssql#558]
We should probably wait until the Travis CI and Appveyor builds are successfully building for milestone [10](https://github.com/pymssql/pymssql/milestone/10) with the current supported Python versions (pending 3.3 see https://github.com/pymssql/pymssql/issues/557), but once that's all working we should go ahead and add Python 3.7 to the build since it released on 6/27/2018.

**Comment by AlexHagerman** [comment]
I'm going to rollback 3.7 from travis on Monday. Build is breaking, but not because of 3.7 itself, but because of travis support. https://github.com/travis-ci/travis-ci/issues/9815

I don't think we want to spend a lot of time on this, instead rollback for the milestone to 3.6 and then 3.7 seems to be fine in circleci since we are using docker images on 16.04.

**Comment by sverrejb** [comment]
Am I reading this right? Should pymssql currently be working with python 3.7? Updating our docker image to use the Python 3.7 image as base broke our build.

`Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-2aemta0f/PyYAML/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-6twd_xvk/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-2aemta0f/PyYAML/`

**Comment by AlexHagerman** [comment]
@sverrejb thanks for the report. Was this with the 2.1.x release?

**Comment by sverrejb** [comment]
This was with pymssql 2.1.3 and the official python 3.7 image (this I guess: https://github.com/docker-library/python/blob/master/3.7/stretch/Dockerfile).

**Comment by AlexHagerman** [comment]
3.7 failed in AppVeyor build. Removing it from AV until we get 2.1.4 released and then I'll dig into why 3.7 is failing.

https://ci.appveyor.com/project/level12/pymssql/build/job/dc0599huah964d52

**Comment by AlexHagerman** [comment]
3.7 is now part of the AppVeyor and Circle build process.
