### ISSUE TITLE
Removing non-active maintainers

### ISSUE THREAD

**Issue by rsyring** [pymssql/pymssql#560]
@damoxc, @jpgimenez, @msabramo, @ramiro, @yuvalbar:

Greetings gents!  As part of our effort to start putting more time into pymssql, we are taking a look at the project as a whole and making sure project access on GitHub and PyPI is limited to users that need it.

Please let me know if you believe you will have time to contribute to pymssql project in the next 6 months or so.  If not, then I'd like to remove your access from the project.

Not trying to be heavy handed at all, which is why I'm creating this issue and asking for feedback.  I'm just trying to operate on the [Principle of Least Privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege).

If I don't hear back from any of you in the next couple weeks, I'll assume that is confirmation that your access can be removed.

If you are removed and any of you have contributions you want to make in the future, we'll be happy to add you back to the project as needed.

Thanks.

**Comment by msabramo** [comment]
That’s fine with me too.

**Comment by rsyring** [comment]
Thanks  guys for your input.  Yes, I was finally able to secure some funding to move pymssql forward and I'm really glad about that.  I obviously haven't had the volunteer time to contribute significantly either.  Thank you all for your contributions over the years.
