### ISSUE TITLE
Migrate 2.1.x to master

### ISSUE THREAD

**Issue by AlexHagerman** [pymssql/pymssql#569]
Currently the default branch is a `2.2.x` build. That branch should be checked out and moved into a branch `2.2.x` development and `2.1.x` should be checked in as the `master` branch where stable and active development is happening. This will make it easier for those looking to contribute, GitHub tooling (for instance keywords) will work better, and those visiting the repo looking for information will see stable/master/default immediately.

**Comment by rsyring** [comment]
@AlexHagerman just want to be sure that by "default" branch you mean a branch named `master`.  

Thanks.

**Comment by AlexHagerman** [comment]
Updated, I did mean `master`, but need to make sure that's clear.

**Comment by AlexHagerman** [comment]
Tagging based on top contributors to the project. It looks like `master` and `2.1.x` branched a while back, but I'm trying to find some design discussion on why, or what features created the `2.1` to `2.2` bump. Also it looks like pypi stayed on the `2.1` and I don't see a `2.2` release that happened on GitHub or pypi. Based on that I have a couple questions I'm hoping we can answer to determine what next steps the project should take.

- What is the difference between `2.1` and `2.2`?
- Is there anything in `2.2` that should be back ported to `2.1`?
- Should `2.1` be active, or should we consider it to be in bug fix mode only and move forward with `2.2`? 

Appreciate your help with this. If I have missed something in issues, the mailing list, etc please let me know. 

@rsyring @ramiro @damoxc @msabramo @jpgimenez @bladams @skinowski

**Comment by rsyring** [comment]
@AlexHagerman it looks to me like this started due to some work around TDS version numbering started by @ramiro:

![image](https://user-images.githubusercontent.com/109467/55110458-7214ad00-50ae-11e9-84b7-a1585f6cc3cb.png)

Red is the stable branch, black is master.

**Comment by rsyring** [comment]
Actually, looking further, everything in master got merged into the stable branch:
![image](https://user-images.githubusercontent.com/109467/55110966-ac327e80-50af-11e9-8637-0f84624c9e56.png)

I was able to fast-forward merge the 2.1 stable branch into master.  Master is now the only branch we need to worry about and represents current active development.

**Comment by AlexHagerman** [comment]
Thanks @rsyring I just found these notes in the Changelog around `2.2` also

```
Version 2.2.0 - To be released
==============================

General
-------

- Stop using 7.1 as default value for the TDS protocol version used in connections.

  This is a backward incompatible change and affects connections using both
  `pymssql` and `_mssql`.

  Now you need to specify a TDS protocol version explicitly by using any of
  the supported mechanisms (in descending order of precedence):

  * Using the ``tds_version`` paramenter of ``pymssql.connect()`` and
    ``_mssql.connect()``
  * A ``TDSVER`` enviromnent variable (see FreeTDS documentation)
  * A ``freetds.conf`` file (see FreeTDS documentation)

- Drop support for versions of FreeTDS older than 0.91.
- Accept 7.3 as TDS protocol version when establishing a connection.

Features
--------

- Support for new in SQL Server 2008 ``DATE``, ``TIME`` and ``DATETIME2`` data
  types (GH-156). The following conditions need to be additionally met so
  values of these column types can be returned from the database as their
  native corresponding Python data types instead of as strings:

  * Underlying FreeTDS must be 0.95 or newer.
  * TDS protocol version in use must be 7.3 or newer.

  Thanks Ed Avis for the implementation. (GH-331)

Bug fixes
---------

- Fix ``tds_version``  ``_mssql`` connection property value for TDS version.
7.1 is actually 7.1 and not 8.0.
```

https://github.com/pymssql/pymssql/blob/master/ChangeLog

**Comment by AlexHagerman** [comment]
> Actually, looking further, everything in master got merged into the stable branch:
> ![image](https://user-images.githubusercontent.com/109467/55110966-ac327e80-50af-11e9-8637-0f84624c9e56.png)
> 
> I was able to fast-forward merge the 2.1 stable branch into master. Master is now the only branch we need to worry about and represents current active development.

Hmm, based on the `Changelog` there may be a breaking change in there.
