### ISSUE TITLE
Tagged builds fail on PyPi deployment

### ISSUE THREAD

**Issue by AlexHagerman** [pymssql/pymssql#575]
Working on investigating why the 2012 builds fail to deploy in AppVeyor while 2008 succeeds. 

https://ci.appveyor.com/project/level12/pymssql/build/320

@ramiro can you verify an email for test.pypi.org so we can see if the rest of the deployment steps succeed?

```
HTTPError: 400 Client Error: User 'ramiro' does not have a verified primary email address. Please add a verified primary email before attempting to upload to PyPI. See https://test.pypi.org/help/#verified-email for more information.for more information. for url: https://test.pypi.org/legacy/
```

**Comment by AlexHagerman** [comment]
Appveyor deploys with this statement:

```
if ($env:APPVEYOR_REPO_TAG -eq "true" -or $env:APPVEYOR_REPO_TAG -eq "True") {
  If ($env:INSTANCENAME -eq "SQL2012SP1") {
    pip install twine --upgrade
    twine upload -u $env:PYPI_USERNAME -p $env:PYPI_PASSWORD --config-file dev\appveyor\pypirc -r testpypi $env:APPVEYOR_BUILD_FOLDER\dist\*.whl
  }
}
```

The `INSTANCENAME` check is why the build succeeds on '08 but fails on '12. The deployment step only happens on '12 and fails. 

https://ci.appveyor.com/project/level12/pymssql/build/322

Looking back at the build history this was already happening.

https://ci.appveyor.com/project/level12/pymssql/build/269

Need to review the twine command arguments.

**Comment by ramiro** [comment]
@AlexHagerman Done

PS: @rsyring DO you have control of the pymssql project at Read The Docs  to be able to handle the documentation deleares there, etc.?

A couple of days ago I logged in to RTD for work on an unrelated project and I saw there are theee maintainers: Marc, me and a pymssql account which weirdly enough has my avatar (possibly because at some point in he past we set mine as its email address there) 

I want to be sure @AlexHagerman has what he needs to handle the docs side of a release.

**Comment by AlexHagerman** [comment]
@ramiro thank you! 

As an update on the issue a new error has emerged in the travis deployment:

```
HTTPError: 400 Client Error: Binary wheel 'pymssql-2.1.4rc1-cp34-cp34m-linux_x86_64.whl' has an unsupported platform tag 'linux_x86_64'. for url: https://test.pypi.org/legacy/
```

**Comment by AlexHagerman** [comment]
PyPi has manylinux wheels:

https://pypi.org/project/pymssql/#files

Looking at the .travis.yml file history I don't see anything that would impact this there. I'll look at the setup.py build information next to see if something changed there that would cause the build to do something other than a manylinux wheel. @ramiro if you have any thoughts or advice I would appreciate it.

**Comment by ramiro** [comment]
@AlexHagerman According to

  https://stackoverflow.com/questions/50690526/how-to-publish-binary-python-wheels-for-linux-on-a-local-machine

you are right. PyPI is rejecting your ``linux_x86_64` tagged wheel file. 

IIRC I generated the *manylinux* wheels you see published locally using the official Python wheel tooling (which AFAIR involved docker images of centos?) and then uploaded hem manually after release.

**Comment by AlexHagerman** [comment]
@rsyring my RTD account is setup with GitHub my username is AlexHagerman.

**Comment by AlexHagerman** [comment]
@ramiro can you add me as a maintainer on https://test.pypi.org/project/pymssql/ ? Wanted to validate the pre release tag and windows/manylinux wheels there first.

**Comment by ramiro** [comment]
@AlexHagerman done!

I've added you as an "owner". Feel free to remove me if it's possible

You can add @rsyring et al once he creates his account at test.pypi.org. I tried and it seems he hasn't one yet.

**Comment by AlexHagerman** [comment]
Thanks @ramiro appreciate that. I got the manylinux_x86_x64 wheels for 2.1.4rc1 up on test.pypi.org this evening. 

From here I'll get the sdist, Windows wheels from appveyor and i686 up on test.pypi.org tomorrow or Monday and then move them to pypi.org and make the announcement. I'm also going to open a PR for the manylinux build script so we have that for future CI/CD updates.

**Comment by AlexHagerman** [comment]
Closing this issue. Build script setup for manylinux and working with test.pypi.org. Will pull artifacts for Windows from AppVeyor and will work on getting CD working with the CicleCI ticket. Will manually push the RC and release for now.
