### ISSUE TITLE
Add conda install and feedstock information to the docs

### ISSUE THREAD

**Issue by AlexHagerman** [pymssql/pymssql#593]
@nehaljwani has setup conda feedstock project making `pymssql` available via conda. We should add this to the docs.

https://github.com/AnacondaRecipes/pymssql-feedstock

**Comment by AlexHagerman** [comment]
@nehaljwani would you want us to move the feedstock into `pymssql` or do you want to maintain that in the repo you have created?

**Comment by nehaljwani** [comment]
That feedstock is a fork of https://github.com/conda-forge/pymssql-feedstock . 

In general, project owners become recipe maintainers at conda-forge and keep updating that feedstock, which publishes packages to the conda-forge channel. Whenever there is an important update, they give a heads up by either sending the Anaconda distribution team an email or by pinging them on the PR or by opening an issue at https://github.com/AnacondaRecipes/aggregate

Then the Anaconda folks fork that project and make changes ( if required ) and then publish the conda package on the defaults channel.

It would be great if you could become a recipe maintainer for the conda-forge feedstock.

**Comment by rsyring** [comment]
> It would be great if you could become a recipe maintainer for the conda-forge feedstock.

That would essentially be another platform that pymssql would be committing to support.  I think we should avoid doing that at this time.  While we currently have funding to get pymssql support pushed forward, we have typically struggled with having enough time from maintainers.
