### ISSUE TITLE
Pymssql submitted data successfully, in fact, the database has not changed

### ISSUE THREAD

**Issue by r0liang** [pymssql/pymssql#599]
Part of the code：
conn=pymssql.connect(host='AAAAAAAAAAAAAAA\\AAAAA',user='sa',password='123123',database='YZ',autocommit=True,conn_properties=None)

Autocommit has been set, and the spliced SQL code in Python can be executed directly in studio and can be used normally, but whether I use cur.execute() +autocommit or cur.execute() conn.commit, the callback shows NONE, but actually No change in the database

like this:

import	pymssql
import	sys
import	os

conn=pymssql.connect(host='AAAAAAAAAAAAAAA\\AAAAA',user='sa',password='123123',database='YZ',autocommit=False,conn_properties=None)
cur=conn.cursor()
if not cur:
	print('false')
sql='update YZ.dbo.ZSJB set QueryTime='+'\''+'111233'+'\''+'where number='+'\''+'9892412540402'+'\''
cur.execute(sql)
conn.commit()
print(sql)

and I user C# and Studio to commit the sql also can used.

**Comment by rsyring** [comment]
Given the test suite that we have in place, it's highly unlikely that pymssql is fundamentally broken in a way that it can't do a simple update query.  I'd recommend you do an insert instead for testing, it's possible your update statement just isn't matching anything.

@r0liang your post on the pymssql mailing list is the best place for a question like this.  Therefore, I'm going to close this issue.
