### ISSUE TITLE
python setup.py egg_info failure breaks package managers

### ISSUE THREAD

**Issue by josephong** [pymssql/pymssql#614]
Application dependency managers as per recommended by Python like [pipenv](https://packaging.python.org/tutorials/managing-dependencies/) may use `python setup.py egg_info` to collect dependency information ahead of time to compute the minimal set of dependencies to install before installing anything – it seems that setup.py as defined in this repository breaks that API, even on the latest 2.1.x branch? Running `python setup.py egg_info` returns errors in the root folder of the repository. 

It seems this issue doesn't exist if the wheel is present for the release for a particular system (though I may have diagnosed this incorrectly) – it's possible these dependency managers check wheels first for dependency lists.

The breakage is related to the import of Cython, which I know is a tough thing to address as per many other issues I see around here. Will this project's adherence to PEP518 fix this? I'm not sure if pip right now handles required installations or considers .toml for something like egg_info.

**Comment by hustlibraco** [comment]
Meeting same problem.  Even requirements.txt contains Cypthon and pymssql, `pip install -r requirements.txt` still fail.

**Comment by vandakiara** [comment]
Hi, I'm having the exact same problem and haven't found any workaround yet. I added Cython to requirements and I'm still getting this error. Did anyone find a workaround for this? I'm stuck in my project until I get rid of this error.

**Comment by hustlibraco** [comment]
Finally I solved this problem. First, pip install cython separately. Second, pip install pymssql. @vandakiara
