### ISSUE TITLE
N prefix

### ISSUE THREAD

**Issue by mohscorpion** [pymssql/pymssql#617]
hi 
i am using pymssql in superset and i noticed an issue in filtering result using where clause on unicode strings . i traced back issue to the SQL statement that is sent to MSSQL as it does not prefix unicode strings comparison with N as needed for unicode comparison.
is there any solution ?

**Comment by rsyring** [comment]
You may get better traction on this question at our mailing list.  Not enough details here to keep the issue open, sorry.
