### ISSUE TITLE
Finding grants/funding for pymssql development

### ISSUE THREAD

**Issue by rsyring** [pymssql/pymssql#621]
My company, Level 12, has decided to undertake an initiative to find grants or other sources of funding for pymssql development.  We have internal resources that can contribute to the funding, but they are currently inadequate to make a significant dent in the tech debt that is present in pymssql.

Our hope is that we can find someone at Microsoft who would be willing to help sponsor development of this project.  Microsoft officially supports pyodbc, but based on #477, pymssql still has a lot of value when connecting unix systems to Microsoft SQL server.

If anyone has connections at Microsoft that we might be able to use and/or any other large corporations that use pymssql that might consider helping to fund development, please leave comments here or contact me directly (email in GitHub profile).

No one on my team has ever tried to raise support for an OSS project before.  So if you have any suggestions, please feel free to leave them here as well.

**Comment by rsyring** [comment]
I've not had any real luck in finding people who can help with this.  The response I got from one person inside Microsoft was:

* They can't justify extending support past PyODBC right now.  They also have a tendency to only sponsor projects fiscally that they are also directly involved in.
* A compelling argument for them looks like “I’m a customer who can’t use your services because of X”, and this person just didn't see that situation happening from the links I could provide to GitHub issues.
* From their perspective, it mostly looks like like people who aren’t yet prepared to switch libraries, which they understand, but is not compelling for them.
* If we can provide a write up of case studies that we think *are* more compelling, my contact would be happy to give it another go.

**Comment by zzzeek** [comment]
took a look again at #477.  Here's the thing.   PyODBC has gotten a lot better thanks to the MS ODBC drivers.       I noticed on that issue it was mostly me commenting, I don't use any of these drivers in production as I only do stuff with MySQL at work.   I like pymssql being around but it's hard to compete with MSFT actually supporting pyodbc, i didn't know they were doing that (even though #477 mentions it).

**Comment by echen805** [comment]
@rsyring is pymssql still being actively developed then? I see that the last commit was in Jan 2018. I can help be a maintainer and start fixing PRs if there is someone else available to help peer review.

**Comment by rsyring** [comment]
@echen805 Thanks for your interest.  Please post on https://github.com/pymssql/pymssql/issues/516 and let's discuss there.
