### ISSUE TITLE
Is pymssql LGPL 2 only?

### ISSUE THREAD

**Issue by dsuch** [pymssql/pymssql#625]
Hello,

I would like to try to embed pymssql in [Zato](https://zato.io/docs/) but I am not sure if the library is LGPL 2 only?

Zato is under LGPL v3 and I ask for clarification, is pymssql under LGPL v2 alone or is it v2 and v3?

Regards.

**Comment by AlexHagerman** [comment]
Today the `LICENSE` file is only LGPL v2.

**Comment by dsuch** [comment]
Hello @AlexHagerman - seeing as you said 'today', does it mean that you plan to change it?

**Comment by AlexHagerman** [comment]
I have no plans to change the LICENSE, but I'm not the library creator just a contributor.

**Comment by rsyring** [comment]
No, it won't be changing.  

> Zato is under LGPL v3 and I ask for clarification, is pymssql under LGPL v2 alone or is it v2 and v3?

Please read the license and maybe consult an attorney.  We don't want to be giving legal advice.  :)

**Comment by dsuch** [comment]
@rsyring - I was looking for confirmation about the version that you want for this library to be under, I do not see how this could be interpreted as my not being familiar with either or that I was asking for legal advice.

That aside, seeing as you have confirmed that this is LGPLv2 only, this answers my question and I will close the ticket.

**Comment by rsyring** [comment]
The license file clearly states that the license is version 2.1: https://github.com/pymssql/pymssql/blob/master/LICENSE

I'm sorry if I misunderstood your question.

**Comment by dsuch** [comment]
Sure, generally, when asked, most people do not have any issues with using LGPLv3 in addition to v2 as long as it is LGPL, not GPL, nor BSD/MIT/similar.

Sometimes this is because they just settled on something many years ago and no one asked about it since then and sometimes because they are not aware of the possibility to license their libraries under more than one license. Sometimes it is because their library is a low-level one that will not see much use if it is licensed too restrictively.

This is why I felt it prudent to ask the question.

In this particular case, what also prompted me into submitting this question was that pymssql is described as being under "Lesser General Public License (LGPL)" on PyPI even if PyPI has [a range of choices](https://pypi.org/classifiers/), including more specific ones:

License :: OSI Approved :: GNU Lesser General Public License v2 (LGPLv2)
License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)
License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)
License :: OSI Approved :: GNU Lesser General Public License v3 or later (LGPLv3+)
License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)

This was inconsistent with what GitHub was saying so I wanted to double-check it.

**Comment by rsyring** [comment]
We'll keep this issue open to clarify the license on pypi.

> Sure, generally, when asked, most people do not have any issues with using LGPLv3 in addition to v2 as long as it is LGPL, not GPL, nor BSD/MIT/similar.

In this case, it's not a matter of us having or not having an issue with it.  It's that there have been a number of maintainers on this project and changing or even clarifying the license of the project, beyond simply pointing to what the license file says, would take getting the permission and consensus of everyone who had contributed under the existing license.
