### ISSUE TITLE
prerequisites

### ISSUE THREAD

**Issue by Jefronty** [pymssql/pymssql#638]
The install instructions say that FreeTDS is required, but do not mention that Cython is also required.  I kept getting an error while attempting to install via PIP before I installed BOTH _FreeTDS_ and _Cython_ via `apt-get`  
Also installing pymssql via apt-get (python-pymssql) does not install either _freetds_ or _cython_

**Comment by termim** [comment]
Fixed in https://github.com/termim/pymssql/commit/8a6b84b3f98962044d656b581698b38f36c11bc0
