### ISSUE TITLE
DATETIMEOFFSET returns binary object instead of a datetime object

### ISSUE THREAD

**Issue by ttallierchio** [pymssql/pymssql#649]
I am encountering an issue when im trying to pull datetimeoffset data using pymssql. no matter what column i pull from on any database in several environments i get a set of bytes that i have to decode to make this field useable. 

the below stackoverflow post has code samples as well as a work around. 

[stackoverflow link](https://stackoverflow.com/questions/56693367/pymssql-is-returning-binary-data-for-datetimeoffset)

is there a function or something else im missing here?

**Comment by bemoody** [comment]
This behavior seems to have changed as a result of changing default/supported TDS protocol versions.

It seems that if you invoke pymssql.connect with tds_version='7.2' or earlier, then DATETIMEOFFSET values are returned as a Python string (in ISO 8601 format).

If you use tds_version='7.3', then DATETIMEOFFSET values are returned as some kind of packed binary object.

Which protocol version is used by default seems to depend on which version of freetds as well as which version of pymssql you are using.

This seems likely related to issue #156.

**Comment by JimiC** [comment]
For future reference here's a code snippet for a workaround, in case some else is looking for it.
```python
from datetime import datetime, timedelta
from math import modf
from struct import unpack

from dateutil.tz import tzoffset


def convert_datetimeoffset_to_datetime(self, dto, precision):
    # haven't figured out what the last tuple part is for
    (microseconds, days, tz_minutes, _) = unpack("<QI2h", dto)
    ms, s = modf(microseconds / 10**precision)
    offset = timedelta(minutes=tz_minutes).total_seconds()
    tzname = "UTC" if offset == 0 else "ANY"
    # add tzinfo here for ease
    sql_epoch = datetime(1900, 1, 1, 0, 0, 0, tzinfo=tzoffset(tzname, offset))
    td = timedelta(
        days=days,
        minutes=tz_minutes,
        seconds=int(s),
        microseconds=int(ms * 1e6),  # microseconds: 0..999999
    )
    return sql_epoch + td
```

The above was highly influenced from this [stackoverflow answer](https://stackoverflow.com/a/56706596) (kudos to the OP)

**Comment by bemoody** [comment]
I believe that first 64-bit integer is *tenths* of a microsecond.  Not
microseconds.  The last 16 bits should contain the precision and
flags.

I believe what you're looking at is DBDATETIMEALL, as defined here:
https://github.com/FreeTDS/freetds/blob/v1.3.17/include/sybdb.h#L306

**Comment by klesun** [comment]
Is this library still maintained?

**Comment by PavelUmanskiy** [comment]
> For future reference here's a code snippet for a workaround, in case some else is looking for it.

Your version didn't work for me, so I've modified it and for me it worked better:
```python
def convert_datetimeoffset_to_datetime(bytes_: bytes) -> datetime:
    (_microseconds, days, tz_minutes, _) = unpack("<QI2H", bytes_)
    seconds, milliseconds = divmod(_microseconds, 10**7)
    milliseconds = milliseconds / 10 ** 4
    offset = timedelta(minutes=tz_minutes).total_seconds()
    tzname = "UTC" if offset == 0 else "ANY"
    sql_epoch = datetime(1900, 1, 1, 0, 0, 0, tzinfo=tzoffset(tzname, offset))
    td = timedelta(
        days=days,
        seconds=seconds,
        milliseconds=milliseconds
    )
    return sql_epoch + td
```

Input:
b'\x10_uI\x81\x00\x00\x00\xdd\xb0\x00\x00\x00\x00\x07\xe0'
b'\xa0\xfb\x84\x80\x81\x00\x00\x00\xdd\xb0\x00\x00\x00\x00\x07\xe0'
b'\xc0\xd8\xe3\xcc\x83\x00\x00\x00\xdd\xb0\x00\x00\x00\x00\x07\xe0' b'\x10W7\x86\x99\x00\x00\x00\xdd\xb0\x00\x00\x00\x00\x07\xe0'
Expected output:
2023-12-19 15:25:28.3210000 +00:00 
2023-12-19 15:27:00.6980000 +00:00 
2023-12-19 15:43:27.8200000 +00:00 
2023-12-19 18:18:58.1770000 +00:00
Your version returned datetime object, but the time part was missing (it was all zeroes). Me and my friend managed to figure out that the `microseconds` variable is actully the MSSQL db ticks
Anyway, thank you for your answer, it helped a lot!

**Comment by termim** [comment]
Should be fixed in 
4e473c4d7db067a74dd475bf12201486520c77c2
d09684321afe638c9ebea4625df43e7c061b1c76

**Comment by ArtemiyNaumov** [comment]
@PavelUmanskiy hi, your convertion func works great! But don't you lose the amount of hours equal to the offset value in the final timestamp? Let me explain: when I tried this func with timestamp `'2024-03-27 03:00:43+07:00'` (this is the value from the mssql db) I got `'2024-03-26 20:00:43+07:00'` from the func, which is obviously "less" for 7 hours - a timezone (and `offset` in the func) value. So when I tried other timestamps, for example with +03:00 timezone, func returned value which is 3 hours earlier than the initial timestamp. For now I need some more time to dive into the meaning of every step of `convert_datetimeoffset_to_datetime()`, but this is possible that the `td` value should be:
```python
    td = timedelta(
        days=days,
        seconds=seconds+offset,
        milliseconds=milliseconds
    )
```

**Comment by PavelUmanskiy** [comment]
@ArtemiyNaumov maybe, but at the time the only concern for me and my coworker was the empty time part (since we were dealing with UTC+0 timezone, we didn't notice this bug). Anyway, thank you for your comment, I would like to see how your investigation works!

**Comment by JimiC** [comment]
@PavelUmanskiy 
> Your version returned a datetime object, but the time part was missing (it was all zeroes). Me and my friend managed to figure out that the microseconds variable is actully the MSSQL db ticks

Your `tz_minutes` were zero because you had storing UTC times which have no offset.

My code example worked just perfect for my project where I had to write and read `DATETMEOFFSET`, for an app that would run in EET (Eastern European Time) and IST (Indian Standard Time). The two have a 3 hour and a half deference.

What made it work was the part you left out, the `minutes=tz_minutes,` when constructing the `td`.
You see datetimes with offset always are representing the local time adding the offset part to notate the time difference from UTC.
