### ISSUE TITLE
Why is connection closed?

### ISSUE THREAD

**Issue by zhaoyi0113** [pymssql/pymssql#657]
I create a database connection then keep the connection instance in my application and use it for all other requests. It works fine at beginning but the connection is closed after a few hours. I checked that the `_conn.connected` is false on my connection instance. Does the connection close automatically if it is not used for some time?

```
connection = pymssql.connect(host, DB_USER, DB_PASSWORD, 'admin')
```

**Comment by JayRizzo** [comment]
>> Does the connection close automatically if it is not used for some time?

# In short, no.
There are two different paths that have their own ways to address timeouts:

1. Thru the module
1. Thru the database

My understanding is (_as the documentation is limited_) that this will only happen if you have too many connections from when you don't close your connection(s) to the DB properly (or, whether or not you are using connection pooling).  If you are using connection pooling please read below about "removing connections"

If you exceed your max connections, your connection will/may close. But, there is not a _direct timeout_ for keeping your connection alive as that is part of the designed behaviour with MS_SQL as it is **indefinite**.

Always check your DB settings too, as the DB might have priority over the module unless directly specified in the module.

# Module Research
Please see these researched links and I hope they help:

http://pymssql.org/en/stable/release_notes.html#mssql-module

## _mssql.login_timeout
> http://pymssql.org/en/stable/ref/_mssql.html#_mssql.login_timeout
> Timeout for connection and login in seconds, default 60.


## MSSQLConnection.query_timeout
> http://pymssql.org/en/stable/ref/_mssql.html#_mssql.MSSQLConnection.query_timeout
> Query timeout in seconds, default is 0, which means to wait indefinitely for results. Due to the way DB-Library for C works, setting this property affects all connections opened from the current Python script (or, very technically, all connections made from this instance of dbinit()).

and 

Connection limitations:
http://pymssql.org/en/stable/ref/_mssql.html#_mssql.set_max_connections
## _mssql.set_max_connections(number)

> Sets maximum number of simultaneous connections allowed to be open at any given time. Default is 25.
> 
## _mssql.get_max_connections()
> Gets current maximum number of simultaneous connections allowed to be open at any given time.

# Database Research

# [SQL Server Connection Pooling (ADO.NET)](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-connection-pooling?redirectedfrom=MSDN#adding-connections)

> ...
>
> # Note
> 
> When connection pooling is enabled, and if a timeout error or other login error occurs, 
> an exception will be thrown and **subsequent connection attempts will fail for the next five seconds, the "blocking period"**. If the application attempts to connect within the blocking period, the first exception will be thrown again. Subsequent failures after a blocking period ends will result in a new blocking periods that is twice as long as the previous blocking period, up to a maximum of one minute.
> 
> ...
> 
> # Caution
> 

> We strongly recommend that you always close the connection when you are finished using it so that the connection will be returned to the pool. You can do this using either the Close or Dispose methods of the Connection object, or by opening all connections inside a using statement in C#, or a Using statement in Visual Basic. Connections that are not explicitly closed might not be added or returned to the pool. For more information, see using Statement or How to: Dispose of a System Resource for Visual Basic.
>
> ...
>
> # Removing Connections
> The **connection pooler removes a connection from the pool after it has been idle for approximately 4-8 minutes**, or **if the pooler detects that the connection with the server has been severed**. Note **that a severed connection can be detected only after attempting to communicate with the server**. **If a connection is found that is no longer connected to the server, it is marked as invalid. Invalid connections are removed from the connection pool only when they are closed or reclaimed**.
> 
> If a connection exists to a server that has disappeared, this connection can be drawn from the pool even if the connection pooler has not detected the severed connection and marked it as invalid. This is the case because the overhead of checking that the connection is still valid would eliminate the benefits of having a pooler by causing another round trip to the server to occur. When this occurs, the first attempt to use the connection will detect that the connection has been severed, and an exception is thrown.
> 
> ...

# [Connection Pooling for the SQL Server DBA](https://techcommunity.microsoft.com/t5/Premier-Field-Engineering/Connection-Pooling-for-the-SQL-Server-DBA/ba-p/370605)

> "Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.
> This may have occurred because all pooled connections were in use and max pool size was reached."
> 

# [Re: Does MS SQL Server have an idle timeout for connections?](http://www.vbforums.com/showthread.php?810173-RESOLVED-Does-MS-SQL-Server-have-an-idle-timeout-for-connections)

> There's two types of time outs - one is the ConnectionTimeout ... which determines how long it waits while making the connection before it times out...
> The other is the CommandTimeout ... which determines how long it will wait while executing the command before it times out.
> 
> I don't think either of those apply...
> 
> so the short answer is, no there is no idle timeout on the connection. Probably good for two reasons - 1) people will sometimes develop their app to open the connection once and keep it open for hte life of the app... whether the user uses it or not. 2) killing idle connections would kill the purpose of connection pooling, where connections are "closed" but held on until a new request comes.
>

**Comment by zhaoyi0113** [comment]
Thanks for this extensive explanation. I will investigate more on my side for this issue.
