### ISSUE TITLE
pip install -r requirements.txt

### ISSUE THREAD

**Issue by bnornes** [pymssql/pymssql#660]
Downloading https://files.pythonhosted.org/packages/2e/81/99562b93d75f3fc5956fa65decfb35b38a4ee97cf93c1d0d3cb799fffb99/pymssql-2.1.4.tar.gz (691kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-36weo9p6/pymssql/setup.py'"'"'; __file__='"'"'/tmp/pip-install-36weo9p6/pymssql/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-36weo9p6/pymssql/pip-egg-info
         cwd: /tmp/pip-install-36weo9p6/pymssql/
    Complete output (7 lines):
    /usr/local/lib/python3.5/dist-packages/setuptools/dist.py:46: DistDeprecationWarning: Do not call this function
      warnings.warn("Do not call this function", DistDeprecationWarning)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-36weo9p6/pymssql/setup.py", line 88, in <module>
        from Cython.Distutils import build_ext as _build_ext
    ImportError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c pip3 install -r requirements.txt' returned a non-zero code: 1

**Comment by Sunwukong00** [comment]
I have same problem.Not sure how to fixed it .

**Comment by schavery** [comment]
pymssql needs cython to build, but they haven't specified that in their own requirements. If you do a `pip install Cython`, or add it to your own requirements files, it should install fine.

**Comment by termim** [comment]
Fixed in https://github.com/termim/pymssql/commit/8a6b84b3f98962044d656b581698b38f36c11bc0
