### ISSUE TITLE
segmentation fault on network disconnect

### ISSUE THREAD

**Issue by amonsch** [pymssql/pymssql#661]
Hi,

i am getting a segmentation fault when i start and stop my mssql server instance multiple times, while my program (see snippet below) is running. The mssql server instance runs in a docker container.

A minimal version of my code looks as follows:
```python
#!/usr/bin/env python

import time
import pymssql


def run():
    conn = None
    while True:
        try:
            if not (conn and conn._conn.connected):
                conn = pymssql.connect(
                    "localhost",
                    "user",
                    "s3cret",
                    "mydb",
                )

            print("Doing SQL things ... ")
            with conn.cursor() as cursor:
                cursor.execute("select 1 as value")

        except pymssql.OperationalError as exc:
            print(f"Could not connect: {exc}")
        except AttributeError: # in case conn is None
            print("Could not connect ..")
            pass

        time.sleep(2)


if __name__ == "__main__":
    run()

```  

I am using pymssql v2.1.4 in production but can also reproduce the issue on the master branch. My Python version is 3.7.3. 

The exact output for my test looks like this:

```bash
python segfault.py
segfault.py:4: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working        
  import pymssql
Doing SQL things ...
Doing SQL things ...
Doing SQL things ...
Doing SQL things ...
Doing SQL things ...
Doing SQL things ...
Doing SQL things ...
Doing SQL things ...
Doing SQL things ...
Could not connect: (20004, b'\xa0\x91\xc4\x01DB-Lib error message 20004, severity 9:\nRead from the server failed\nNet-Lib error during Connection reset by peer (104)\n')
malloc(): unsorted double linked list corrupted
zsh: abort (core dumped)  python segfault.py
```

**Comment by mcgradycchen** [comment]
Hi , I have the same problem. Did you solve this problem?

**Comment by qdlaczian** [comment]
Same problem ubuntu python 3.7.5

**Comment by amonsch** [comment]
> Hi , I have the same problem. Did you solve this problem?

We kind of solved it - we ported our code to python-tds (https://github.com/denisenkom/pytds).

**Comment by qdlaczian** [comment]
> > Hi , I have the same problem. Did you solve this problem?
> 
> We kind of solved it - we ported our code to python-tds (https://github.com/denisenkom/pytds).

Good Job

**Comment by termim** [comment]
It doesn't happen with 2.1.5 on Linux and Windows.
Feel free to reopen if it still happens.
