### ISSUE TITLE
using callproc raises TypeError regardless of the parameters

### ISSUE THREAD

**Issue by hantusk** [pymssql/pymssql#669]
Using pymssql version 2.1.4.

Connecting with sqlalchemy. Finding the cursor object through cursor =  engine.raw_connection().cursor(), which is a cursor object from pymssql.

The method cursor.callproc returns TypeError: '<' not supported between instances of 'NoneType' and 'int' regardless of what parameters I set.

Excuse me for not making a more complete issue form, I have since moved on to pyodbc, which does not have an issue with stored procedures.

This stackoverflow posts shows a more complete example: https://stackoverflow.com/questions/33469291/pymssql-executes-stored-procedure-but-returns-no-results except the cursor.callproc fails with above TypeError in version 2.1.4.

**Comment by JuxhinDB** [comment]
This is a bug in 2.1.4 and manifests by default on Ubuntu 20.04 as well unfortunately. If it helps, you should lock down to Ubuntu 18.04 which allows you to install `python3-pymssql=2.1.3+dfsg-1build2` which should not have this bug due to the changes made to `tds_version` check.
