### ISSUE TITLE
Python 3.8 Wheels

### ISSUE THREAD

**Issue by cprieto** [pymssql/pymssql#670]
We need a Python wheel for Python 3.8, currently we have to install all dependencies and compile it because the latest wheel version is 3.7

**Comment by decaz** [comment]
https://github.com/pymssql/pymssql/pull/659

**Comment by gordthompson** [comment]
https://www.lfd.uci.edu/~gohlke/pythonlibs/#pymssql

**Comment by rsyring** [comment]
Closing since this project is being discontinued.  For details, see #668.
