### ISSUE TITLE
怎样使用指定的IP连接数据库？

### ISSUE THREAD

**Issue by JoffreyN** [pymssql/pymssql#673]
pymysql 可以用 bind_address 参数，但是pymssql没有
    conn=pymssql.connect(server=hostDic[env],user=user,password=password,bind_address=ip)
  File "src/pymssql.pyx", line 582, in pymssql.connect
TypeError: connect() got an unexpected keyword argument 'bind_address'

**Comment by xyy277** [comment]
conn2 = pymssql.connect(
    server=cp.get(role2, 'server'),
    user=cp.get(role2, 'user'),
    password=cp.get(role2, 'password'),
    port=cp.get(role2, 'port'),
    database=cp.get(role2, 'database'),
    autocommit=True)

**Comment by JoffreyN** [comment]
> autocommit
我的机器上有无线和有线两种网络，都可以上网， 但是只有有线网络可以连接我需要的数据库。但是使用pymssql连接默认使用无线网络，所以问题是如何指定使用有线网络连接？

**Comment by xyy277** [comment]
都是外网，为什么不断开WiFi，只用有线就可以了

**Comment by termim** [comment]
pymssqlconnect没有bind_address参数。 您必须在网络上配置路由。
