### ISSUE TITLE
PyPI project maintenance

### ISSUE THREAD

**Issue by termim** [pymssql/pymssql#678]
Hello @n0mn0m ,@n8harmon, @guruofgentoo and @wesm,
Could someone add me as a maintainer of the pymssql project on pypi.org and test.pypi.org please?
As a new maintainer I need this for the future releases.

**Comment by wesm** [comment]
I just added you on pypi.org. 

I'm not an owner on test.pypi.org, @rsyring could you add me as an owner there?

**Comment by n0mn0m** [comment]
Sorry, been offline. @wesm @termim you should both have access on test.pypi.org now.

**Comment by termim** [comment]
Thank you!

**Comment by n8harmon** [comment]
@wesm and @termim I received a notice today from PyPI that this is now seen as a critical project, which means that all maintainers will need to have 2FA enabled.  I had forgotten that I was even listed as an Owner of this project there.  It appears that @termim is now the primary maintainer of this project.  Is there any reason that he should not be made an Owner in PyPI.  I cannot remove myself from the project there, but I can make @termim an Owner, and either of you can remove me.  I'm not sure if @n0mn0m or @guruofgentoo still need to be maintainers in PyPI any longer either, so if you are cleaning up the maintainers, you may want to confirm with them.  Thanks.

**Comment by termim** [comment]
Yes, make me an owner please.

**Comment by wesm** [comment]
I just made @termim an owner.

**Comment by termim** [comment]
Thank you!
