### ISSUE TITLE
ModuleNotFoundError: No module named 'pymssql'

### ISSUE THREAD

**Issue by ronak2303** [pymssql/pymssql#682]
I have installed pymssql successfully and when i run it locally it works.
but when i try to run it from my application it fails with "ModuleNotFoundError: No module named 'pymssql'".
not sure if this is available only for user i have installed using pip and not available for other users.
environment is 
linux redhat 7.7
python 3

**Comment by termim** [comment]
The python environment you are using for your application should have  `pymssql` installed as well.

**Comment by ronak2303** [comment]
I have app app agent running on same server.

**Comment by termim** [comment]
Does it use the same python executable?

**Comment by termim** [comment]
It seems problem is gone ...
