### ISSUE TITLE
A problem with version 2.1.5: When inserting data into mysql, there is a Chinese scrambling code

### ISSUE THREAD

**Issue by CaptionLittleBird** [pymssql/pymssql#684]
Hello, author:
        I am a user from China.
        Recently, I used PYMSSQL, version 2.1.5, to query data from SQL Server and insert it into the mysql database. I found that the Chinese part had some confusing codes, but version 2.1.4 was ok, so this is a bug, please kindly correct it

**Comment by termim** [comment]
Please provide an example to help fix the problem, check [sscce.org](http://sscce.org) to see what would be helpful.

**Comment by jackywang615** [comment]
![Snipaste_2021-01-07_16-58-07](https://user-images.githubusercontent.com/9586655/103872601-99186380-5109-11eb-8b98-2f658bee3a2d.png)
@termim

**Comment by termim** [comment]
You can try this workaround:
`
conn = pymssql.connect(server, user, password, "tempdb")
cursor = conn.cursor()
cursor.execute("SELECT %s, %s", (123,'你好傑基！'))
row = cursor.fetchone()
while row:
    print(f"ID={row[0]},  Name={row[1]}")
    row = cursor.fetchone()
conn.close()
... 
... ID=123,  Name=你好傑基！conn.close()

`

**Comment by jackywang615** [comment]
@termim but I cannot query chinese from table.

SQL
``` sql
CREATE TABLE dbo.Users
	(
	Name varchar(50) NULL
	)  ON [PRIMARY]
GO

INSERT INTO dbo.Users
(
    Name
)
VALUES
('你好'
    )
go
```

python code
``` python
import pymssql

conn = pymssql.connect(server, user, password, db)

cursor = conn.cursor()
cursor.execute("SELECT name from dbo.Users")
row = cursor.fetchone()
while row:
    print(f"name={row[0]}")
    row = cursor.fetchone()
conn.close()
```

![Snipaste_2021-01-08_08-52-54](https://user-images.githubusercontent.com/9586655/103961216-f5719680-518e-11eb-8b19-2817ff0cd6f3.png)

**Comment by termim** [comment]
You have to use the proper column type for unicode:

```python
conn = pymssql.connect(server, user, password, "tempdb")
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE dbo.Users
	(
	Name nvarchar(50) NULL
	)  ON [PRIMARY]
""")
cursor.execute("INSERT INTO dbo.Users (Name) VALUES (%s)",'你好')
cursor.execute("SELECT Name FROM dbo.Users")
row = cursor.fetchone()
while row:
    print(f"Name={row[0]}")
    row = cursor.fetchone()

conn.close()
...
... Name=你好
```

**Comment by zhaoziming** [comment]
@CaptionLittleBird 我也遇到了，仅限于windows。linux下是正常的，从2.1.5开始，不知道他们改了什么东西。查了好几个月也没有结果。现在升级到Python 3.10，发现2.1.5以下的版本都不支持了。虽然windows仅限于日常开发，但是也挺不方便的。

**Comment by CaptionLittleBird** [comment]
用异步的话就用 aiomysql 或者 asyncmy 就好，不用的话 正常的pymsyql就可以啦，这个包时间长了 我也忘记当时我是为什么用他了，但是现在我的主项目python还是3.7 所以也没什么错



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月9日(星期四) 下午3:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pymssql/pymssql] A problem with version 2.1.5: When inserting data into mysql, there is a Chinese scrambling code (#684)





 
@CaptionLittleBird 我也遇到了，仅限于windows。linux下是正常的，从2.1.5开始，不知道他们改了什么东西。查了好几个月也没有结果。现在升级到Python 3.10，发现2.1.5以下的版本都不支持了。虽然windows仅限于日常开发，但是也挺不方便的。

**Comment by zhaoziming** [comment]
@CaptionLittleBird 这是SQLServer的，pymysql肯定不能连SQLServer，我们现在重度依赖这个包。

**Comment by CaptionLittleBird** [comment]
我看了官网上还是支持windows的，如果升级还是不行，你们得考虑先降低python版本，如果还不行 试试别的sql也不来呗，sqlserver还花钱




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pymssql/pymssql"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月9日(星期四) 下午5:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pymssql/pymssql] A problem with version 2.1.5: When inserting data into mysql, there is a Chinese scrambling code (#684)





 
@CaptionLittleBird 这是SQLServer的，pymysql肯定不能连SQLServer，我们现在重度依赖这个包。

**Comment by termim** [comment]
> @CaptionLittleBird 我也遇到了，仅限于windows。linux下是正常的，从2.1.5开始，不知道他们改了什么东西。查了好几个月也没有结果。现在升级到Python 3.10，发现2.1.5以下的版本都不支持了。虽然windows仅限于日常开发，但是也挺不方便的。

@zhaozhiming 请提供不起作用的表架构和查询

**Comment by zhaozhiming** [comment]
你是不是艾特错人了 @termim
