### ISSUE TITLE
Mac OS can't connect, error 20002.

### ISSUE THREAD

**Issue by matianhe3** [pymssql/pymssql#700]
`macOS Big Sur 11.2.1 (20D74)`
`Python 3.8.2`
`pymssql 2.1.5`
`freetds-1.2.18`

```
Traceback (most recent call last):
  File "src/pymssql.pyx", line 636, in pymssql.connect
  File "src/_mssql.pyx", line 1964, in _mssql.connect
  File "src/_mssql.pyx", line 682, in _mssql.MSSQLConnection.__init__
  File "src/_mssql.pyx", line 1690, in _mssql.maybe_raise_MSSQLDatabaseException
_mssql.MSSQLDatabaseException: (20002, b'DB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (192.168.16.100)\nDB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (192.168.16.100)\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 15, in <module>
    run()
  File "test.py", line 9, in run
    ms = MthMssql(100)
  File "/Users/matianhe/mth/sql/mssql.py", line 20, in __init__
    self.conn = pymssql.connect("192.168.16.100", "dong", "dong@159753", "YsDB")
  File "src/pymssql.pyx", line 642, in pymssql.connect
pymssql.OperationalError: (20002, b'DB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (192.168.16.100)\nDB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (192.168.16.100)\n')
```

**Comment by matianhe3** [comment]
> Probably your module is not linked with OpenSSL. Could you try the [dev wheel](https://test-files.pythonhosted.org/packages/69/72/7f4e467c3a77af924ff5bd371aa8f1fb6cf60e8383be07f9c200e54aba95/pymssql-2.1.6.dev55-cp38-cp38-macosx_10_14_x86_64.whl) and report back?

ok, it working well. why the error appears? Normally, how can i link with OpenSSL?

**Comment by termim** [comment]
Because the current wheels on PyPi are not built with SSL support.
You can do that when you build from source.
The next version will be built with SSL support.

**Comment by matianhe3** [comment]
> @termim
> Hi!
> I has same issue with
> bigsur 11.2.2
> pymssql 2.1.5
> freetds 1.2.21
> 
> Is there any dev wheel for this version of big sur?
> 
> It would be great if you had the opportunity to send it here.

i think it already solved by the latest version.

**Comment by StepanTuchin98** [comment]
> > @termim
> > Hi!
> > I has same issue with
> > bigsur 11.2.2
> > pymssql 2.1.5
> > freetds 1.2.21
> > Is there any dev wheel for this version of big sur?
> > It would be great if you had the opportunity to send it here.
> 
> i think it already solved by the latest version.

Hm, I has installed 2.2.2 pymssql, but seems like it doesn't work properly.

**Comment by termim** [comment]
@StepanTuchin98 
Hi!
Could you provide more details - exact error message, where you installed pymssql from...

**Comment by angdust** [comment]
@termim
Hi!
bigsur 11.2.2
pymssql 2.2.2
freetds 1.3
After update the problem from @StepanTuchin98 partly solved, but now I have this issue:
`from _mssql import MSSQLException
E   ModuleNotFoundError: No module named '_mssql'`
Has smth changed or what?
P.S. I installed pymssql from pip.
