### ISSUE TITLE
A strange memory usage

### ISSUE THREAD

**Issue by kuraga** [pymssql/pymssql#701]
Good day!

Do query with several JOINs. The result is 4Gb via SSMS export.

But with pymssql process crashes with 64Gb of RAM.

Could it be a known issue?

Thanks!

**Comment by termim** [comment]
Yes this is expected. Kind of. If you'd parse and load these 4Gb data in python (even without pymssql) you'd eat a lot more memory.

**Comment by kuraga** [comment]
@termim after some investigation it seems to be my fault. SSMS provide not full data by default and cuts off columns by 255 symbols. So 4Gb were not the whole data.

But BTW abiout "eating" memory. I saw this: https://sourceware.org/bugzilla/show_bug.cgi?id=14827. Hah! Remember this "feature" on such questions...
