### ISSUE TITLE
Missing wheels for python 3.9 on window

### ISSUE THREAD

**Issue by CaselIT** [pymssql/pymssql#702]
Hi,

On [pypi](https://pypi.org/project/pymssql/#files) wheels for python 3.9 for windows (and osx too) are missing.

It would be great if you could publish them.

Thanks!

**Comment by termim** [comment]
Sorry for the delay, would 2.2.0 do for you?

**Comment by CaselIT** [comment]
Sure, that should work.

I noticed that 2.2.0 has py3.9 wheels. Thanks!
