### ISSUE TITLE
Core Dumped on connect() with 2.2.0

### ISSUE THREAD

**Issue by ondrejbosik** [pymssql/pymssql#706]
[pymssql2.2.0.core.dump.txt](https://github.com/pymssql/pymssql/files/6316256/pymssql2.2.0.core.dump.txt)
Previously we were using 2.1.5 but it was crashing when the database was shut down with double-linked lists very similar to issue #697 or #686 (both being open still) always ending up in Python interpreter's crash.

Then we've upgraded to 2.2.0 but at this time we're not even able to connect. Interpreter crashes immediately upon server connect with core dump.

[ondrej@devbase8 CommonServer]$ ./venv/bin/python3.8
Python 3.8.3 (default, Aug 31 2020, 16:03:14)
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
> import pymssql
> conn = pymssql.connect('192.168.199.132','sa','**********','tempdb')
Segmentation fault (core dumped)

I have attached a file with stack trace and a message in /var/log/message in an enclosed file.

We are using Cent OS 8:

Linux devbase8 4.18.0-240.22.1.el8_3.x86_64 #1 SMP Thu Apr 8 19:01:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Tested this behaviour with python 3.6 and 3.8 with the same results. All packages installed using PyPI (pip3).

Using MSSQL:

Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64) \n\tAug 22 2017 17:04:49 \n\tCopyright (C) 2017 Microsoft Corporation\n\tExpress Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19042: ) (Hypervisor)\n"},

With this new issue we're completely unable to access the database.

**Comment by termim** [comment]
Could you try to install pymssql from [here](https://test.pypi.org/project/pymssql/2.2.1.dev2/)?

**Comment by ondrejbosik** [comment]
Hi Mikhail,

Thank you for the quick reaction.

I can confirm that this newer version does not dump core any more and I 
am able to connect to the database. This also fixed previous error with 
libc memory corruption and interpreter abort.

I will further test my script and let you know if I come into any other 
roadblock.

Do you have any idea when this fix will make it to a production 2.2.1 ?

Ondrej

**Comment by termim** [comment]
It is already on [PyPi](https://pypi.org/project/pymssql/#files).
And thank you for the detailed report!
