### ISSUE TITLE
cursors returned from user defined functions lose connection?

### ISSUE THREAD

**Issue by pymssql-issue-migrator** [pymssql/pymssql#71]
_From [blan...@gmail.com](https://code.google.com/u/115382761823886382237/) on September 21, 2011 12:05:30_

What steps will reproduce the problem? 1. The following executes with no problem:   

<pre>
my_host="host"
my_user="username"
my_database=""
conn = pymssql.connect(host=my_host,user=my_user,trusted=True,database=my_database)
cur = conn.cursor()
result = cur.execute("select 1")
for row in result: print row
</pre>

1. but when the connection is made in a separate function and returned by that function, the connection isn't kept:

<pre>
def get_cursor(my_host,my_user,my_database):
    conn = pymssql.connect(host=my_host,user=my_user,trusted=True,database=my_database)
    cur = conn.cursor()
    return cur

if __name__ == "__main__":
  my_host="host"
  my_user="username"
  my_database="database"
  cur = get_cursor("tomax","RLannon","Odin")
  cur.execute("select 1")
</pre>

returns error: 

<pre>
Traceback (most recent call last):
  File "test_cur.py", line 13, in <module>
    cur.execute("select 1")
  File "C:\Python26\lib\site-packages\pymssql.py", line 198, in execute
    raise InterfaceError, e[0]
pymssql.InterfaceError: Not connected to any MS SQL server
</pre>

Python 2.6.2
pymssql 1.0.2
SQL Server 9.0.5266

Thanks for any help, hopefully I'm just dumb.

_Original issue: http://code.google.com/p/pymssql/issues/detail?id=67_

**Comment by termim** [comment]
This usage pattern is completely wrong. When get_cursor() function returns the conn object will be garbage collected and destroyed. Cursors can not outlive connection they were created on.
