### ISSUE TITLE
Pypi Project links ChangeLog 404

### ISSUE THREAD

**Issue by Morabaraba** [pymssql/pymssql#711]
Hi

The Project links -> ChangeLog at https://pypi.org/project/pymssql/ points to:
https://github.com/pymssql/pymssql/blob/master/ChangeLog_highlights.rst

Should it not be changed to:
https://github.com/pymssql/pymssql/blob/master/ChangeLog.rst

Regards,

ps. Sorry if this is the wrong channel to report the issue/_bug_.

**Comment by termim** [comment]
Thanks for reporting! This will be fixed in the next release.
