### ISSUE TITLE
PowerPC AD connection to MSSQL Issue

### ISSUE THREAD

**Issue by marcelned** [pymssql/pymssql#715]
Architecture: PPC64LE 
OS: RHEL 7

Connecting to a database using SQL Server Authentication works, but can't connect to a SQL Server database that requires AD/LDAP authentication:

![image](https://user-images.githubusercontent.com/82392567/122762175-53a5b800-d29d-11eb-89c2-63634c48dee6.png)

**Comment by termim** [comment]
Can you connect using tsql from FreeTDS using AD/LDAP?

**Comment by marcelned** [comment]
Hi @termim 

After using FreeTDS driver, it works.

Thank you
