### ISSUE TITLE
[Question] SQL Big Int returns Decimal type

### ISSUE THREAD

**Issue by invokermain** [pymssql/pymssql#716]
OS: Windows 10

The cursor type hint is also 5 (Decimal) compared to Small Ints/Tiny Ints/Ints type hint 3 (Number).

I am assuming this is known and intended, is it a MSSQL limitation?

**Comment by termim** [comment]
I'm not sure I understand your question right, but yes it is intended and it is not a MSSQL limitation.

**Comment by invokermain** [comment]
Sorry my question was just why is it like this?

At first glance it seems very weird and I couldn't find any explanation online, but I was assuming there was a reason so wanted to ask why.

**Comment by termim** [comment]
Like what? What exactly you find weird?

**Comment by invokermain** [comment]
That a SQL integer type is translated into non-integer type in Python, with behaviour different from all the other SQL integer types.

You would assume that all SQL integer columns would be parsed into Python integers as Python can handle arbitrarily large integers.

You said this behaviour is intended, so what is the motivation for this design decision?

**Comment by termim** [comment]
Decimal is not an integer type. You can find it's description elsewhere, even in Python's documentation.

**Comment by invokermain** [comment]
Sorry, you've completely misunderstood my question (I know what Decimal is).

I was wondering why does executing `SELECT CAST(2,200,000,000 AS BIGINT)` return `Decimal(2200000000.0)` and not `2200000000`?

**Comment by invokermain** [comment]
I can see that BIGINT is cast to `PY_LONG_LONG` here: https://github.com/pymssql/pymssql/blob/master/src/pymssql/_mssql.pyx#L967

But I cannot see why this is turned into Decimal type (or where)?

**Comment by termim** [comment]
That example would make it clear from the beginning :)

**Comment by termim** [comment]
It returns 2200000000 for me. Please provide a complete example script that reproduces the problem.

**Comment by invokermain** [comment]
1. Apologies for not providing an example up front.
2. This is actually weird MSSQL behaviour and not related to pymssql, pymssql is acting correctly. See this example.

```SQL
SELECT 
    2147483648 Col_BigInt
    , CAST(2147483648 AS BIGINT) Col_BigInt2
INTO #temp;
EXEC tempdb.dbo.sp_help @objname = N'#temp';
```

This tells you that `Col_BigInt` is treated as `Numeric`, and `Col_BigInt2` is treated as `BigInt`.

Sorry for wasting your time!
