### ISSUE TITLE
I cannot install prior working version via pip on Mac

### ISSUE THREAD

**Issue by apocalypse2012** [pymssql/pymssql#717]
Fails to install prior working version when trying to downgrade to work around other failures in the current version. Mac OS 10.15.7 Catalina

Collecting pymssql==2.1.5
  Using cached pymssql-2.1.5.tar.gz (167 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Building wheels for collected packages: pymssql
  Building wheel for pymssql (PEP 517): started
  Building wheel for pymssql (PEP 517): finished with status 'error'
Failed to build pymssql

  ERROR: Command errored out with exit status 1:
   command: /Users/rstewart/Depot/acc_elt_pipeline/venv/bin/python /Users/rstewart/Depot/acc_elt_pipeline/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/w4/75s7wb5156d5znlvllzfpgxc0000gn/T/tmppe_j7x2r
       cwd: /private/var/folders/w4/75s7wb5156d5znlvllzfpgxc0000gn/T/pip-install-m252jzqo/pymssql_99c0cbf257ca4334898d38badc4223e1
  Complete output (33 lines):
  setup.py: platform.system() => 'Darwin'
  setup.py: platform.architecture() => ('64bit', '')
  setup.py: platform.libc_ver() => ('', '')
  setup.py: Detected Darwin/Mac OS X.
      You can install FreeTDS with Homebrew or MacPorts, or by downloading
      and compiling it yourself.
  
      Homebrew (http://brew.sh/)
      --------------------------
      brew install freetds
  
      MacPorts (http://www.macports.org/)
      -----------------------------------
      sudo port install freetds
  
  setup.py: Not using bundled FreeTDS
  setup.py: include_dirs = ['/usr/local/include']
  setup.py: library_dirs = ['/usr/local/lib']
  running bdist_wheel
  running build
  running build_ext
  cythoning src/_mssql.pyx to src/_mssql.c
  cythoning src/pymssql.pyx to src/pymssql.c
  building '_mssql' extension
  creating build
  creating build/temp.macosx-10.15-x86_64-3.9
  creating build/temp.macosx-10.15-x86_64-3.9/src
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/usr/local/include -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/tcl-tk/include -I/Users/rstewart/Depot/acc_elt_pipeline/venv/include -I/usr/local/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c src/_mssql.c -o build/temp.macosx-10.15-x86_64-3.9/src/_mssql.o -DMSDBLIB
  src/_mssql.c:613:10: fatal error: 'sqlfront.h' file not found
  #include "sqlfront.h"
           ^~~~~~~~~~~~
  1 error generated.
  error: command '/usr/bin/clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for pymssql
ERROR: Could not build wheels for pymssql which use PEP 517 and cannot be installed directly

**Comment by termim** [comment]
It seems you do not have FreeTDS installed.
