### ISSUE TITLE
install last version 2.2.2 in "2021-05-07-raspios-buster-armhf-lite"

### ISSUE THREAD

**Issue by jealcuna** [pymssql/pymssql#720]
Since the issue with "Adaptive Server connection failed" is solved by updating the binding version to 2.2.2, I am trying to update the binding version of raspbian which is 2.1.4. However I can not install:

I test the following:
- make a clean OS installation with "2021-05-07-raspios-buster-armhf-lite"
- install pip with "sudo apt install python3-pip"
- install "sudo apt-get install freetds-dev"
- and then install with pip "sudo pip3 install pymssql==2.2.2"

In the pymssql installation process i get this:

`Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pymssql
  Using cached pymssql-2.2.2.tar.gz (170 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Building wheels for collected packages: pymssql
  Building wheel for pymssql (PEP 517): started
  Building wheel for pymssql (PEP 517): still running...
  Building wheel for pymssql (PEP 517): finished with status 'error'
Failed to build pymssql

WARNING: Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /usr/local/lib/python3.7/dist-packages
sysconfig: /usr/lib/python3.7/site-packages
WARNING: Value for scheme.purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /usr/local/lib/python3.7/dist-packages
sysconfig: /usr/lib/python3.7/site-packages
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /usr/local/include/python3.7/UNKNOWN
sysconfig: /usr/include/python3.7m/UNKNOWN
WARNING: Value for scheme.scripts does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /usr/local/bin
sysconfig: /usr/bin
WARNING: Value for scheme.data does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /usr/local
sysconfig: /usr
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
  WARNING: Value for purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /usr/lib/python3/dist-packages
  sysconfig: /usr/lib/python3.7/site-packages
  WARNING: Additional context:
  user = False
  home = None
  root = None
  prefix = None
  WARNING: Value for platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /usr/lib/python3/dist-packages
  sysconfig: /usr/lib/python3.7/site-packages
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/local/lib/python3.7/dist-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpag_b__lh
       cwd: /tmp/pip-install-mpwxw7jo/pymssql_63e7ba11ede04f3db78fa5b5d087cb27
  Complete output (25 lines):
  setup.py: platform.system() => Linux
  setup.py: platform.architecture() => ('32bit', 'ELF')
  setup.py: platform.libc_ver() => ('glibc', '2.28')
  setup.py: include_dirs => []
  setup.py: library_dirs => []
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-3.7
  creating build/lib.linux-armv7l-3.7/pymssql
  copying src/pymssql/__init__.py -> build/lib.linux-armv7l-3.7/pymssql
  running build_ext
  cythoning src/pymssql/_mssql.pyx to src/pymssql/_mssql.c
  cythoning src/pymssql/_pymssql.pyx to src/pymssql/_pymssql.c
  building 'pymssql._mssql' extension
  creating build/temp.linux-armv7l-3.7
  creating build/temp.linux-armv7l-3.7/src
  creating build/temp.linux-armv7l-3.7/src/pymssql
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -c src/pymssql/_mssql.c -o build/temp.linux-armv7l-3.7/src/pymssql/_mssql.o -DMSDBLIB
  arm-linux-gnueabihf-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-armv7l-3.7/src/pymssql/_mssql.o -lsybdb -lssl -lcrypto -o build/lib.linux-armv7l-3.7/pymssql/_mssql.cpython-37m-arm-linux-gnueabihf.so
  /usr/bin/ld: cannot find -lssl
  /usr/bin/ld: cannot find -lcrypto
  collect2: error: ld returned 1 exit status
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pymssql
ERROR: Could not build wheels for pymssql which use PEP 517 and cannot be installed directly`

**Comment by termim** [comment]
The error message suggests that libssl and libcrypto are missing.

**Comment by jealcuna** [comment]
I solve by installing "apt-get install libssl-dev"
