### ISSUE TITLE
problem with fetchmany()

### ISSUE THREAD

**Issue by hai-hotmail** [pymssql/pymssql#722]
**Describe the bug**
After creating a cursor, the program will report an error if the the cursor.fetchmany() is not executed within a certain period of time. Error message: “20047, b'DB-Lib error message 20047, severity 9:\nDBPROCESS is dead or not enabled\n'”

**To Reproduce**
chunk_size = 20000
cursor = conn.cursor()
cursor.execute(simple_select_query)

for part in range(1, 100):
    cursor.fetchmany(chunk_size)
    sleep(60)

**Expected behavior**
fetchmany() will be executed 100 without error.

**Current Behavior**
Depends on sleep time:
     If the sleep time is less than 25 seconds then the code is ok. fetchmany() runs for 100 times without any error.
     If the sleep time is greater than 25s then only the first fetchmany can complete. The job will failed at the second fetchmany run with error message “20047, b'DB-Lib error message 20047, severity 9:\nDBPROCESS is dead or not enabled\n'”

**Context (Environment)**
 - What are the OS, Python and FreeTDS versions?
    pyhton 3.6. AWS Glue python shell.

**Additional context**

**Comment by termim** [comment]
It looks like it is a connection and/or MSSQL server configuration problem, not pymssql one.
May be something like [this](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/63bfcfb2-6cca-4cff-96df-216ad206881e/dbprocess-is-dead-or-not-enabled?forum=sqldatabaseengine) could help.
