### ISSUE TITLE
SQL query with IN condition

### ISSUE THREAD

**Issue by jsguerrero** [pymssql/pymssql#726]
I'm trying to get multiple rows from SQL query with IN condition based on [Docs examples](https://pymssql.readthedocs.io/en/stable/_mssql_examples.html) from the _examples of queries with parameters_ section as follows:

```
from pymssql import _mssql
conn = _mssql.connect(server=server, user=user_db, password=password_db)

conn.execute_query('SELECT * FROM [Table] WHERE Id IN (%s)', ((5, 6),))

#show result
for row in conn:
    print(row['Id'])
```
I get a error

> MSSQLDatabaseException: (102, b"Incorrect syntax near ','.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n")

If change the query code for: (only remove the comma after of tuple params)
```
conn.execute_query('SELECT * FROM [Table] WHERE Id IN (%s)', ((5, 6)))

for row in conn:
    print(row['Id'])
```

run but doesn't work as I expect, just get one row.

![imagen](https://user-images.githubusercontent.com/73492954/132141784-0f6a5110-3b2a-4cf8-915e-f8c534d0d53c.png)

If change the tuple elements order, then get

![imagen](https://user-images.githubusercontent.com/73492954/132141810-78cd3d95-a46c-400e-80c2-7c2f0cabccca.png)

I don't know what I can be doing wrong.

Thanks!

**Comment by jsguerrero** [comment]
This [conversation](https://groups.google.com/g/pymssql/c/TyhtI0rbNjo/m/HFIFRwFpgRcJ) help.

![imagen](https://user-images.githubusercontent.com/73492954/132142147-eb330d69-7ed2-4f87-b051-f84e1630e17b.png)

It works, but it is not entirely clear to me the difference or why it does it that way

**Comment by termim** [comment]
It was a bug in the documentation. Fixed, see [latest](https://pymssql.readthedocs.io/en/latest/_mssql_examples.html).
