### ISSUE TITLE
Kerberos authentication not supported by wheels

### ISSUE THREAD

**Issue by prensing** [pymssql/pymssql#734]
**Describe the bug**
I have been running 2.1.6 on Linux with success. I can connect to our SqlServer using just Kerberos authentication.
Because of a new machine, I installed 2.2.2 directly with pip, and it does not connect. If I turn on TDSDUMP, I see:

tls.c:1049:handshake succeeded!!
login.c:939:requested GSS authentication but not compiled in
login.c:566:login packet rejected
query.c:3757:tds_disconnect() 
util.c:179:Changed query state from IDLE to DEAD

If I read it correctly, the built in version of FreeTDS is not properly compile with Kerberos support. 

**To Reproduce**
Install 2.2.2 on Linux. Create a kerberos token with kinit. Try to connect.

**Expected behavior**
This worked find in 2.1.6, with the external libsybdb from Linux Mint (Ubuntu variant).

**Current Behavior**
What happens instead of the expected behavior.

**Context (Environment)**
Python 3.8.10
pymssql 2.2.2 installed by pip

**Additional context**

**Comment by prensing** [comment]
Log file from a run with TDSDUMP on.
[pymssql.log](https://github.com/pymssql/pymssql/files/7721161/pymssql.log)

**Comment by prensing** [comment]
OK, I have improved my understanding of pip. If you install pymssql with:
    python3 -m pip install  --no-binary=pymssql pymssql
then it will ignore the wheel and compile it with the local libraries.

I think you should document this clearly on the website. There are various statements about "if you are using an external version of FreeTDS,...." but I could not find anything about *how* to do that.

**Comment by termim** [comment]
Could you try the wheels from [test.pypi](https://test.pypi.org/project/pymssql/2.2.3.dev10/#files)?

**Comment by termim** [comment]
Fixed in 8f8b88c46e046572fac607cd496d5f9cfce52fb1 and aa0d4a89928bd65ae112e09a100149f5cfb0b4ed.
