### ISSUE TITLE
cursor.nextset() does not return True when there is another result set

### ISSUE THREAD

**Issue by invokermain** [pymssql/pymssql#749]
**Describe the bug**
`cursor.nextset()` returns 1 instead of True if there is another set. This seems to go against [PEP249](https://www.python.org/dev/peps/pep-0249/#nextset). As an example, [pyodbc return True](https://github.com/mkleehammer/pyodbc/blob/24e0ccadaec091ce6b1b81e3197a345b895773fc/src/cursor.cpp#L1990). This behaviour is strange as it returns a truthy value but you would be caught out if you did an explicit `if cursor.nextset() is True`.

**To Reproduce**
```python
import pymssql as sql

QUERY = "SELECT 1 Set1; SELECT 2 Set2;" 

if __name__ == "__main__":
    conn = sql.connect(server="SERVER")
    with conn.cursor() as cursor:
        cursor.execute(QUERY)
        ok = cursor.nextset()
        print(f"0a. {ok is True}")
        ok = cursor.nextset()
        print(f"0b. {ok is None}")
```

**Expected behavior**
`cursor.nextset()` should return True or None as per the PEP.

**Current Behavior**
`cursor.nextset()` returns 1 instead of True if there is another set.

**Context (Environment)**
 N/A

**Relevant Line In Source Code**
https://github.com/pymssql/pymssql/blob/master/src/pymssql/_pymssql.pyx#L497

**Comment by termim** [comment]
Please note that [PEP249](https://www.python.org/dev/peps/pep-0249/#nextset) says: "**it returns a true value**" - note the casing. See [here](https://docs.python.org/3/library/stdtypes.html?highlight=comparison#truth-value-testing) for truth value testing. According to PEP249 it could even return a number of remaining sets if any.
