### ISSUE TITLE
symbol not found in flat namespace '_bcp_batch'

### ISSUE THREAD

**Issue by nnarta** [pymssql/pymssql#751]
Apple MacBook M1, pymssql-2.2.4, Python 3.9.10, 
I've tried to install/reinstall.
Any advice? bug?

```
from pymssql import _mssql
  File "/opt/homebrew/lib/python3.9/site-packages/pymssql/__init__.py", line 3, in <module>
    from ._pymssql import *
  File "src/pymssql/_pymssql.pyx", line 1, in init pymssql._pymssql
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/pymssql/_mssql.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_bcp_batch'
```

**Comment by derekmeegan** [comment]
Hello, I am also experiencing this problem. What code or method did you use to purge your cache?

**Comment by pambram** [comment]
@nnarta can you please explain what you did? I also have this problem and "pip cache purge" alone doesn't make it work for me.

**Comment by softgandhi** [comment]
I am also facing same issue
purge cache didn't help
