### ISSUE TITLE
pymssql vs. pyodbc

### ISSUE THREAD

**Issue by ubalklen** [pymssql/pymssql#755]
According to a [post](https://www.anaconda.com/blog/anaconda-easy-button-microsoft-sql-server-and-python) on the official Anaconda blog (from 2017):

> We start by importing the common pyodbc package. This is Microsoft's recommended Python interface to SQL Server. There was an alternate Python interface [pymssql](http://pymssql.org/en/stable/) that at one point was more reliable for SQL Server connections and even until quite recently was the only way to get Python on a Mac to connect to SQL Server, however with Microsoft's renewed support for Python and Microsoft's own Mac Homebrew packages it is now the case that pyodbc is the leader for all platforms.

Is this true? Is pyodbc the Microsoft endorsed way to go?

**Comment by termim** [comment]
I guess if Microsoft's endorsement is important to you, you have to ask Microsoft about it, otherwise just try and see which one is most convenient for you :).
