### ISSUE TITLE
pymssql install fails: fatal error building wheel

### ISSUE THREAD

**Issue by greg-mcnamara** [pymssql/pymssql#759]
**Describe the bug**
I'm trying to install pymssql on an RPi4 (arm64) running Ubuntu 20.04 with python 3.10. I get the following error when installing with pip as per the docs. Looks like I'm missing a pre-requisite but not sure which.

Collecting pymssql
  Using cached pymssql-2.2.5.tar.gz (170 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pymssql
  Building wheel for pymssql (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pymssql (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      setup.py: platform.system() => Linux
      setup.py: platform.architecture() => ('64bit', 'ELF')
      setup.py: platform.libc_ver() => ('glibc', '2.31')
      setup.py: include_dirs => []
      setup.py: library_dirs => []
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-3.10
      creating build/lib.linux-aarch64-3.10/pymssql
      copying src/pymssql/__init__.py -> build/lib.linux-aarch64-3.10/pymssql
      running build_ext
      cythoning src/pymssql/_mssql.pyx to src/pymssql/_mssql.c
      cythoning src/pymssql/_pymssql.pyx to src/pymssql/_pymssql.c
      building 'pymssql._mssql' extension
      creating build/temp.linux-aarch64-3.10
      creating build/temp.linux-aarch64-3.10/src
      creating build/temp.linux-aarch64-3.10/src/pymssql
      aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.10 -I/usr/local/include/python3.10 -c src/pymssql/_mssql.c -o build/temp.linux-aarch64-3.10/src/pymssql/_mssql.o -DMSDBLIB
      src/pymssql/_mssql.c:6:10: fatal error: Python.h: No such file or directory
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/aarch64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pymssql
Failed to build pymssql
ERROR: Could not build wheels for pymssql, which is required to install pyproject.toml-based projects

**To Reproduce**
`pip install pymssql`

**Expected behavior**
Successful installation

**Current Behavior**
Installation fails

**Context (Environment)**
 - What are the OS, Python and FreeTDS versions? Ubuntu 20.04, python 3.10
 - please include the output of the following command:
    `/<path to your python>/python -c "import pymssql; print(pymssql.version_info())"`

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pymssql'

**Additional context**

**Comment by termim** [comment]
It seems you do not have Python headers installed neither in /usr/include/python3.10 nor in /usr/local/include/python3.10.

**Comment by greg-mcnamara** [comment]
Thanks for your help @termim, I installed python3.10-dev which fixed the original error, then got errors "cannot find -lssl" and "cannot find -lcrypto". I installed libssl-dev and after that the build/install was successful.
