### ISSUE TITLE
Implement type hints

### ISSUE THREAD

**Issue by PaulConwayiii** [pymssql/pymssql#767]
Currently pymssql does not implement type hints and there is no library stub on typeshed. As the earliest version of pymssql officially supported is Python 3.6, there shouldn't be backwards compatibility issues with adding type hints.

Issue #437 was opened to add a stub file to typeshed and closed in 2016, but there is nothing in typeshed. Perhaps it was depreciated?

If there are reasons I am not aware of that prevents/discourages implementing type hints let me know, otherwise I will begin work and submit a PR when ready.

https://peps.python.org/pep-0484/

**Comment by mew1033** [comment]
I would love to see these! There is an old module on pypi, but it only supports python2. The types in typeshed were removed from the git repo, but the history is still there: https://github.com/python/typeshed/blob/8b0ff828a62e09d6236d85a6c4b22cd12d884bb2/third_party/2.7/pymssql.pyi

@PaulConwayiii, did you end up working on these types?

**Comment by aaravind100** [comment]
I started using this package and having no type intellisense is a deal breaker. Would love to have this feature.

Shall I give a go at this as there seems to be little/no progress on this for sometime?

Not a huge fan of adding the stubs in typeshed, as having source code and typing in different repo/packages could become tedious the manage.

**Comment by aaravind100** [comment]
@termim is this something which you'd like to be added? I raised a pr without asking as turned out to be fairly simple 😐
