### ISSUE TITLE
No data returned when callproc() function is called

### ISSUE THREAD

**Issue by Astrit11** [pymssql/pymssql#772]
**Describe the bug**
I'm spending quite some time debugging this issue.

I'm new with stored procedures so currently need to integrate some stored procedures for some x project,they have a stored procedure for authenticating user as below:

`
CREATE PROCEDURE [dbo].[AuthenticateUser]
	@username varchar(50),
	@password varchar(50)

AS
	SELECT * from Users where username=@username and Pass=@password
 `
My python code as below:

`
 conn = pymssql.connect("7x.1xx.x1.xx","user","pass","db_name")
 with conn.cursor(as_dict=True) as cursor:
    cursor.callproc('AuthenticateUser', (1111,111))
    //So after this i tried to access return values as:
    results = cursor.fetchall() //or
    cursor.fetchone() 
    //Tried adding the conn.commit() after calling the proc and then fetching the records but still nothing shows
 

`

**To Reproduce**
//

**Expected behavior**
In this case a user object should be returned 

**Current Behavior**
Nothing is  returned 

**Context (Environment)**
 -OS Ubuntu v.20.04.4, 
 -Python v.3.8.10
- FreeTDS v1.1.6
 -myssql v.2.2.5

**Additional context**
*Note:I can fetch records when executing a query directly but not while calling proc ex:
cursor.execute('SELECT * FROM Users where username=1111')
//then im able to fetch the records with 
row = cursor.fetchall()
//Then i can iterate through records

**Comment by prakash260** [comment]
If i am not wrong your Stored Procedure should return something for this to work. 
https://stackoverflow.com/questions/72055442/is-there-a-way-to-return-a-stored-procedure-return-value-to-the-python-script-ex

**Comment by Astrit11** [comment]
@prakash260 but as I know select is in itself a return in this case?

**Comment by prakash260** [comment]
i dont think thats how it works in case of Stored Procedure i believe. Try returning a output to see if it works.
