### ISSUE TITLE
bulk_copy fails when computed column exists in table.

### ISSUE THREAD

**Issue by markweissman** [pymssql/pymssql#775]
**Describe the bug**

bulk_copy fails when there are computed columns in the target table.

This fails with install:
`
    pyenv/bin/pip install --no-binary pymssql pymssql==2.2.5
`
This works fine with install:

 `
   pyenv/bin/pip install  pymssql==2.2.5
`

The error message is:

   pymssql._mssql.MSSQLDatabaseException: (271, b'The column "Hash" cannot be modified because it is either a computed column or is the result of a UNION operator.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20599, severity 11:\nunrecognized msgno\n')

The example below uses column_ids to exclude the computed Hash column from the bulk insert set.
I get the same error if I use a dictionary instead of array and column_ids.

It appears that this column is correctly excluded in the binary installation but not in the no-binary version.

I believe I need the no-binary version in order to use kerberos for mssql authentication.

**To Reproduce**
import pymssql
import os

SERVER = os.getenv("SERVER")
PASSWORD = os.getenv("PASSWORD")
USER = os.getenv("USER")
DATABASE = os.getenv("DATABASE")

conn = pymssql.connect(
    server=SERVER,
    user=USER,
    password=PASSWORD,
    database=DATABASE,
    autocommit=True)

conn.cursor().execute("""
  IF OBJECT_ID('dbo.tstBCPComputedColumn') IS NOT NULL
    drop table [dbo].[tstBCPComputedColumn];
  create TABLE [dbo].[tstBCPComputedColumn] (
       Id int not null identity(1,1) UNIQUE,
       Code varchar(4096) not null, 
       Format varchar(10) not null default 'xml', 
       Hash 
           AS CAST(hashbytes('SHA1',[Code]) AS VARBINARY(20))
           PERSISTED NOT NULL,
       DateInserted DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
       CreatedBy varchar(30) NOT NULL DEFAULT CURRENT_USER,
       CONSTRAINT pk_enumTestBCPComputedColumn PRIMARY KEY(Id))
    """)
conn.commit()

batch = [[None, 'Code0', 'xml', '2022-09-14 13:00:05.720', 'guest']]
column_ids = [1, 2, 3, 5, 6] # Skips Hash column

"""Following blows up
"""
conn.bulk_copy(f"{DATABASE}.dbo.tstBCPComputedColumn",
               batch,
               column_ids,
               batch_size=1,
               fire_triggers=True,
               check_constraints=True)
print("OK")

**Expected behavior**
Should print OK on success or 20599 error on failure.

**Current Behavior**
Throws error:
pymssql._mssql.MSSQLDatabaseException: (271, b'The column "Hash" cannot be modified because it is either a computed column or is the result of a UNION operator.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20599, severity 11:\nunrecognized msgno\n')

**Context (Environment)**

- Python version: Python 3.7.4
- Ubuntu 20.04.3 LTS 20.04 focal
- FreeTDS 1.1.6-1.1
# Freetds entry
[BOS-DBRESEARCH01]
	host = BOS-DBRESEARCH01
	port = 1433
	tds version = 7.4

 - please include the output of the following command:
    `/<path to your python>/python -c "import pymssql; print(pymssql.version_info())"`

System:
platform.system()       : Linux
platform.architecture() : ('64bit', '')
platform.libc_ver()     : ('glibc', '2.10')
Python:
sys.version             : 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0]
pymssql:
VERSION            : (2, 2, 5)
version            : 2.2.5
full_version       : 2.2.5
dbversion          : freetds v1.1.6
_mssql:
VERSION            : (2, 2, 5)
version            : 2.2.5
full_version       : 2.2.5
dbversion          : freetds v1.1.6
login_timeout      : 60
min_error_severity : 6

**Comment by termim** [comment]
Wheels on PyPI for 2.2.5 use FreeTDS-1.3.9 but your system shows 1.1.6.
Please try it with FreeTDS-1.3.9 or the latest one and report back.

**Comment by markweissman** [comment]
This worked with 2.2.5 and freeTDS 1.3.9 when we built pymssql.
We were able to get this to work with kerberos and it fixed the computed column issue.
