### ISSUE TITLE
No Kerberos support in manylinux_2_24 wheel

### ISSUE THREAD

**Issue by JCoder01** [pymssql/pymssql#776]
**Describe the bug**
Kerberos auth doesn't work in v2.2.5 manylinux_2_24 wheel 

**To Reproduce**
run
```shell
pip install https://files.pythonhosted.org/packages/81/16/d209a81027f66a9d0a4010f451add2ad0e1664f37a8a4aba9ab378de6c30/pymssql-2.2.5-cp37-cp37m-manylinux_2_24_x86_64.whl
```
on supported platform and attempt to connect to a database without username/password

**Expected behavior**
If kerberos is correctly configured, you get a successful connection.

**Current Behavior**
Returns Connection Error when manylinux 2_24 wheel is used. 
If you install pymssql from the 2_17 manylinux2014 wheel, it works as expected.

**Context (Environment)**
 - What are the OS, Python and FreeTDS versions?
   Ubuntu 20.04, Py 3.7, FreeTDS 1.3.9
  - please include the output of the following command:
    `/<path to your python>/python -c "import pymssql; print(pymssql.version_info())"`
```
System:
platform.system()       : Linux
platform.architecture() : ('64bit', '')
platform.libc_ver()     : ('glibc', '2.10')
Python:
sys.version             : 3.7.4 (default, Aug 13 2019, 20:35:49)
[GCC 7.3.0]
pymssql:
VERSION            : (2, 2, 5)
version            : 2.2.5
full_version       : 2.2.5
dbversion          : freetds v1.3.9
_mssql:
VERSION            : (2, 2, 5)
version            : 2.2.5
full_version       : 2.2.5
dbversion          : freetds v1.3.9
login_timeout      : 60
min_error_severity : 6
```
**Additional context**

The initial problem is that the quay.io/pypa/manylinux_2_24_x86_64 container image does not include `libkrb5-dev` so when compiling FreeTDS on this platform, it is not built with krb5 support from local test build log shows `gss_init_sec_context... no`
```
checking for library containing gethostbyname... none required
checking for library containing gss_init_sec_context... no
checking for error_message... no
```
If you install krb5-dev (`apt-get install libkrb5-dev`) and the run `dev/build_manylinux_wheels.sh` FreeTDS builds with krb5 support:
```
checking for library containing gethostbyname... none required
checking for library containing gss_init_sec_context... -lgssapi_krb5
checking for error_message... no
```
This lines up with the output you see when building with quay.io/pypa/manylinux2014_x86_64 container image.

BUT, then pymssql fail to import:
```
ImportError while loading conftest '/pymssql/tests/conftest.py'.
tests/conftest.py:23: in <module>
    import tests.helpers as th
tests/helpers.py:23: in <module>
    from pymssql import _mssql
/opt/_internal/cpython-3.6.15/lib/python3.6/site-packages/pymssql/__init__.py:3: in <module>
    from ._pymssql import *
src/pymssql/_pymssql.pyx:1: in init pymssql._pymssql
    """DB-SIG compliant module for communicating with MS SQL servers"""
E   ImportError: /opt/_internal/cpython-3.6.15/lib/python3.6/site-packages/pymssql/_mssql.cpython-36m-x86_64-linux-gnu.so: undefined symbol: gss_release_name
```

**Comment by JCoder01** [comment]
This seems to be caused by this same issue outlined here. 
https://stackoverflow.com/questions/26267788/linking-fails-with-gcc-4-8-2-ld-2-24-succeeds-with-gcc-4-4-7-ld-2-20
Ensuring krb5 is linked, solves the issue in my local tests

**Comment by termim** [comment]
> This seems to be caused by this same issue outlined here. https://stackoverflow.com/questions/26267788/linking-fails-with-gcc-4-8-2-ld-2-24-succeeds-with-gcc-4-4-7-ld-2-20 Ensuring krb5 is linked, solves the issue in my local tests

I do not think so. As you rightfully noticed the issue is that krb5 support is missing during compilation not the linkage process.
Anyway, great analysis, thank you!
