### ISSUE TITLE
Support Cross Database Joins

### ISSUE THREAD

**Issue by jayceslesar** [pymssql/pymssql#779]
Why does this wrapper not support cross database joins?

**Comment by termim** [comment]
No

**Comment by jayceslesar** [comment]
Is there not a way around it? I can connect to my server without specifying a database and am assuming I can just specify the database within that server and join against another database in my server?  And why just respond with "No"?

**Comment by termim** [comment]
Sorry for the too short answer. It is obvious IMHO:

Because nobody who cares about cross database joins submitted a PR which implements/documents this functionality.
