### ISSUE TITLE
Wheels for Python 3.6 silently omitted

### ISSUE THREAD

**Issue by kamil-certat** [pymssql/pymssql#787]
With publishing the wheels for Python 3.11, the wheel for Python 3.6 was removed from the wheel building list (https://github.com/pymssql/pymssql/commit/7cf41348b5829b64f65da0ba43cd76010064451f) and not thous provided to PyPI. This make systems still relying on the Python 3.6 to try to build from source.

I was going through the Changelog and git history, and I didn't find any information about dropping support for 3.6, just removing it from CI due to technical issues with the intention to keep it built (https://github.com/pymssql/pymssql/commit/c16e409a38606d7eb3f7b481088a373f8efce33b). 

I'd like to ask if it's a decision to drop Python 3.6 support, or just the wheel building?

**Comment by termim** [comment]
Python 3.6 is EOL for about a year now.
Do you still need to support it?
