### ISSUE TITLE
Enforce SSL

### ISSUE THREAD

**Issue by cernym43** [pymssql/pymssql#797]
Is there any way to tell `pymssql` to always use an encrypted connection? Some drivers accept `Encrypt=yes` in the connection string.

Thank you!

**Comment by MikeTerekhov** [comment]
103042ff80e790a6d8bd0fc2ac977ee0d177360c - added `encription` parameter with possible values `off`, `request` and `require`.

**Comment by FelixGSE** [comment]
Hi, I saw you made the mentioned commit @termim. It seems this feature didn't make it into v.2.2.8. Is there any ETA when is will be released?
