### ISSUE TITLE
Import of pymssql on Centos fails to find libsydbd.so.5

### ISSUE THREAD

**Issue by pymssql-issue-migrator** [pymssql/pymssql#8]
_From [clwaters](https://code.google.com/u/110202252264561063723/) on May 14, 2010 16:57:31_

What steps will reproduce the problem? 1. Build from current source 1.9.908
2. import pymssql; What is the expected output? What do you see instead? Python 2.6.5 ( r265 :79063, May 14 2010, 12:02:51) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-46)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import pymssql;
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: libsybdb.so.5: cannot open shared object file: No such file or 
> > > directory What version of the product are you using? On what operating system? 1.9.908
> > > CentOS release 5.4 (Final)
> > > Linux centreon 2.6.18-164.15.1.el5 #1 SMP Wed Mar 17 11:30:06 EDT 2010 
> > > x86_64 x86_64 x86_64 GNU/Linux Please provide any additional information below. This is for python2.6 which was built from source using the make altinstall 
> > > build command so that it may live side by side with the default 2.4 that 
> > > comes with CentOs.  That seems to work fine as other modules can be 
> > > imported without error.

Tried to follow the README to build pymssql but it seems incomplete.  Ran  
/path/to/python2.6 setup.py build.  README suggests there should be a tests 
directory that does not see to be created.  Then ran /path/to/python2.6 
setup.py install.  This seems to place the files in the correct location 
for that build.

It appears that although setup.py looks in the /usr/local/lib dir as part 
of the include process, it's not being honored.  A symbolic link to 
/usr/lib64 for /usr/local/lib/libsybdb.so.5 corrects the issue.

_Original issue: http://code.google.com/p/pymssql/issues/detail?id=4_

**Comment by mcescalante** [comment]
I just stumbled back on this issue on CentOS 7.3 because I built FreeTDS from source in `/usr/local/` instead of `/usr/bin` which is where it looks for the link. A simple symbolic link fixed the issue for me:

`ln -s /usr/local/lib/libsybdb.so.5 /usr/lib/libsybdb.so.5`
