### ISSUE TITLE
pymssql version supports python-2.7.5-92.el7_9.x86_64

### ISSUE THREAD

**Issue by jamesakm** [pymssql/pymssql#802]
Which version of pymssql supports python-2.7.5-92 version?

**Comment by korverdev** [comment]
That would be `v2.1.5`. `v2.2.0` dropped support for Python 2, [documented here.](https://github.com/pymssql/pymssql/blob/master/ChangeLog.rst#version-220---2021-04-08---mikhail-terekhov)
