### ISSUE TITLE
DB-Lib error message 20018, severity 14

### ISSUE THREAD

**Issue by liaoxuewei** [pymssql/pymssql#804]
I used to be able to connect to mssql using pymssql normally, but recently, when I used it to connect to other servers, the following error occurred. Based on some issue information, it cannot be resolved.

```
        connect = pymssql.connect("GSSQL009HZ", "edpc_posgp", "pwd",
                                  "db")

```
```
  File "src\pymssql\_pymssql.pyx", line 652, in pymssql._pymssql.connect
pymssql._pymssql.OperationalError: (18456, b"Login failed for user 'edpc_posgp'.DB-Lib error message 20018, severity 14:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (GSSQL009HZ)\nDB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (GSSQL009HZ)\n")
```

**Comment by liaoxuewei** [comment]
https://github.com/pymssql/pymssql/issues/330

**Comment by MikeTerekhov** [comment]
Did solution in #330 solved your problem?

**Comment by liaoxuewei** [comment]
No!

**Comment by liaoxuewei** [comment]
Are there any other ideas?

**Comment by liaoxuewei** [comment]
I'm sorry, it turned out that the database name was written incorrectly, and the error message was not very clear. Sorry to disturb you, it has been resolved.
