### ISSUE TITLE
Entering pandas NaT as a query parameter causes the python environment to stop with a memory access violation

### ISSUE THREAD

**Issue by irreg** [pymssql/pymssql#806]
**Describe the bug**
Entering pandas NaT (indicating that a value of datetime type is missing in pandas) as a query parameter causes the python environment to stop with a memory access violation(0xc0000005)

**To Reproduce**
```py
import pymssql
import pandas as pd
conn = pymssql.connect("127.0.0.1", "user", "password", "tempdb")
cursor = conn.cursor()
#cursor.execute("CREATE TABLE temptable (tempcolumn datetime)")
cursor.execute('INSERT INTO temptable (tempcolumn) VALUES (%(0)s)', {"0": pd.NaT})
```

**Expected behavior**
Python environment does not stop and some error occurs

**Current Behavior**
Python environment stops

**Context (Environment)**
 - Windows 10 64bit, Python 3.8.9, pymssql 2.2.7

**Comment by termim** [comment]
`pymssql` and `MSSQL` know nothing about `pandas` and `pandas.NaT`.
You have to convert `pandas.NaT` something meaningful to your application,
for example to NULL, then it will be returned as None on select.

**Comment by irreg** [comment]
Thanks for  reply,
I don't believe this bug needs to be fixed, but as long as it breaks the execution environment, I think it's better to find out what's going on and clarify if there are any serious problems hiding.

Outlook for Android<https://aka.ms/AAb9ysg>を取得
________________________________
