### ISSUE TITLE
Build packages for all platforms and publish to pypi uniformly, rather than platform-by-platform.

### ISSUE THREAD

**Issue by wangzelin007** [pymssql/pymssql#832]
**Describe the bug**

We rely on pymssql, and the latest version is used by default.
We found that when pymssql is released, the linux version will be released for a while longer than the macos version.
For example, only the macos version is available now, which causes all our pipelines to report errors, because we run these ci in the linux environment.
Is it possible to consider building the wheel packages for all platforms and then upload them to pypi?
![image](https://github.com/pymssql/pymssql/assets/18628534/22c32bf5-47ca-4152-afaa-a2751ff3d66b)
![image](https://github.com/pymssql/pymssql/assets/18628534/2535c690-3f5b-48a0-9970-0b92d76919a5)

**To Reproduce**
Short example reproducing the problem, see http://sscce.org/ for general guidelines.

**Expected behavior**

**Current Behavior**
What happens instead of the expected behavior.

**Context (Environment)**
 - What are the OS, Python and FreeTDS versions?
 - please include the output of the following command:
    `/<path to your python>/python -c "import pymssql; print(pymssql.version_info())"`

**Additional context**

**Comment by FanatoniQ** [comment]
Missing linux whl files for the latest release has broken our CI as well

**Comment by termim** [comment]
If you are building from source, then you need to install dependencies (FreeTDS).

**Comment by scott-c-h** [comment]
@termim - that's not the problem people are alluding to. If you have a CI system setup and you have `"pymssql~=2.2.0"` or similar in `setup.py`, when a new release is pushed with no binaries, or with binaries missing for the platform you are deploying on, pip tries to build from source instead. We don't want to build from source - but currently in PyPI there are still no binaries for any platform other than macos, so everyone is forced to instead pin the previous version `"pymssql==2.2.7"`.

**Comment by vkottler** [comment]
> If you are building from source, then you need to install dependencies (FreeTDS).

It's not normal for any Python software release to provide a source-only distribution when it relies on FFI bindings (compiling C/C++, Rust, etc.). A package installer like `pip` isn't finding any candidate built wheel(s) published to the package index, so it's trying to perform a source install **as a contingency**.

This project seems to _eventually_ provide built wheels to PyPI for a new release, so the question/bug is: **why is an initial source-only release getting published without built wheels?**

A lot of Python software gets installed to machines that are not developer/build workstations, that will have development headers for arbitrary things. When the source-only release is published, automation that's trying to install latest versions of packages can break (lesson learned: pin this package down or try not to use it in the first place).

The obvious action is for the package maintainers to integrate the wheel building into the release publishing, not for the entire rest of the world to install development headers to source build the package (or any other Python package..).

**Comment by wangzelin007** [comment]
> @termim - that's not the problem people are alluding to. If you have a CI system setup and you have `"pymssql~=2.2.0"` or similar in `setup.py`, when a new release is pushed with no binaries, or with binaries missing for the platform you are deploying on, pip tries to build from source instead. We don't want to build from source - but currently in PyPI there are still no binaries for any platform other than macos, so everyone is forced to instead pin the previous version `"pymssql==2.2.7"`.

Totally agree, we never intended to install pymssql from source.
