### ISSUE TITLE
Consider dropping builds for `i686` (32-bit x86)

### ISSUE THREAD

**Issue by korverdev** [pymssql/pymssql#841]
To my knowledge, no company manufactures an x86 32-bit processor that isn't EOL. No fully up-to-date, supported Windows or Mac distribution supports 32-bit processors. While you can find support on the Linux side of things, I'd be very surprised if there are still a large group of users out there on 32-bit x86.

Wanted to get people's thoughts on dropping support for this to limit the number of platforms that need to be accounted for and save CI/CD time. I'd be happy to submit a PR for this if we'd like to make this change.

**Comment by termim** [comment]
It seems i686 is still used  - https://github.com/pymssql/pymssql/issues/839#issuecomment-1683039248
