### ISSUE TITLE
The current bundled FreeTDS version contains a bug that hinders proper hostname validation. Updating to version 1.4.2 is necessary to address this issue

### ISSUE THREAD

**Issue by FelixGSE** [pymssql/pymssql#847]
I've come across a bug in FreeTDS that inhibits proper hostname validation. This issue arises when the hostname provided through the server parameter is present in SANs (Subject Alternative Names) but doesn't match the Common Name (CN). For a more detailed explanation, please check out the [related issue](https://github.com/FreeTDS/freetds/issues/503#issuecomment-1736308579).

The bug has been resolved and and the fix has been included in FreeTDS version 1.4.2. To ensure proper hostname validation in PyMSSQL, It would be great if you update the bundled FreeTDS version to a version >=1.4.2.

**Comment by gordthompson** [comment]
Fixed in version 2.2.9.
