### ISSUE TITLE
Unexpected keyword argument 'read_only'

### ISSUE THREAD

**Issue by skryzh** [pymssql/pymssql#862]
**Describe the bug**
Hi, I'm trying to use read_only parameter with latest version, however it seems that this parameter is not implemented.
It  raises an error: 
```File src\\pymssql\\_pymssql.pyx:593, in pymssql._pymssql.connect()

TypeError: connect() got an unexpected keyword argument 'read_only'
```
or
```
File src\\pymssql\\_mssql.pyx:2109, in pymssql._mssql.connect()

File src\\pymssql\\_mssql.pyx:599, in pymssql._mssql.MSSQLConnection.__init__()

TypeError: __init__() got an unexpected keyword argument 'read_only'
``` 
code example:
```
pymssql.connect(..., read_only=True, ...)
pymssql._mssql.connect(..., read_only=True, ...)
pymssql._pymssql.connect(..., read_only=True, ...)
```

**Expected behavior**
I need an analog for ApplicationIntent=ReadOnly 

**Current Behavior**
Code don't work

**Context (Environment)**
```
System:
platform.system()       : Windows
platform.architecture() : ('64bit', 'WindowsPE')
Python:
sys.version             : 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
pymssql:
VERSION            : (2, 2, 10)
version            : 2.2.10
full_version       : 2.2.10
dbversion          : freetds v1.4.3
_mssql:
VERSION            : (2, 2, 10)
version            : 2.2.10
full_version       : 2.2.10
dbversion          : freetds v1.4.3
login_timeout      : 60
min_error_severity : 6
```
**Additional context**
documentations with read_only  parameter:
https://pymssql.readthedocs.io/en/latest/ref/_mssql.html#mssql.MSSQLConnection
https://pymssql.readthedocs.io/en/latest/ref/pymssql.html

**Comment by termim** [comment]
It is in the master branch and is not released yet.

**Comment by Gobi2511** [comment]
May I know when will this be released? It would be better if you share the version and ETA.
