### ISSUE TITLE
ImportError in pymssql on Macbook Air M2: Missing Symbol '_bcp_batch'

### ISSUE THREAD

**Issue by girithodu** [pymssql/pymssql#874]
Describe the bug

Encountering an ImportError when attempting to use pymssql on a Macbook Air M2 chip. The error specifically mentions a missing symbol "_bcp_batch" in the flat namespace.

To Reproduce

`import pymssql`
Expected behavior
The library should import successfully without encountering an ImportError.

Current Behavior

Encountering the following ImportError:
`ImportError: dlopen(/opt/homebrew/lib/python3.11/site-packages/pymssql/_mssql.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_bcp_batch'`

Context (Environment)

OS:macOS Sonoma Version 14.2 (Macbook Air M2 chip)
Python Version: 3.11
FreeTDS Version: 1.4.10

Additional context

Using the sql driver in my fast api application

**Comment by termim** [comment]
The problem is similar to what is described [here](https://stackoverflow.com/questions/29777337/macosx-boost-python-pyftgl-symbol-not-found-expected-in-flat-namespace). Try to compile pymssql from source using hint from https://github.com/pymssql/pymssql/issues/769
