### ISSUE TITLE
Mac M3  Building wheel for pymssql (pyproject.toml) ... erro

### ISSUE THREAD

**Issue by anandlingaraj** [pymssql/pymssql#883]
Unable to install on 3.9 and 3.12 on Mac M3 Max

Have a fastpi bootstrapped.
pip install  pymssql

anandl@pegasus Desktop % source /Users/anandl/projects/ROmans/Romans/.venv9/bin/activate
pip install pymssql
Collecting pymssql
  Using cached pymssql-2.2.11.tar.gz (172 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pymssql
  Building wheel for pymssql (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pymssql (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [70 lines of output]
      prefix='/opt/homebrew/opt/freetds'
      setup.py: platform.system() => Darwin
      setup.py: platform.architecture() => ('64bit', '')
      setup.py: platform.libc_ver() => ('', '')
      setup.py: include_dirs => ['/opt/homebrew/opt/freetds/include']
      setup.py: library_dirs => ['/opt/homebrew/opt/freetds/lib']
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-x86_64-cpython-39
      creating build/lib.macosx-10.9-x86_64-cpython-39/pymssql
      copying src/pymssql/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-39/pymssql
      running build_ext
      warning: src/pymssql/_mssql.pyx:82:0: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:275:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:344:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:849:8: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:937:8: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:1031:12: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:1405:16: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:1739:8: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      Compiling src/pymssql/_mssql.pyx because it changed.
      [1/1] Cythonizing src/pymssql/_mssql.pyx
      building 'pymssql._mssql' extension
      creating build/temp.macosx-10.9-x86_64-cpython-39
      creating build/temp.macosx-10.9-x86_64-cpython-39/src
      creating build/temp.macosx-10.9-x86_64-cpython-39/src/pymssql
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/opt/homebrew/opt/freetds/include -I/Users/anandl/projects/ROmans/Romans/.venv9/include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c src/pymssql/_mssql.c -o build/temp.macosx-10.9-x86_64-cpython-39/src/pymssql/_mssql.o -DMSDBLIB
      src/pymssql/_mssql.c:43402:21: warning: fallthrough annotation in unreachable code [-Wunreachable-code-fallthrough]
                          CYTHON_FALLTHROUGH;
                          ^
      src/pymssql/_mssql.c:564:34: note: expanded from macro 'CYTHON_FALLTHROUGH'
            #define CYTHON_FALLTHROUGH __attribute__((fallthrough))
                                       ^
      src/pymssql/_mssql.c:43413:21: warning: fallthrough annotation in unreachable code [-Wunreachable-code-fallthrough]
                          CYTHON_FALLTHROUGH;
                          ^
      src/pymssql/_mssql.c:564:34: note: expanded from macro 'CYTHON_FALLTHROUGH'
            #define CYTHON_FALLTHROUGH __attribute__((fallthrough))
                                       ^
      src/pymssql/_mssql.c:43774:21: warning: fallthrough annotation in unreachable code [-Wunreachable-code-fallthrough]
                          CYTHON_FALLTHROUGH;
                          ^
      src/pymssql/_mssql.c:564:34: note: expanded from macro 'CYTHON_FALLTHROUGH'
            #define CYTHON_FALLTHROUGH __attribute__((fallthrough))
                                       ^
      src/pymssql/_mssql.c:43780:21: warning: fallthrough annotation in unreachable code [-Wunreachable-code-fallthrough]
                          CYTHON_FALLTHROUGH;
                          ^
      src/pymssql/_mssql.c:564:34: note: expanded from macro 'CYTHON_FALLTHROUGH'
            #define CYTHON_FALLTHROUGH __attribute__((fallthrough))
                                       ^
      src/pymssql/_mssql.c:44400:21: warning: fallthrough annotation in unreachable code [-Wunreachable-code-fallthrough]
                          CYTHON_FALLTHROUGH;
                          ^
      src/pymssql/_mssql.c:564:34: note: expanded from macro 'CYTHON_FALLTHROUGH'
            #define CYTHON_FALLTHROUGH __attribute__((fallthrough))
                                       ^
      src/pymssql/_mssql.c:44411:21: warning: fallthrough annotation in unreachable code [-Wunreachable-code-fallthrough]
                          CYTHON_FALLTHROUGH;
                          ^
      src/pymssql/_mssql.c:564:34: note: expanded from macro 'CYTHON_FALLTHROUGH'
            #define CYTHON_FALLTHROUGH __attribute__((fallthrough))
                                       ^
      6 warnings generated.
      gcc -bundle -undefined dynamic_lookup -arch x86_64 -g build/temp.macosx-10.9-x86_64-cpython-39/src/pymssql/_mssql.o -L/opt/homebrew/opt/freetds/lib -lsybdb -lgssapi_krb5 -lkrb5 -lssl -lcrypto -o build/lib.macosx-10.9-x86_64-cpython-39/pymssql/_mssql.cpython-39-darwin.so
      ld: library 'ssl' not found
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pymssql
Failed to build pymssql
ERROR: Could not build wheels for pymssql, which is required to install pyproject.toml-based projects

**Context (Environment)**
 - What are the OS, Python and FreeTDS versions?
 - MAC OS SONOMA 14.3.1 (23D60) &  Apple M3 Max
 - 
Compile-time settings (established with the "configure" script)
                            Version: freetds v1.4.10
             freetds.conf directory: /opt/homebrew/etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: yes
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 7.3
                              iODBC: no
                           unixodbc: yes
              SSPI "trusted" logins: no
                           Kerberos: yes
                            OpenSSL: yes
                             GnuTLS: no
                               MARS: yes

 - please include the output of the following command:
    python -c "import pymssql; print(pymssql.version_info())"`

(.venv9) anandl@pegasus Desktop % python -c "import pymssql; print(pymssql.version_info())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pymssql'

**Comment by termim** [comment]
> gcc -bundle -undefined dynamic_lookup -arch x86_64 -g build/temp.macosx-10.9-x86_64-cpython-39/src/pymssql/_mssql.o -L/opt/homebrew/opt/freetds/lib -lsybdb -lgssapi_krb5 -lkrb5 -lssl -lcrypto -o build/lib.macosx-10.9-x86_64-cpython-39/pymssql/_mssql.cpython-39-darwin.so
**> ld: library 'ssl' not found**
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> error: command '/usr/bin/gcc' failed with exit code 1
> [

You do not have openssl installed.

**Comment by anandlingaraj** [comment]
> > gcc -bundle -undefined dynamic_lookup -arch x86_64 -g build/temp.macosx-10.9-x86_64-cpython-39/src/pymssql/_mssql.o -L/opt/homebrew/opt/freetds/lib -lsybdb -lgssapi_krb5 -lkrb5 -lssl -lcrypto -o build/lib.macosx-10.9-x86_64-cpython-39/pymssql/_mssql.cpython-39-darwin.so
> > **> ld: library 'ssl' not found**
> > clang: error: linker command failed with exit code 1 (use -v to see invocation)
> > error: command '/usr/bin/gcc' failed with exit code 1
> > [
> 
> You do not have openssl installed.

Thanks
I did notice that and did fix it with 
1. brew install freetds
2. brew install openssl
3. export LDFLAGS="-L/opt/homebrew/Cellar/freetds/1.4.10/lib -L/opt/homebrew/Cellar/openssl@3/3.2.1/lib"
4. export CFLAGS="-I/opt/homebrew/Cellar/freetds/1.4.10/include"
5. pip install pymssql

end up with 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/grumpy/projects/ROmans/Romans/.venv/lib/python3.9/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/Users/grumpy/projects/ROmans/Romans/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/Users/grumpy/projects/ROmans/Romans/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/Users/grumpy/projects/ROmans/Romans/.venv/lib/python3.9/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/grumpy/projects/ROmans/Romans/.venv/lib/python3.9/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/Users/grumpy/projects/ROmans/Romans/.venv/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/grumpy/projects/ROmans/Romans/main.py", line 10, in <module>
    from acts.routes.BIAPIRoutes import BIAPIRoutes
  File "/Users/grumpy/projects/ROmans/Romans/acts/routes/BIAPIRoutes.py", line 7, in <module>
    from acts.services.DatabaseConnectorService import get_connection_by_id
  File "/Users/grumpy/projects/ROmans/Romans/acts/services/DatabaseConnectorService.py", line 20, in <module>
    import pymssql
  File "/Users/grumpy/projects/ROmans/Romans/.venv/lib/python3.9/site-packages/pymssql/__init__.py", line 3, in <module>
    from ._pymssql import *
  **File "src/pymssql/_pymssql.pyx", line 1, in init pymssql._pymssql
ImportError: dlopen(/Users/grumpy/projects/ROmans/Romans/.venv/lib/python3.9/site-packages/pymssql/_mssql.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_bcp_batch'**

**Comment by anandlingaraj** [comment]
grumpy@pegasus pymssql % ls
__init__.py			_mssql.cpython-39-darwin.so
__pycache__			_pymssql.cpython-39-darwin.so
grumpy@pegasus pymssql % pwd
/Users/grumpy/projects/ROmans/Romans/.venv/lib/python3.9/site-packages/pymssql
grumpy@pegasus pymssql %

**Comment by termim** [comment]
It seems you are using system python but FreeTDS from the brew. They could be compiled by different compilers which results in such an error.
