### ISSUE TITLE
cannot connect to one particular, SSH LocalForward-ed SQL server

### ISSUE THREAD

**Issue by bluppfisk** [pymssql/pymssql#888]
**Describe the bug**
I need to access an SQL server that is in a network that I do not directly have access to. However, I have SSH access to a host that does have access to this SQL server. So I have used an SSH LocalForward to forward the SQL server's port locally on 127.0.2.3:11433. However, pymssql won't connect and throws an OperationalError.

**To Reproduce**
It is hard to reproduce as I have no idea about the version or configuration of this particular SQL server, and it does work with other SQL servers when I use local port forwarding.

**Expected behavior**
I expect pymssql to connect to this instance.

**Current Behavior**
It throws an OperationalError

**Context (Environment)**
OS: Ubuntu Linux 23.10
Python: 3.11.6
System:
platform.system()       : Linux
platform.architecture() : ('64bit', 'ELF')
platform.libc_ver()     : ('glibc', '2.31')
Python:
sys.version             : 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
pymssql:
VERSION            : (2, 2, 5)
version            : 2.2.5
full_version       : 2.2.5
dbversion          : freetds v1.3.9
_mssql:
VERSION            : (2, 2, 5)
version            : 2.2.5
full_version       : 2.2.5
dbversion          : freetds v1.3.9
login_timeout      : 60
min_error_severity : 6

**Additional context**
* When using the nodeJS-based MSSQL commandline utility, I can connect to the SSH-forwarded SQL server.
* When going onto the SSH server and using pymssql there, I can connect to the SQL server directly using the same python code
* I have done the above successfully in other situations with a different network and different database server, so this problem only seems to occur with this particular SQL server, with pymssql and when using SSH port forwarding.
* Question first asked on StackOverflow https://stackoverflow.com/questions/78316183/pymssql-cannot-connect-to-an-ssh-forwarded-sql-server

**Comment by termim** [comment]
First I'd update to the latest pymssql version - 2.3.0.
Then, I'd try different tds_version like here #860.
If it still fails, then set environment variable TDSDUMP/TDSCONFIIG and try to analyze the logs. see https://www.freetds.org/userguide/logging.html#Environment.

**Comment by bluppfisk** [comment]
Thank you for your answer. The latest pymssql version did not help, but setting tds_version to 7.0 did.
