### ISSUE TITLE
Execute many with zeros

### ISSUE THREAD

**Issue by pymssql-issue-migrator** [pymssql/pymssql#89]
_From [schwar...@gmail.com](https://code.google.com/u/104080671825704461099/) on March 02, 2012 09:38:15_

What steps will reproduce the problem? (The attached script will reproduce)
1. create a database with a primary key of an integer
2. generate a list of integers that are unordered with a zero in the list
3. executemany to insert the list does not work (inserting one by one will) What is the expected output? What do you see instead? Inserting should work the same with execute and executemany What version of the product are you using? On what operating system? pymssql: 2.0.0, python 2.4, connecting to sql server 2008R2, on solaris 5.10 Please provide any additional information below.

**Attachment:** [zerosinexecmany.py](http://code.google.com/p/pymssql/issues/detail?id=85)

_Original issue: http://code.google.com/p/pymssql/issues/detail?id=85_

**Comment by swn1** [comment]
I just hit this.  Took me a while to understand that "what makes zero special?" wasn't the right question to be asking.  I agree with the "side note" above -- it would be great if incorrect use of execute with single replacement didn't almost always work.
