### ISSUE TITLE
pymssql no longer works for Sybase databases post versions >=2.2.9

### ISSUE THREAD

**Issue by s7clarke10** [pymssql/pymssql#890]
**Describe the bug**
pymssql works well against both MSSQL and Sybase databases. The following Singer / Meltano tap [tap-sybasel](https://github.com/s7clarke10/tap-sybase) to extract data from Sybase databases work well on version 2.2.7 of pymssql.

Version 2.2.9 and onwards, I can no longer connect to Sybase, I receive the following error message.

I would appreciate some guidance to why the following error message is happening upon connection and how it may be resolved. For now I am stuck on an older version of pymssql.

```shell
CRITICAL (156, b"Incorrect syntax near the keyword 'AS'.\nDB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 1, severity 11:\nunrecognized msgno (SERVER_NAME)\n")
Traceback (most recent call last):
  File "/home/me/meltano-projects/salesforce_pot/.meltano/extractors/tap-sybase/venv/bin/tap-sybase", line 8, in <module>
    sys.exit(main())
  File "/home/me/meltano-projects/salesforce_pot/.meltano/extractors/tap-sybase/venv/lib/python3.8/site-packages/tap_sybase/__init__.py", line 804, in main
    raise exc
  File "/home/me/meltano-projects/salesforce_pot/.meltano/extractors/tap-sybase/venv/lib/python3.8/site-packages/tap_sybase/__init__.py", line 801, in main
    main_impl()
  File "/home/me/meltano-projects/salesforce_pot/.meltano/extractors/tap-sybase/venv/lib/python3.8/site-packages/tap_sybase/__init__.py", line 783, in main_impl
    mssql_conn = MSSQLConnection(args.config)
  File "/home/me/meltano-projects/salesforce_pot/.meltano/extractors/tap-sybase/venv/lib/python3.8/site-packages/tap_sybase/connection.py", line 47, in __init__
    conn = pymssql._mssql.connect(**args)
  File "src/pymssql/_mssql.pyx", line 2155, in pymssql._mssql.connect
  File "src/pymssql/_mssql.pyx", line 712, in pymssql._mssql.MSSQLConnection.__init__
  File "src/pymssql/_mssql.pyx", line 1881, in pymssql._mssql.maybe_raise_MSSQLDatabaseException
  File "src/pymssql/_mssql.pyx", line 1898, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (156, b"Incorrect syntax near the keyword 'AS'.\nDB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 1, severity 11:\nunrecognized msgno (SERVER_NAME)\n")
```

**To Reproduce**
If I pin the version to 2.2.7 - I can connect with sybase databases. If I change my version of pymssql to 2.2.9 I receive an error like that above.

I am also surprised because it says - unrecognised msgno(SERVER_NAME) - the value for SERVER_NAME is the redacted host argument that I passed to the connection.

**Non-Working Context (Environment)**
 - This is running on Linux RHEL 8,  Python 3.8 and FreeTDS versions which is bundled with pymssql in pypi.
 - pymssql version info
- System:
platform.system()       : Linux
platform.architecture() : ('64bit', 'ELF')
platform.libc_ver()     : ('glibc', '2.28')
Python:
sys.version             : 3.8.16 (default, May 31 2023, 12:44:21) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-18)]
pymssql:
VERSION            : (2, 3, 0)
version            : 2.3.0
full_version       : 2.3.0
dbversion          : freetds v1.4.10
_mssql:
VERSION            : (2, 3, 0)
version            : 2.3.0
full_version       : 2.3.0
dbversion          : freetds v1.4.10
login_timeout      : 60
min_error_severity : 6

**Working Context (Environment)**
- System:
platform.system()       : Linux
platform.architecture() : ('64bit', 'ELF')
platform.libc_ver()     : ('glibc', '2.28')
Python:
sys.version             : 3.8.16 (default, May 31 2023, 12:44:21) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-18)]
pymssql:
VERSION            : (2, 2, 7)
version            : 2.2.7
full_version       : 2.2.7
dbversion          : freetds v1.3.13
_mssql:
VERSION            : (2, 2, 7)
version            : 2.2.7
full_version       : 2.2.7
dbversion          : freetds v1.3.13
login_timeout      : 60
min_error_severity : 6

**Additional context**

The actual connection code made to pymssql is located here https://github.com/s7clarke10/tap-sybase/blob/46cd1d39273a5c86558088dd2df801f544430d4d/tap_sybase/connection.py#L30C1-L50C21 in this tap code.

```python
class MSSQLConnection(pymssql.Connection):
    def __init__(self, config):
        args = {
            "user": config["user"],
            "password": config["password"],
            "server": config["host"],
            "database": config["database"],
            "charset": config.get("characterset", "utf8"),
            "port": config.get("port", "2638"),
            "tds_version": config.get("tds_version", None),
            "conn_properties": '',
        }
        conn = pymssql._mssql.connect(**args)
        super().__init__(conn, False, True)


    def __enter__(self):
        return self


    def __exit__(self, *exc_info):
        del exc_info
        self.close()
```

With the printouts, I can see the version of freetds has increased in the different versions published to pypi. I am unsure if the change in behaviour is related to pymssql or the underlying freetds driver.

**Comment by mjsqu** [comment]
After a deep-dive into this, using the option:

```
environ['TDSDUMP'] = 'stdout'
```

We inspected the logs and found differences in the way that the `tds_setup_connection` works between TDS versions 1.3 and 1.4:

## TDSDUMP FreeTDS v1.3.13 - pymssql 2.2.8

```
0000 0f 01 00 29 00 00 00 00-21 1c 00 00 00 00 73 65 |...).... !.....se|
0010 6c 65 63 74 20 40 40 73-70 69 64 20 75 73 65 20 |lect @@s pid use |
0020 6e 6d 64 73 5f 74 73 74-32                      |nmds_tst 2|
```

## TDSDUMP FreeTDS v1.4.3 - pymssql 2.2.9

```
0000 0f 01 00 7f 00 00 00 00-21 72 00 00 00 00 53 45 |........ !r....SE|
0010 4c 45 43 54 20 40 40 73-70 69 64 20 41 53 20 73 |LECT @@s pid AS s|
0020 70 69 64 20 55 53 45 20-6e 6d 64 73 5f 74 73 74 |pid USE  nmds_tst|
0030 32 20 53 45 4c 45 43 54-20 43 41 53 54 28 27 61 |2 SELECT  CAST('a|
0040 62 63 27 20 41 53 20 4e-56 41 52 43 48 41 52 28 |bc' AS N VARCHAR(|
0050 33 29 29 20 41 53 20 6e-76 63 2c 20 43 41 53 54 |3)) AS n vc, CAST|
0060 28 27 78 79 7a 27 20 41-53 20 55 4e 49 56 41 52 |('xyz' A S UNIVAR|
0070 43 48 41 52 28 33 29 29-20 41 53 20 75 76 63    |CHAR(3))  AS uvc|
```

Searching in the FreeTDS codebase for the 'abc' and 'xyz' strings used in this query, yields the function `tds_setup_connection`. In both FreeTDS versions, a query is run on connection that begins with:

```
SELECT @@spid AS spid
```

In v1.4.3, depending on a condition, the errant code (for our old Sybase DB) is appended:

```
	if (IS_TDS50(tds->conn)) {
		strcat(str, " SELECT CAST('abc' AS NVARCHAR(3)) AS nvc, CAST('xyz' AS UNIVARCHAR(3)) AS uvc");
		parse_results = true;
	}
```

This appears to relate to being able to choose a TDS version:
https://www.freetds.org/userguide/ChoosingTdsProtocol.html

> The TDS protocol version is probably something you'd rather not know even existed, much less something you'd have to choose. 

😆 😆 

We have quite an old Sybase version 😕 - 2003

**Comment by mjsqu** [comment]
Recommend closing - pymssql 2.3.0 works when you set the config option tds_version = 4.2 for our ancient Sybase DB 😄 

@s7clarke10 - could you test please?

**Comment by mjsqu** [comment]
Our Sybase version was current when Black Eyed Peas released "Where Is The Love"...

**Comment by termim** [comment]
@mjsqu :+1:
