### ISSUE TITLE
Pymssql works with Sybase with new version of FreeTDS - Recommend using latest stable

### ISSUE THREAD

**Issue by s7clarke10** [pymssql/pymssql#895]
**Describe the bug**
The following closed issue noted an issue with Sybase connections related to FreeTDS. https://github.com/pymssql/pymssql/issues/890 .

Subsequent discussion with Freddy who maintains FreeTDS has resulted a new release of FreeTDS which work with Pymssql and older Sybase databases. We no longer have to change the TDS protocol version for Sybase to version "4.2" - this is important to avoid truncation of varchar datatypes.

Discussion: https://github.com/FreeTDS/freetds/issues/550

Latest Fixed Version:  1.4.13 - https://www.freetds.org/files/stable/freetds-1.4.13.tar.gz

**Expected behavior**
When the next release of Pymssql is built will it pull the latest FreeTDS release? I would imagine Freddy will create will create a release in the next week or so based on the latest stable release.

If this is the case, I think there is no action required - the next release of pymssql will work with older Sybase versions again.

Are you able to please confirm this @termim ?

Thank you.

**Comment by termim** [comment]
I'm trying it now. There some problem with uploading artifacts and openssl in actions. Needs to be fixed before release. What OS/Python you are using?

**Comment by s7clarke10** [comment]
Hi @termim,

I use pymssql on Linux Redhat 8, Ubuntu, and Alphine flavours of Unix/Linux.

I note what I reference was the latest stable release rather than the latest release on their git repo. To do a custom install of FreeTDS. I  used the following build command which appeared to work okay for me.

```bash
python dev/build.py \
    --force-download \
    --freetds-version 1.4.13 \
    --freetds-url https://www.freetds.org/files/stable/ \
    --ws-dir=./freetds \
    --dist-dir=./dist \
    --with-openssl=yes \
    --enable-krb5 \
    --sdist \
    --static-freetds
```
I needed to provide the --freetds-url to point to the stable release.

My main question is once a formal git release is built for FreeTDS (rather just a stable release), will pymssql pick up the latest copy?

**Comment by termim** [comment]
Could you try wheels from https://test.pypi.org/project/pymssql/2.3.1.dev1/#files?

**Comment by s7clarke10** [comment]
Hi @termim,

I installed the wheels installation. It appears to be working as expected - the version you have prepared looks good - Thank you. 

Here were my installation steps.

```shell
pip install -i https://test.pypi.org/simple/ pymssql==2.3.1.dev1 --force
```

The version information presented via this comand

```shell
vscode ➜ /workspaces/python-pymssql-freetds/pymssql (master) $ python -c "import pymssql; print(pymssql.version_info())"
System:
platform.system()       : Linux
platform.architecture() : ('64bit', 'ELF')
platform.libc_ver()     : ('glibc', '2.36')
Python:
sys.version             : 3.8.19 (default, Apr 24 2024, 13:04:15) 
[GCC 12.2.0]
pymssql:
VERSION            : (2, 3, 1)
version            : 2.3.1
full_version       : 2.3.1.dev1
dbversion          : freetds v1.4.13
_mssql:
VERSION            : (2, 3, 1)
version            : 2.3.1
full_version       : 2.3.1.dev1
dbversion          : freetds v1.4.13
login_timeout      : 60
min_error_severity : 6
```

**Comment by termim** [comment]
Thank you!

**Comment by s7clarke10** [comment]
Hi @termim,

Just following up when will there be a production release of pymssql using the latest version of FreeTDS?

I know we tested a test version of the build last month https://test.pypi.org/project/pymssql/2.3.1.dev1/  will we do a release to the main pypi soon e.g. 2.3.1?

I am uncomfortable using a dev release in my Production pipeline, so I am hoping there will be a release soon. Thanks for the work you have done on this 🥇 .

**Comment by github-wenli** [comment]
How to install FreeTDS under windows 11?

**Comment by termim** [comment]
@github-wenli You can check [build.py](https://github.com/pymssql/pymssql/blob/64475fadb58f1847ef2de74b57426cf1ed5515ba/dev/build.py#L109) how to build on Windows.

**Comment by termim** [comment]
@s7clarke10 2.3.1 is out.

**Comment by s7clarke10** [comment]
Brilliant, thank you @termim. I'll look to pick that up this week and test it out 😊🥳.
