### ISSUE TITLE
FLOAT Datatype is mapped as NUMBER

### ISSUE THREAD

**Issue by prakashsivan-deriv** [pymssql/pymssql#910]
**Describe the bug**
The data type for the FLOAT column in the source is incorrectly being interpreted as INT64 (type code 3) when fetching data from the cursor. This discrepancy leads to loss of precision in the data representation.

**To Reproduce**
- Create a table with columns of INT, FLOAT data type in `mssql`
- `execute` a SELECT statement using `cursor`
- Get the `cursor.description`
- You can find both FLOAT & INT column tagged to type code 3 which is `NUMBER`

Code reference - https://github.com/pymssql/pymssql/blob/master/src/pymssql/_mssql.pyx#L1924-L1926
I think this part is the reason

**Expected behavior**
Ideally FLOAT & INT column should not be tagged with same type code

**Current Behavior**
- We are creating a target table by reading the `cursor.description`
- Since INT & FLOAT has the same type code, target table will be created as `INTEGER` type
- This causes issue when the data has FLOAT values

**Context (Environment)**
```
System:
platform.system()       : Linux
platform.architecture() : ('64bit', '')
platform.libc_ver()     : ('glibc', '2.36')
Python:
sys.version             : 3.12.3 (main, Apr 24 2024, 11:28:46) [GCC 12.2.0]
pymssql:
VERSION            : (2, 3, 0)
version            : 2.3.0
full_version       : 2.3.0
dbversion          : freetds v1.4.10
_mssql:
VERSION            : (2, 3, 0)
version            : 2.3.0
full_version       : 2.3.0
dbversion          : freetds v1.4.10
login_timeout      : 60
min_error_severity : 6
```

**Additional context**

**Comment by gordthompson** [comment]
`Cursor.description` is defined in Python's DBAPI spec v2.0 [here](https://peps.python.org/pep-0249/#description). It says

"The `type_code` can be interpreted by comparing it to the [Type Objects](https://peps.python.org/pep-0249/#type-objects) specified in the section below."

The Type Objects section describes the valid values for `type_code`, including:

> STRING type
>     This type object is used to describe columns in a database that are string-based (e.g. CHAR).
> 
> BINARY type
>     This type object is used to describe (long) binary columns in a database (e.g. LONG, RAW, BLOBs).
> 
> NUMBER type
>     This type object is used to describe numeric columns in a database.
> 
> DATETIME type
>     This type object is used to describe date/time columns in a database.
> 
> ROWID type
>     This type object is used to describe the “Row ID” column in a database. 

Note that there is only one type for numeric columns: `NUMBER`

Instead of trying to create the new table from the `Cursor.description`, just create the table using `SELECT … INTO"

```python
crsr.execute("SELECT * INTO new_table FROM (SELECT int_col, float_col FROM old_table WHERE 1=0) subq")
```

**Comment by prakashsivan-deriv** [comment]
@gordthompson Thanks for the details. Need some clarification, how are we deciding to tag FLOAT datatype as `NUMBER` but DECIMAL as datatype as `DECIMAL`

From SQL [documentation](https://learn.microsoft.com/en-us/sql/t-sql/data-types/decimal-and-numeric-transact-sql?view=sql-server-2017)

> decimal and numeric are numeric data types that have a fixed precision and scale. decimal and numeric are synonyms and can be used interchangeably.

The `type_code` references advises to tag NUMERIC columns to NUMBER type

> NUMBER type
> This type object is used to describe numeric columns in a database.

But the code [here](https://github.com/pymssql/pymssql/blob/master/src/pymssql/_mssql.pyx#L1924-L1929) (also copied below) we are tagging FLOAT as NUMBER but DECIMAL as DECIMAL

```
cdef int get_api_coltype(int coltype):
    if coltype in (SQLBIT, SQLINT1, SQLINT2, SQLINT4, SQLINT8, SQLINTN,
            SQLFLT4, SQLFLT8, SQLFLTN):
        return NUMBER
    elif coltype in (SQLMONEY, SQLMONEY4, SQLMONEYN, SQLNUMERIC,
            SQLDECIMAL):
        return DECIMAL
    elif coltype in (SQLDATETIME, SQLDATETIM4, SQLDATETIMN):
        return DATETIME
    elif coltype in (SQLVARCHAR, SQLCHAR, SQLTEXT):
        return STRING
    else:
        return BINARY
```

Also in our case we need to create the table in BQ, so we cannot directly use the `SELECT * INTO`, we have to detect the schema type from description and  decide the equivalent schema for BQ

**Comment by gordthompson** [comment]
Yes, it's a bit strange that pymssql gives DECIMAL special treatment. Neither v1.0 nor v2.0 of the DBAPI spec mention DECIMAL as a column type. However, pymssql is in strict (albeit minimal) compliance with the spec and the code has been that way for over 14 years now.

I also agree that pymssql's `Cursor.description` is not as helpful as it could be. With pymssql we get

```python
crsr.execute("SELECT 1 AS i, CAST('3.14' AS float) AS f, CAST('1.23' AS decimal(18, 4)) AS d")
descr = crsr.description
pprint(descr)
"""
(('i', 3, None, None, None, None, None),
 ('f', 3, None, None, None, None, None),
 ('d', 5, None, None, None, None, None))
"""
```

whereas with pyodbc and msodbcsql17 we get

```python
crsr.execute("SELECT 1 AS i, CAST('3.14' AS float) AS f, CAST('1.23' AS decimal(18, 4)) AS d")
descr = crsr.description
pprint(descr)
"""
(('i', <class 'int'>, None, 10, 10, 0, False),
 ('f', <class 'float'>, None, 53, 53, 0, True),
 ('d', <class 'decimal.Decimal'>, None, 18, 18, 4, True))
"""
```

**Comment by gordthompson** [comment]
In addition, if using pyodbc and msodbcsql17/18 is not a desirable option, [python-tds](https://pypi.org/project/python-tds/) also returns more detailed values

```
(('i', 56, None, None, None, None, 0),
 ('f', 62, None, 8, None, None, 1),
 ('d', 106, None, 9, 18, 4, 1))
```

and the numeric values can be converted to type names using the mappings starting here

https://github.com/denisenkom/pytds/blob/80857132a5fb867f5f766c6f6a643c11c34098ee/src/pytds/tds_base.py#L205

e.g.,

56 → INT4TYPE → int  
62 → FLT8TYPE → float  
106 → DECIMALNTYPE → decimal  

and so on.

**Comment by termim** [comment]
This is not a bug. Python's DB API v2 type system is deliberately vague  as it can't reflect all the types available in all databases. It just gives a hint on how to display query results.
To reflect real column types you need to query database system catalog.

**Comment by dlenski** [comment]
> I also agree that pymssql's `Cursor.description` is not as helpful as perhaps it could be.

It would be possible to replace the `type_code`s in `Cursor.description` with an object that contains more fine-grained TDS type information, in a backwards-compatible way.

```py
# current situation: the type_code is pymssql._pymssql.DBAPIType(3), which == pymssql.NUMBER ,
# but doesn't contain any more fine-grained information
cur.description = ( ('integer_field',  pymssql._pymssql.DBAPIType(3),
                     None, None, None, None, None), )

# improvement: add fine-grained type information to the DbApiTypeCode object
class Better_DbApiTypeCode(int):
    def __new__(cls, db_api_type, tds_type=None, python_type=None):
        return super().__new__(cls, db_api_type)

    def __init__(self, db_api_type, tds_type=None, python_type=None):
        self._tds_type = tds_type
        self._python_type = python_type
        super().__init__()

# using this, we can set a type_code that is still == pymssql.NUMBER, but also
# allows us to determine the fine-grained TDS type when necessary:
cur.description = ( ('integer_field',  Better_DBAPIType(3, 56, int),
                     None, None, None, None, None)

assert DbApiTypeCode(3, 56, int) == pymssql.NUMBER
assert DbApiTypeCode(3, 56, int)._tds_type == 56
assert DbApiTypeCode(3, 56, int)._python_type is int
```
