### ISSUE TITLE
Adaptive Server is unavailable or does not exist (server\instance_name)

### ISSUE THREAD

**Issue by rvan1** [pymssql/pymssql#913]
I'm trying to use airflow MsSqlHook, installed via pip, which depends on pymssql but I get this error which you've heard about before:

> Adaptive Server is unavailable or does not exist (server\instance_name)

Outside of airflow, I can reproduce the issue with a simple py script:

```
export AIRFLOW_CONN_MSSQL_DEFAULT='mssql+pyodbc://user:pwd@server\instance_name:1433/dbase_name'

import pandas as pd
from airflow.providers.microsoft.mssql.hooks.mssql import MsSqlHook

mengine = MsSqlHook('mssql_default').get_sqlalchemy_engine()
sql='SELECT TOP 10 * FROM dbo.mytable]'
df = pd.read_sql(sql, mengine.connect())
print(df.head())
```

There are no network, firewall or permission issues. Connection works fine via sqlcmd and other connection soluitions such as 
create_engine(URL.create("mssql+pyodbc", query={"odbc_connect": conn_params}), echo=False, encoding='utf-8')

We're using mssql express 15.0.4385 and MsSqlHook works ok on server which references default instance and has no instance name. The issue occurs when I try to connect to our server which has a named instance, so it seems like pymssql pkg doesn't understand it.

On the different computers I've tried with, I have pymssql v 2.3.0 and 2.3.1. We also have 2.2.11, but haven't tried with that one.

I haven't tried it directly, but always through MsSqlHook, which is where I need it to work from.

>>> import pymssql; print(pymssql.version_info())
System:
platform.system()       : Linux
platform.architecture() : ('64bit', 'ELF')
platform.libc_ver()     : ('glibc', '2.35')
Python:
sys.version             : 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
pymssql:
VERSION            : (2, 3, 1)
version            : 2.3.1
full_version       : 2.3.1
dbversion          : freetds v1.4.22
_mssql:
VERSION            : (2, 3, 1)
version            : 2.3.1
full_version       : 2.3.1
dbversion          : freetds v1.4.22
login_timeout      : 60
min_error_severity : 6

**Comment by gordthompson** [comment]
pymssql certainly can resolve instance names if the SQL Browser service is running on the server.

```python
import pymssql

conn = pymssql.connect(
    server=r"192.168.0.100\SQLEXPRESS",
    user="scott",
    password="tiger^5HHH",
    database="test",
)
cursor = conn.cursor()
cursor.execute("SELECT @@SERVERNAME AS foo")
print(cursor.fetchone()) 
# ('WIN7-VB-01\\SQLEXPRESS',)
cursor = conn.cursor()
cursor.execute("SELECT ip_address, port FROM sys.dm_tcp_listener_states")
print(cursor.fetchall()) 
# [('::', 49242), ('0.0.0.0', 49242)]
```

**Comment by rvan1** [comment]
The browser service is running but UDP port 1434 isn't open so are requesting to have it opened, which might fix our issue. Thx.

**Comment by rvan1** [comment]
I can get a result your way with a connection cursor, which returns '49903' for the port, but still doesn't work with airflow MsSqlHook which gets an sqlalchemy engine. So I suppose this is an issue for MsSqlHook, but thought you might know a fix.

**Comment by koolinoor** [comment]
Hi!

I keep getting the same error; no matter what I do..
All the ports are open; server running; c# and enterprise manager is connecting.
I’ve tried python 311 and 312; pymssql 2.8-3.2 
Tds_version 7.0-7.4 

Nothing helps 

Thanks 
Andrew

**Comment by gordthompson** [comment]
@rvan1 - For SQLAlchemy, it would be

```python
import sqlalchemy as sa

engine = sa.create_engine(
    r"mssql+pymssql://scott:tiger^5HHH@192.168.0.100\SQLEXPRESS/test"
)
with engine.connect() as conn:
    result = conn.exec_driver_sql("SELECT @@SERVERNAME AS foo").scalar()
    print(result)
    # WIN7-VB-01\SQLEXPRESS
    result = conn.exec_driver_sql(
        "SELECT ip_address, port FROM sys.dm_tcp_listener_states"
    ).all()
    print(result)
    # [('::', 49242), ('0.0.0.0', 49242)]
```

**Comment by gordthompson** [comment]
@koolinoor - Is your issue specifically related to accessing a SQL Server named instance?

**Comment by gordthompson** [comment]
@koolinoor - More details needed. What does `print(pymssql.version_info())` display?

**Comment by rvan1** [comment]
I find that connection from hook does work:

conn = MsSqlHook('mssql_default').get_conn()

BUt sa engine from hook doesn't for some reason, but I have always used sa engine:

engine = MsSqlHook('mssql_default').get_sqlalchemy_engine()

**Comment by gordthompson** [comment]
@rvan1 - So after you call `.get_sqlalchemy_engine()` does the engine look right?

```python
print(type(engine))
# <class 'sqlalchemy.engine.base.Engine'>
print(engine)
# Engine(mssql+pymssql://scott:***@192.168.0.100\SQLEXPRESS/test))
```

**Comment by rvan1** [comment]
yes i can print the engine...

<class 'sqlalchemy.engine.base.Engine'>
Engine(mssql+pymssql://un:***@srver%5Cinstance:1433/dbase)

**Comment by koolinoor** [comment]
> @koolinoor - More details needed. What does `print(pymssql.version_info())` display?

hey! as I said; i've tested 2.2.8-2.3.1 all versions; with name/localhost, ip address 
cross referencing Tds_version 7.0-7.4

**Comment by koolinoor** [comment]
in sql conf; all protocols are enabled.. as i said; no problem connecting with anyhing else; inc pyodbc
do i need to re-code all the db interfaces?

**Comment by gordthompson** [comment]
@rvan1 - Look closely at your `print(engine)` output.

This can successfully connect:

```python
engine = sa.create_engine(
    r"mssql+pymssql://scott:tiger^5HHH@192.168.0.100\SQLEXPRESS/test"
)
print(engine)
# Engine(mssql+pymssql://scott:***@192.168.0.100\SQLEXPRESS/test)
```

This cannot:

```python
engine = sa.create_engine(
    r"mssql+pymssql://scott:tiger^5HHH@192.168.0.100%5CSQLEXPRESS/test"
)
print(engine)
# Engine(mssql+pymssql://scott:***@192.168.0.100%5CSQLEXPRESS/test)
```

**Comment by gordthompson** [comment]
@koolinoor - At the very least, `pymssql.version_info()` will tell us whether you are running your code on Linux, Windows, or Mac. It would also be helpful to see the results from `SELECT @@VERSION` when you connect to your database using some other method.

**Comment by koolinoor** [comment]
System:
platform.system()       : Windows
platform.architecture() : ('64bit', 'WindowsPE')
Python:
sys.version             : 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
pymssql:
VERSION            : (2, 2, 11)
version            : 2.2.11
full_version       : 2.2.11
dbversion          : freetds v1.4.9
_mssql:
VERSION            : (2, 2, 11)
version            : 2.2.11
full_version       : 2.2.11
dbversion          : freetds v1.4.9
login_timeout      : 60
min_error_severity : 6

**Comment by rvan1** [comment]
I see, but I'm setting the connection URI on the environment without url encoding. By convention airflow will pull connection variables from the environment with 'AIRFLOW_CONN_' prefix, so gets a 'mssql_default' url value from it. That process is url encoding when we don't want/need it to, though when I echo the variable back, it's not url encoded. Double backslash gets same result. Quoting with single or double quotes makes no difference. I notice that SA it makes the instance name into lower case, but not the dbase name.

export AIRFLOW_CONN_MSSQL_DEFAULT='mssql+pyodbc://un:pwdpwdpwd@192.168.1.1\INSTANCE:1433/DBASE'

echo $AIRFLOW_CONN_MSSQL_DEFAULT
mssql+pyodbc://un:pwdpwdpwd@192.168.1.1\INSTANCE:1433/DBASE

**Comment by gordthompson** [comment]
@rvan1 - Okay, so `.get_sqlalchemy_engine()`is apparently quoting the host portion of the URL when it shouldn't, converting `192.168.1.1\INSTANCE` to `192.168.1.1%5CINSTANCE`

Fortunately, you have a workaround until airflow (or whoever) fixes that. You know from earlier testing that the instance is listening on port 49903 so you could use

```bash
export AIRFLOW_CONN_MSSQL_DEFAULT='mssql+pyodbc://un:pwdpwdpwd@192.168.1.1:49903/DBASE'
```

which should work provided that the instance does not change its listening port.

**Comment by rvan1** [comment]
Interesting, you can change the instancename:port to just the instance port. Yes that does work, at least in test script, so will have to try within ariflow next. Thanks for all the tips. I learned some now things about mssql connections in python. I'm good to close out this issue, but I see you're still working with koolinoor so keep at it.

**Comment by gordthompson** [comment]
We only need to supply the instance name OR the port number. If both are supplied then the name takes precedence. So for

```
mssql+pymssql://scott:tiger^5HHH@192.168.0.100\SQLEXPRESS:1433/test
```

the `:1433` is ignored.

**Comment by gordthompson** [comment]
@rvan1 - You can go ahead and close this issue.

**Comment by gordthompson** [comment]
@koolinoor re: "lets be hones [sic]; this library is unstable and unreliable"

It is downloaded from PyPI at an average rate of over 400_000 times *per day*. Pretty popular for an "unstable and unreliable" module.
