### ISSUE TITLE
Request to add "enable tls v1" parameter for connection.

### ISSUE THREAD

**Issue by yongwoo1** [pymssql/pymssql#916]
Starting from FreeTDS 1.4, TLS v1 is not used by default. However, by specifying "enable tls v1 = yes", it is still possible to connect to MS SQL Server using TLS v1. 

Since pymssql now uses FreeTDS version 1.4, it is no longer possible to connect to MS SQL Server 2008 R2 that hasn't applied the TLS 1.2 update. 

I would appreciate it if the latest version of pymssql could also support "enable tls v1" parameter.

If TLS v1 is already supported, please let me know how to enable it.

**Comment by gordthompson** [comment]
The `strace` utility shows me that when I run `pymssql.connect()` it looks for a freetds.conf file in two places

/home/gord/.freetds.conf

and

/usr/local/etc/freetds.conf

So perhaps you could try adding an entry like

```
[global]
enable tls v1 = yes
```

in one of those places and see if it works for you.

**Comment by yongwoo1** [comment]
Thank you very much.

I'm using RHEL 9, and the freetds package included by default uses /etc/freetds.conf as the configuration file, but pymssql seems to ignore that file and instead looks for /usr/local/etc/freetds.conf.

Based on the information you provided, I added the following content to the /usr/local/etc/freetds.conf file:

[global]
enable tls v1 = yes

After testing, it worked perfectly.

**Comment by yongwoo1** [comment]
In some environments (RHEL9 + pymssql 2.3.2 + FreeTDS 1.4.23), the above solution works perfectly. 

However, in a specific environment (RHEL8 + pymssql 2.3.2 + FreeTDS 1.4.16), the solution does not work. 
Even with strace, it does not look for any freetds.conf file, including /usr/local/etc/freetds.conf or ~/.freetds.conf. 

What should I do in such a case?

**Comment by yongwoo1** [comment]
In some environments (RHEL9 + pymssql 2.3.2 + FreeTDS 1.4.23), the above solution works perfectly.

However, in a specific environment (RHEL8 + pymssql 2.3.2 + FreeTDS 1.4.16), the solution does not work.
Even with strace, it does not look for any freetds.conf file, including /usr/local/etc/freetds.conf or ~/.freetds.conf.

What should I do in such a case?

**Comment by gordthompson** [comment]
Does it make any difference if you create a `FREETDS` environment variable? e,g.,

```
export FREETDS=/usr/local/etc/freetds.conf
```

**Comment by termim** [comment]
According to [config.c](https://github.com/FreeTDS/freetds/blob/75fb3192fa4fb2eb8e83392f01f77d8b844a479c/src/tds/config.c#L346) `FREETDS` should point to directory that has `etc/freetds.conf` in it. So, if your config is `/usr/local/etc/freetds.conf`, you should use:
```
export FREETDS=/usr/local
```

Or you can use any name for your config file and set `FREETDSCONF` (see [config.c](https://github.com/FreeTDS/freetds/blob/75fb3192fa4fb2eb8e83392f01f77d8b844a479c/src/tds/config.c#L334)):
```
export FREETDSCONF=/usr/local/etc/freetds.conf
```

**Comment by yongwoo1** [comment]
Thanks so much to everyone who kindly responded. I've learned a lot thanks to all of you. In the RHEL8 environment, I still couldn't fully resolve the issue, so I ended up downgrading pymssql to version 2.2.7. It seems that this won’t be a big issue as the use of RHEL8 will gradually decrease. Thank you again.
