### ISSUE TITLE
document confuse issue

### ISSUE THREAD

**Issue by xinjiboy1234** [pymssql/pymssql#918]
https://pymssql.readthedocs.io/en/stable/pymssql_examples.html#bulk-copy, when i copy and execute the example,  dose not happen anything, without any errors.  and i found the reason for this.  there are missing the commit operation. 
just like this, 

`conn.bulk_copy("example", [(1, 2)] * 1000000)
    conn.commit()`

 i hope fix it ASAP.

**Comment by termim** [comment]
Fixed.
